/*
 * Copyright 2026, MojoProse. All rights reserved.
 * Distributed under the terms of the Apache License v2.0 with LLVM Exceptions.
 *
 * Generated by Haiku/generator/mojobe_gen.py. Do not edit.
 */


/*!	The ABI oracle (Haiku/docs/bridge-design.md, section 12): what the C++
	compiler passes and returns, for Haiku/tests/abi_oracle.mojo to compare
	with what Mojo sees. Hook tables are called slot by slot with known
	arguments; value types and enums are passed and returned around other
	arguments; and a call spills onto the stack.
*/


#include "mojobe.h"

#include <stdint.h>


extern "C" {


int32
mojobe_oracle_BHandler(const mojobe_BHandler_hooks* hooks, void* context)
{
	int32 failures = 0;
	{
		BMessage message0_1(0x6F720001);
		if (hooks->MessageReceived == NULL)
			failures++;
		else
			hooks->MessageReceived(context, reinterpret_cast<BHandler*>(0x10000), &message0_1);
	}
	return failures;
}

int32
mojobe_oracle_BLooper(const mojobe_BLooper_hooks* hooks, void* context)
{
	int32 failures = 0;
	{
		BMessage message0_1(0x6F720001);
		if (hooks->MessageReceived == NULL)
			failures++;
		else
			hooks->MessageReceived(context, reinterpret_cast<BLooper*>(0x10000), &message0_1);
	}
	{
		if (hooks->QuitRequested == NULL)
			failures++;
		else if (hooks->QuitRequested(context, reinterpret_cast<BLooper*>(0x10100)) != true)
			failures++;
	}
	return failures;
}

int32
mojobe_oracle_BApplication(const mojobe_BApplication_hooks* hooks, void* context)
{
	int32 failures = 0;
	{
		if (hooks->ReadyToRun == NULL)
			failures++;
		else
			hooks->ReadyToRun(context, reinterpret_cast<BApplication*>(0x10000));
	}
	{
		BMessage message1_1(0x6F720011);
		if (hooks->MessageReceived == NULL)
			failures++;
		else
			hooks->MessageReceived(context, reinterpret_cast<BApplication*>(0x10100), &message1_1);
	}
	{
		if (hooks->QuitRequested == NULL)
			failures++;
		else if (hooks->QuitRequested(context, reinterpret_cast<BApplication*>(0x10200)) != false)
			failures++;
	}
	{
		if (hooks->AboutRequested == NULL)
			failures++;
		else
			hooks->AboutRequested(context, reinterpret_cast<BApplication*>(0x10300));
	}
	{
		if (hooks->Pulse == NULL)
			failures++;
		else
			hooks->Pulse(context, reinterpret_cast<BApplication*>(0x10400));
	}
	return failures;
}

int32
mojobe_oracle_BWindow(const mojobe_BWindow_hooks* hooks, void* context)
{
	int32 failures = 0;
	{
		BMessage message0_1(0x6F720001);
		if (hooks->MessageReceived == NULL)
			failures++;
		else
			hooks->MessageReceived(context, reinterpret_cast<BWindow*>(0x10000), &message0_1);
	}
	{
		if (hooks->QuitRequested == NULL)
			failures++;
		else if (hooks->QuitRequested(context, reinterpret_cast<BWindow*>(0x10100)) != true)
			failures++;
	}
	{
		if (hooks->FrameMoved == NULL)
			failures++;
		else
			hooks->FrameMoved(context, reinterpret_cast<BWindow*>(0x10200), mojobe_BPoint{21.25, 21.5});
	}
	{
		if (hooks->FrameResized == NULL)
			failures++;
		else
			hooks->FrameResized(context, reinterpret_cast<BWindow*>(0x10300), 3.75, 4.0);
	}
	{
		if (hooks->WindowActivated == NULL)
			failures++;
		else
			hooks->WindowActivated(context, reinterpret_cast<BWindow*>(0x10400), false);
	}
	{
		if (hooks->WorkspaceActivated == NULL)
			failures++;
		else
			hooks->WorkspaceActivated(context, reinterpret_cast<BWindow*>(0x10500), -517, false);
	}
	{
		if (hooks->MenusBeginning == NULL)
			failures++;
		else
			hooks->MenusBeginning(context, reinterpret_cast<BWindow*>(0x10600));
	}
	{
		if (hooks->MenusEnded == NULL)
			failures++;
		else
			hooks->MenusEnded(context, reinterpret_cast<BWindow*>(0x10700));
	}
	{
		if (hooks->Zoom == NULL)
			failures++;
		else
			hooks->Zoom(context, reinterpret_cast<BWindow*>(0x10800), mojobe_BPoint{81.25, 81.5}, 9.0, 9.25);
	}
	{
		if (hooks->Minimize == NULL)
			failures++;
		else
			hooks->Minimize(context, reinterpret_cast<BWindow*>(0x10900), true);
	}
	return failures;
}

int32
mojobe_oracle_BView(const mojobe_BView_hooks* hooks, void* context)
{
	int32 failures = 0;
	{
		if (hooks->Draw == NULL)
			failures++;
		else
			hooks->Draw(context, reinterpret_cast<BView*>(0x10000), mojobe_BRect{1.25, 1.5, 1.75, 2.0});
	}
	{
		if (hooks->DrawAfterChildren == NULL)
			failures++;
		else
			hooks->DrawAfterChildren(context, reinterpret_cast<BView*>(0x10100), mojobe_BRect{11.25, 11.5, 11.75, 12.0});
	}
	{
		if (hooks->MouseDown == NULL)
			failures++;
		else
			hooks->MouseDown(context, reinterpret_cast<BView*>(0x10200), mojobe_BPoint{21.25, 21.5});
	}
	{
		if (hooks->MouseUp == NULL)
			failures++;
		else
			hooks->MouseUp(context, reinterpret_cast<BView*>(0x10300), mojobe_BPoint{31.25, 31.5});
	}
	{
		BMessage message4_3(0x6F720043);
		if (hooks->MouseMoved == NULL)
			failures++;
		else
			hooks->MouseMoved(context, reinterpret_cast<BView*>(0x10400), mojobe_BPoint{41.25, 41.5}, 423, &message4_3);
	}
	{
		if (hooks->KeyDown == NULL)
			failures++;
		else
			hooks->KeyDown(context, reinterpret_cast<BView*>(0x10500), "oracle-5-1-é", -527);
	}
	{
		if (hooks->KeyUp == NULL)
			failures++;
		else
			hooks->KeyUp(context, reinterpret_cast<BView*>(0x10600), "oracle-6-1-é", -627);
	}
	{
		BMessage message7_1(0x6F720071);
		if (hooks->MessageReceived == NULL)
			failures++;
		else
			hooks->MessageReceived(context, reinterpret_cast<BView*>(0x10700), &message7_1);
	}
	{
		if (hooks->AttachedToWindow == NULL)
			failures++;
		else
			hooks->AttachedToWindow(context, reinterpret_cast<BView*>(0x10800));
	}
	{
		if (hooks->AllAttached == NULL)
			failures++;
		else
			hooks->AllAttached(context, reinterpret_cast<BView*>(0x10900));
	}
	{
		if (hooks->DetachedFromWindow == NULL)
			failures++;
		else
			hooks->DetachedFromWindow(context, reinterpret_cast<BView*>(0x10A00));
	}
	{
		if (hooks->AllDetached == NULL)
			failures++;
		else
			hooks->AllDetached(context, reinterpret_cast<BView*>(0x10B00));
	}
	{
		if (hooks->FrameMoved == NULL)
			failures++;
		else
			hooks->FrameMoved(context, reinterpret_cast<BView*>(0x10C00), mojobe_BPoint{121.25, 121.5});
	}
	{
		if (hooks->FrameResized == NULL)
			failures++;
		else
			hooks->FrameResized(context, reinterpret_cast<BView*>(0x10D00), 13.75, 14.0);
	}
	{
		if (hooks->WindowActivated == NULL)
			failures++;
		else
			hooks->WindowActivated(context, reinterpret_cast<BView*>(0x10E00), false);
	}
	{
		if (hooks->Pulse == NULL)
			failures++;
		else
			hooks->Pulse(context, reinterpret_cast<BView*>(0x10F00));
	}
	return failures;
}

mojobe_BRect
mojobe_oracle_echo_BRect(int8 before, mojobe_BRect value, double after,
	mojobe_BRect* seen, int8* seenBefore, double* seenAfter)
{
	*seen = value;
	*seenBefore = before;
	*seenAfter = after;
	mojobe_BRect result = value;
	result.left += 1;
	result.top += 1;
	result.right += 1;
	result.bottom += 1;
	return result;
}

mojobe_BPoint
mojobe_oracle_echo_BPoint(int8 before, mojobe_BPoint value, double after,
	mojobe_BPoint* seen, int8* seenBefore, double* seenAfter)
{
	*seen = value;
	*seenBefore = before;
	*seenAfter = after;
	mojobe_BPoint result = value;
	result.x += 1;
	result.y += 1;
	return result;
}

mojobe_rgb_color
mojobe_oracle_echo_rgb_color(int8 before, mojobe_rgb_color value, double after,
	mojobe_rgb_color* seen, int8* seenBefore, double* seenAfter)
{
	*seen = value;
	*seenBefore = before;
	*seenAfter = after;
	mojobe_rgb_color result = value;
	result.red += 1;
	result.green += 1;
	result.blue += 1;
	result.alpha += 1;
	return result;
}

mojobe_font_height
mojobe_oracle_echo_font_height(int8 before, mojobe_font_height value, double after,
	mojobe_font_height* seen, int8* seenBefore, double* seenAfter)
{
	*seen = value;
	*seenBefore = before;
	*seenAfter = after;
	mojobe_font_height result = value;
	result.ascent += 1;
	result.descent += 1;
	result.leading += 1;
	return result;
}

mojobe_clipping_rect
mojobe_oracle_echo_clipping_rect(int8 before, mojobe_clipping_rect value, double after,
	mojobe_clipping_rect* seen, int8* seenBefore, double* seenAfter)
{
	*seen = value;
	*seenBefore = before;
	*seenAfter = after;
	mojobe_clipping_rect result = value;
	result.left += 1;
	result.top += 1;
	result.right += 1;
	result.bottom += 1;
	return result;
}

mojobe_screen_id
mojobe_oracle_echo_screen_id(int8 before, mojobe_screen_id value, double after,
	mojobe_screen_id* seen, int8* seenBefore, double* seenAfter)
{
	*seen = value;
	*seenBefore = before;
	*seenAfter = after;
	mojobe_screen_id result = value;
	result.id += 1;
	return result;
}

mojobe_pattern
mojobe_oracle_echo_pattern(int8 before, mojobe_pattern value, double after,
	mojobe_pattern* seen, int8* seenBefore, double* seenAfter)
{
	*seen = value;
	*seenBefore = before;
	*seenAfter = after;
	mojobe_pattern result = value;
	for (int j = 0; j < 8; j++)
		result.data[j] += 1;
	return result;
}

BSpacing
mojobe_oracle_echo_BSpacing(int8 before, BSpacing value, double after,
	BSpacing* seen, int8* seenBefore, double* seenAfter)
{
	*seen = value;
	*seenBefore = before;
	*seenAfter = after;
	BSpacing result = value;
	result = (BSpacing)(result + 1);
	return result;
}

alert_type
mojobe_oracle_echo_alert_type(int8 before, alert_type value, double after,
	alert_type* seen, int8* seenBefore, double* seenAfter)
{
	*seen = value;
	*seenBefore = before;
	*seenAfter = after;
	alert_type result = value;
	result = (alert_type)(result + 1);
	return result;
}

alignment
mojobe_oracle_echo_alignment(int8 before, alignment value, double after,
	alignment* seen, int8* seenBefore, double* seenAfter)
{
	*seen = value;
	*seenBefore = before;
	*seenAfter = after;
	alignment result = value;
	result = (alignment)(result + 1);
	return result;
}

alpha_function
mojobe_oracle_echo_alpha_function(int8 before, alpha_function value, double after,
	alpha_function* seen, int8* seenBefore, double* seenAfter)
{
	*seen = value;
	*seenBefore = before;
	*seenAfter = after;
	alpha_function result = value;
	result = (alpha_function)(result + 1);
	return result;
}

bitmap_drawing_options
mojobe_oracle_echo_bitmap_drawing_options(int8 before, bitmap_drawing_options value, double after,
	bitmap_drawing_options* seen, int8* seenBefore, double* seenAfter)
{
	*seen = value;
	*seenBefore = before;
	*seenAfter = after;
	bitmap_drawing_options result = value;
	result = (bitmap_drawing_options)(result + 1);
	return result;
}

bitmap_tiling
mojobe_oracle_echo_bitmap_tiling(int8 before, bitmap_tiling value, double after,
	bitmap_tiling* seen, int8* seenBefore, double* seenAfter)
{
	*seen = value;
	*seenBefore = before;
	*seenAfter = after;
	bitmap_tiling result = value;
	result = (bitmap_tiling)(result + 1);
	return result;
}

border_style
mojobe_oracle_echo_border_style(int8 before, border_style value, double after,
	border_style* seen, int8* seenBefore, double* seenAfter)
{
	*seen = value;
	*seenBefore = before;
	*seenAfter = after;
	border_style result = value;
	result = (border_style)(result + 1);
	return result;
}

buffer_layout
mojobe_oracle_echo_buffer_layout(int8 before, buffer_layout value, double after,
	buffer_layout* seen, int8* seenBefore, double* seenAfter)
{
	*seen = value;
	*seenBefore = before;
	*seenAfter = after;
	buffer_layout result = value;
	result = (buffer_layout)(result + 1);
	return result;
}

buffer_orientation
mojobe_oracle_echo_buffer_orientation(int8 before, buffer_orientation value, double after,
	buffer_orientation* seen, int8* seenBefore, double* seenAfter)
{
	*seen = value;
	*seenBefore = before;
	*seenAfter = after;
	buffer_orientation result = value;
	result = (buffer_orientation)(result + 1);
	return result;
}

button_spacing
mojobe_oracle_echo_button_spacing(int8 before, button_spacing value, double after,
	button_spacing* seen, int8* seenBefore, double* seenAfter)
{
	*seen = value;
	*seenBefore = before;
	*seenAfter = after;
	button_spacing result = value;
	result = (button_spacing)(result + 1);
	return result;
}

button_width
mojobe_oracle_echo_button_width(int8 before, button_width value, double after,
	button_width* seen, int8* seenBefore, double* seenAfter)
{
	*seen = value;
	*seenBefore = before;
	*seenAfter = after;
	button_width result = value;
	result = (button_width)(result + 1);
	return result;
}

cap_mode
mojobe_oracle_echo_cap_mode(int8 before, cap_mode value, double after,
	cap_mode* seen, int8* seenBefore, double* seenAfter)
{
	*seen = value;
	*seenBefore = before;
	*seenAfter = after;
	cap_mode result = value;
	result = (cap_mode)(result + 1);
	return result;
}

color_space
mojobe_oracle_echo_color_space(int8 before, color_space value, double after,
	color_space* seen, int8* seenBefore, double* seenAfter)
{
	*seen = value;
	*seenBefore = before;
	*seenAfter = after;
	color_space result = value;
	result = (color_space)(result + 1);
	return result;
}

color_which
mojobe_oracle_echo_color_which(int8 before, color_which value, double after,
	color_which* seen, int8* seenBefore, double* seenAfter)
{
	*seen = value;
	*seenBefore = before;
	*seenAfter = after;
	color_which result = value;
	result = (color_which)(result + 1);
	return result;
}

command_code
mojobe_oracle_echo_command_code(int8 before, command_code value, double after,
	command_code* seen, int8* seenBefore, double* seenAfter)
{
	*seen = value;
	*seenBefore = before;
	*seenAfter = after;
	command_code result = value;
	result = (command_code)(result + 1);
	return result;
}

coordinate_space
mojobe_oracle_echo_coordinate_space(int8 before, coordinate_space value, double after,
	coordinate_space* seen, int8* seenBefore, double* seenAfter)
{
	*seen = value;
	*seenBefore = before;
	*seenAfter = after;
	coordinate_space result = value;
	result = (coordinate_space)(result + 1);
	return result;
}

cpu_platform
mojobe_oracle_echo_cpu_platform(int8 before, cpu_platform value, double after,
	cpu_platform* seen, int8* seenBefore, double* seenAfter)
{
	*seen = value;
	*seenBefore = before;
	*seenAfter = after;
	cpu_platform result = value;
	result = (cpu_platform)(result + 1);
	return result;
}

cpu_vendor
mojobe_oracle_echo_cpu_vendor(int8 before, cpu_vendor value, double after,
	cpu_vendor* seen, int8* seenBefore, double* seenAfter)
{
	*seen = value;
	*seenBefore = before;
	*seenAfter = after;
	cpu_vendor result = value;
	result = (cpu_vendor)(result + 1);
	return result;
}

drawing_mode
mojobe_oracle_echo_drawing_mode(int8 before, drawing_mode value, double after,
	drawing_mode* seen, int8* seenBefore, double* seenAfter)
{
	*seen = value;
	*seenBefore = before;
	*seenAfter = after;
	drawing_mode result = value;
	result = (drawing_mode)(result + 1);
	return result;
}

font_direction
mojobe_oracle_echo_font_direction(int8 before, font_direction value, double after,
	font_direction* seen, int8* seenBefore, double* seenAfter)
{
	*seen = value;
	*seenBefore = before;
	*seenAfter = after;
	font_direction result = value;
	result = (font_direction)(result + 1);
	return result;
}

font_file_format
mojobe_oracle_echo_font_file_format(int8 before, font_file_format value, double after,
	font_file_format* seen, int8* seenBefore, double* seenAfter)
{
	*seen = value;
	*seenBefore = before;
	*seenAfter = after;
	font_file_format result = value;
	result = (font_file_format)(result + 1);
	return result;
}

font_metric_mode
mojobe_oracle_echo_font_metric_mode(int8 before, font_metric_mode value, double after,
	font_metric_mode* seen, int8* seenBefore, double* seenAfter)
{
	*seen = value;
	*seenBefore = before;
	*seenAfter = after;
	font_metric_mode result = value;
	result = (font_metric_mode)(result + 1);
	return result;
}

hash_mark_location
mojobe_oracle_echo_hash_mark_location(int8 before, hash_mark_location value, double after,
	hash_mark_location* seen, int8* seenBefore, double* seenAfter)
{
	*seen = value;
	*seenBefore = before;
	*seenAfter = after;
	hash_mark_location result = value;
	result = (hash_mark_location)(result + 1);
	return result;
}

image_type
mojobe_oracle_echo_image_type(int8 before, image_type value, double after,
	image_type* seen, int8* seenBefore, double* seenAfter)
{
	*seen = value;
	*seenBefore = before;
	*seenAfter = after;
	image_type result = value;
	result = (image_type)(result + 1);
	return result;
}

join_mode
mojobe_oracle_echo_join_mode(int8 before, join_mode value, double after,
	join_mode* seen, int8* seenBefore, double* seenAfter)
{
	*seen = value;
	*seenBefore = before;
	*seenAfter = after;
	join_mode result = value;
	result = (join_mode)(result + 1);
	return result;
}

menu_bar_border
mojobe_oracle_echo_menu_bar_border(int8 before, menu_bar_border value, double after,
	menu_bar_border* seen, int8* seenBefore, double* seenAfter)
{
	*seen = value;
	*seenBefore = before;
	*seenAfter = after;
	menu_bar_border result = value;
	result = (menu_bar_border)(result + 1);
	return result;
}

menu_layout
mojobe_oracle_echo_menu_layout(int8 before, menu_layout value, double after,
	menu_layout* seen, int8* seenBefore, double* seenAfter)
{
	*seen = value;
	*seenBefore = before;
	*seenAfter = after;
	menu_layout result = value;
	result = (menu_layout)(result + 1);
	return result;
}

mode_focus_follows_mouse
mojobe_oracle_echo_mode_focus_follows_mouse(int8 before, mode_focus_follows_mouse value, double after,
	mode_focus_follows_mouse* seen, int8* seenBefore, double* seenAfter)
{
	*seen = value;
	*seenBefore = before;
	*seenAfter = after;
	mode_focus_follows_mouse result = value;
	result = (mode_focus_follows_mouse)(result + 1);
	return result;
}

mode_mouse
mojobe_oracle_echo_mode_mouse(int8 before, mode_mouse value, double after,
	mode_mouse* seen, int8* seenBefore, double* seenAfter)
{
	*seen = value;
	*seenBefore = before;
	*seenAfter = after;
	mode_mouse result = value;
	result = (mode_mouse)(result + 1);
	return result;
}

orientation
mojobe_oracle_echo_orientation(int8 before, orientation value, double after,
	orientation* seen, int8* seenBefore, double* seenAfter)
{
	*seen = value;
	*seenBefore = before;
	*seenAfter = after;
	orientation result = value;
	result = (orientation)(result + 1);
	return result;
}

overlay_options
mojobe_oracle_echo_overlay_options(int8 before, overlay_options value, double after,
	overlay_options* seen, int8* seenBefore, double* seenAfter)
{
	*seen = value;
	*seenBefore = before;
	*seenAfter = after;
	overlay_options result = value;
	result = (overlay_options)(result + 1);
	return result;
}

rect_tracking_style
mojobe_oracle_echo_rect_tracking_style(int8 before, rect_tracking_style value, double after,
	rect_tracking_style* seen, int8* seenBefore, double* seenAfter)
{
	*seen = value;
	*seenBefore = before;
	*seenAfter = after;
	rect_tracking_style result = value;
	result = (rect_tracking_style)(result + 1);
	return result;
}

set_font_mask
mojobe_oracle_echo_set_font_mask(int8 before, set_font_mask value, double after,
	set_font_mask* seen, int8* seenBefore, double* seenAfter)
{
	*seen = value;
	*seenBefore = before;
	*seenAfter = after;
	set_font_mask result = value;
	result = (set_font_mask)(result + 1);
	return result;
}

source_alpha
mojobe_oracle_echo_source_alpha(int8 before, source_alpha value, double after,
	source_alpha* seen, int8* seenBefore, double* seenAfter)
{
	*seen = value;
	*seenBefore = before;
	*seenAfter = after;
	source_alpha result = value;
	result = (source_alpha)(result + 1);
	return result;
}

swap_action
mojobe_oracle_echo_swap_action(int8 before, swap_action value, double after,
	swap_action* seen, int8* seenBefore, double* seenAfter)
{
	*seen = value;
	*seenBefore = before;
	*seenAfter = after;
	swap_action result = value;
	result = (swap_action)(result + 1);
	return result;
}

thread_state
mojobe_oracle_echo_thread_state(int8 before, thread_state value, double after,
	thread_state* seen, int8* seenBefore, double* seenAfter)
{
	*seen = value;
	*seenBefore = before;
	*seenAfter = after;
	thread_state result = value;
	result = (thread_state)(result + 1);
	return result;
}

thumb_style
mojobe_oracle_echo_thumb_style(int8 before, thumb_style value, double after,
	thumb_style* seen, int8* seenBefore, double* seenAfter)
{
	*seen = value;
	*seenBefore = before;
	*seenAfter = after;
	thumb_style result = value;
	result = (thumb_style)(result + 1);
	return result;
}

topology_level_type
mojobe_oracle_echo_topology_level_type(int8 before, topology_level_type value, double after,
	topology_level_type* seen, int8* seenBefore, double* seenAfter)
{
	*seen = value;
	*seenBefore = before;
	*seenAfter = after;
	topology_level_type result = value;
	result = (topology_level_type)(result + 1);
	return result;
}

undo_state
mojobe_oracle_echo_undo_state(int8 before, undo_state value, double after,
	undo_state* seen, int8* seenBefore, double* seenAfter)
{
	*seen = value;
	*seenBefore = before;
	*seenAfter = after;
	undo_state result = value;
	result = (undo_state)(result + 1);
	return result;
}

vertical_alignment
mojobe_oracle_echo_vertical_alignment(int8 before, vertical_alignment value, double after,
	vertical_alignment* seen, int8* seenBefore, double* seenAfter)
{
	*seen = value;
	*seenBefore = before;
	*seenAfter = after;
	vertical_alignment result = value;
	result = (vertical_alignment)(result + 1);
	return result;
}

window_alignment
mojobe_oracle_echo_window_alignment(int8 before, window_alignment value, double after,
	window_alignment* seen, int8* seenBefore, double* seenAfter)
{
	*seen = value;
	*seenBefore = before;
	*seenAfter = after;
	window_alignment result = value;
	result = (window_alignment)(result + 1);
	return result;
}

window_feel
mojobe_oracle_echo_window_feel(int8 before, window_feel value, double after,
	window_feel* seen, int8* seenBefore, double* seenAfter)
{
	*seen = value;
	*seenBefore = before;
	*seenAfter = after;
	window_feel result = value;
	result = (window_feel)(result + 1);
	return result;
}

window_look
mojobe_oracle_echo_window_look(int8 before, window_look value, double after,
	window_look* seen, int8* seenBefore, double* seenAfter)
{
	*seen = value;
	*seenBefore = before;
	*seenAfter = after;
	window_look result = value;
	result = (window_look)(result + 1);
	return result;
}

window_type
mojobe_oracle_echo_window_type(int8 before, window_type value, double after,
	window_type* seen, int8* seenBefore, double* seenAfter)
{
	*seen = value;
	*seenBefore = before;
	*seenAfter = after;
	window_type result = value;
	result = (window_type)(result + 1);
	return result;
}

double
mojobe_oracle_stack(int32 a0, int32 a1, int32 a2, int32 a3, int32 a4, int32 a5, int32 a6, int32 a7, int32 a8, int32 a9, int32 a10, int32 a11,
	float f0, float f1, float f2, float f3, float f4, float f5, float f6, float f7, float f8, float f9,
	bool b, int8 i8, uint16 u16, int64 i64, uint64 u64, double d)
{
	return a0 * 1.0 + a1 * 2.0 + a2 * 3.0 + a3 * 4.0 + a4 * 5.0 + a5 * 6.0 + a6 * 7.0 + a7 * 8.0 + a8 * 9.0 + a9 * 10.0 + a10 * 11.0 + a11 * 12.0
		+ f0 * 0.5 + f1 * 1.0 + f2 * 1.5 + f3 * 2.0 + f4 * 2.5 + f5 * 3.0 + f6 * 3.5 + f7 * 4.0 + f8 * 4.5 + f9 * 5.0
		+ (b ? 1000.0 : 0.0) + i8 * 3.0 + u16 * 5.0 + i64 * 7.0 + u64 * 11.0
		+ d * 13.0;
}


}	// extern "C"
