"""The Haiku (Prose) arm64 sysroot, for cross-compiling from the Mac.

Unlike the other sysroots, this one is not copied into the repository: it
stays where tools/haiku/make-sysroot.sh put it, on a case-sensitive volume, and
the toolchain passes its absolute path. Haiku's headers need a case-sensitive
filesystem -- libstdc++'s <clocale> asks for <locale.h>, and on a
case-insensitive one the search finds the Locale Kit's os/locale/Locale.h
before posix/locale.h -- and Bazel's execroot and sandboxes may not be on one.

The path comes from the HAIKU_SYSROOT repository environment variable
(--repo_env=HAIKU_SYSROOT=... in local.bazelrc). Unset, the repository is
empty and nothing but a Haiku build notices. The generated defs.bzl carries a
stamp of the sysroot's contents, which the toolchain passes to every Haiku
action, so a rebuilt sysroot re-keys them.
"""

_REQUIRED = [
    "boot/system/develop/headers/posix/stdio.h",
    "boot/system/develop/headers/os/kernel/OS.h",
    "boot/system/develop/headers/c++/cstdio",
    "boot/system/develop/lib/crti.o",
    "boot/system/develop/lib/crtbeginS.o",
    "boot/system/develop/lib/start_dyn.o",
    "boot/system/develop/lib/libroot.so",
    "boot/system/develop/lib/libstdc++.so",
]

def _haiku_sysroot_repository_impl(rctx):
    path = rctx.getenv("HAIKU_SYSROOT") or ""
    stamp = ""
    if path:
        root = rctx.path(path)
        for required in _REQUIRED:
            if not root.get_child(required).exists:
                fail(("HAIKU_SYSROOT={} has no {}. Assemble it with " +
                      "tools/haiku/make-sysroot.sh (on a case-sensitive " +
                      "volume).").format(path, required))

        # Names and sizes of everything in it: cheap, and changes whenever
        # make-sysroot.sh copies in a different header or library.
        result = rctx.execute(
            ["/bin/sh", "-c", "cd \"$0\" && find . \\( -type f -o -type l \\) " +
                              "-exec stat -f '%N %z' {} + | LC_ALL=C sort | " +
                              "shasum -a 256", path],
            quiet = True,
        )
        if result.return_code != 0:
            fail("could not stamp HAIKU_SYSROOT={}: {}".format(path, result.stderr))
        stamp = result.stdout.split(" ")[0][:16]

    rctx.file("BUILD.bazel", 'exports_files(["defs.bzl"])\n')
    rctx.file("defs.bzl", "\n".join([
        '"""Generated by haiku_sysroot_repository."""',
        "",
        'HAIKU_SYSROOT = "{}"'.format(path),
        'HAIKU_SYSROOT_STAMP = "{}"'.format(stamp),
        "",
    ]))

haiku_sysroot_repository = repository_rule(
    implementation = _haiku_sysroot_repository_impl,
    environ = ["HAIKU_SYSROOT"],
    local = True,
)
