# ===----------------------------------------------------------------------=== #
# Copyright (c) 2026, MojoProse. All rights reserved.
#
# Licensed under the Apache License v2.0 with LLVM Exceptions:
# https://llvm.org/LICENSE.txt
#
# Generated by Haiku/generator/mojobe_gen.py from the Haiku headers and
# bridge.toml. Do not edit: change the generator or its annotations.
# ===----------------------------------------------------------------------=== #
"""The ABI oracle (Haiku/docs/bridge-design.md, section 12), generated
with the bridge: C++ calls every slot of each hook table through the
bridge's own trampolines with known arguments, and a Mojo type that
implements every hook checks what arrives; value types and enums go
both ways by value around other arguments; and a call spills onto the
stack. Prints PASS or FAIL for each, then `SELFTEST PASS n/n`.

Build on Prose with liboracle.so (Haiku/bridge/oracle/oracle.cpp):
    mojo build -I Haiku/bridge abi_oracle.mojo -o abi_oracle \
        -Xlinker -L. -Xlinker -loracle -Xlinker -lmojobe -Xlinker -lbe
"""

from std.ffi import external_call

from haiku import *
from haiku._api import _BHandler_hooks, _BLooper_hooks, _BApplication_hooks, _BWindow_hooks, _BView_hooks
from haiku._core import _addr, _destroy, _to_heap
from haiku.hooks import *


struct Checks:
    var passed: Int
    var failed: Int

    def __init__(out self):
        self.passed = 0
        self.failed = 0

    def check(mut self, what: String, ok: Bool):
        if ok:
            self.passed += 1
            print("PASS:", what)
        else:
            self.failed += 1
            print("FAIL:", what)


struct OracleBHandler(HandlerMessageReceived, Movable):
    """Every hook of `BHandler`, checking its arguments."""

    var calls: Int
    var wrong: Int

    def __init__(out self):
        self.calls = 0
        self.wrong = 0

    def expect(mut self, what: String, ok: Bool):
        if not ok:
            self.wrong += 1
            print("  wrong:", what)

    def MessageReceived(
        mut self,
        handler: BHandlerRef[_],
        message: BMessageRef[_],
    ):
        self.calls += 1
        self.expect("MessageReceived handler", _addr(handler._ptr) == 0x10000)
        self.expect("MessageReceived message", message.what == 0x6F720001)


struct OracleBLooper(LooperMessageReceived, LooperQuitRequested, Movable):
    """Every hook of `BLooper`, checking its arguments."""

    var calls: Int
    var wrong: Int

    def __init__(out self):
        self.calls = 0
        self.wrong = 0

    def expect(mut self, what: String, ok: Bool):
        if not ok:
            self.wrong += 1
            print("  wrong:", what)

    def MessageReceived(
        mut self,
        looper: BLooperRef[_],
        message: BMessageRef[_],
    ):
        self.calls += 1
        self.expect("MessageReceived looper", _addr(looper._ptr) == 0x10000)
        self.expect("MessageReceived message", message.what == 0x6F720001)

    def QuitRequested(mut self, looper: BLooperRef[_]) -> Bool:
        self.calls += 1
        self.expect("QuitRequested looper", _addr(looper._ptr) == 0x10100)
        return True


struct OracleBApplication(
    ApplicationReadyToRun,
    ApplicationMessageReceived,
    ApplicationQuitRequested,
    ApplicationAboutRequested,
    ApplicationPulse,
    Movable,
):
    """Every hook of `BApplication`, checking its arguments."""

    var calls: Int
    var wrong: Int

    def __init__(out self):
        self.calls = 0
        self.wrong = 0

    def expect(mut self, what: String, ok: Bool):
        if not ok:
            self.wrong += 1
            print("  wrong:", what)

    def ReadyToRun(mut self, application: BApplicationRef[_]):
        self.calls += 1
        self.expect(
            "ReadyToRun application",
            _addr(application._ptr) == 0x10000,
        )

    def MessageReceived(
        mut self,
        application: BApplicationRef[_],
        message: BMessageRef[_],
    ):
        self.calls += 1
        self.expect(
            "MessageReceived application",
            _addr(application._ptr) == 0x10100,
        )
        self.expect("MessageReceived message", message.what == 0x6F720011)

    def QuitRequested(mut self, application: BApplicationRef[_]) -> Bool:
        self.calls += 1
        self.expect(
            "QuitRequested application",
            _addr(application._ptr) == 0x10200,
        )
        return False

    def AboutRequested(mut self, application: BApplicationRef[_]):
        self.calls += 1
        self.expect(
            "AboutRequested application",
            _addr(application._ptr) == 0x10300,
        )

    def Pulse(mut self, application: BApplicationRef[_]):
        self.calls += 1
        self.expect("Pulse application", _addr(application._ptr) == 0x10400)


struct OracleBWindow(
    WindowMessageReceived,
    WindowQuitRequested,
    WindowFrameMoved,
    WindowFrameResized,
    WindowWindowActivated,
    WindowWorkspaceActivated,
    WindowMenusBeginning,
    WindowMenusEnded,
    WindowZoom,
    WindowMinimize,
    Movable,
):
    """Every hook of `BWindow`, checking its arguments."""

    var calls: Int
    var wrong: Int

    def __init__(out self):
        self.calls = 0
        self.wrong = 0

    def expect(mut self, what: String, ok: Bool):
        if not ok:
            self.wrong += 1
            print("  wrong:", what)

    def MessageReceived(
        mut self,
        window: BWindowRef[_],
        message: BMessageRef[_],
    ):
        self.calls += 1
        self.expect("MessageReceived window", _addr(window._ptr) == 0x10000)
        self.expect("MessageReceived message", message.what == 0x6F720001)

    def QuitRequested(mut self, window: BWindowRef[_]) -> Bool:
        self.calls += 1
        self.expect("QuitRequested window", _addr(window._ptr) == 0x10100)
        return True

    def FrameMoved(mut self, window: BWindowRef[_], newPosition: BPoint):
        self.calls += 1
        self.expect("FrameMoved window", _addr(window._ptr) == 0x10200)
        self.expect(
            "FrameMoved newPosition",
            newPosition == BPoint(21.25, 21.5),
        )

    def FrameResized(
        mut self,
        window: BWindowRef[_],
        newWidth: Float32,
        newHeight: Float32,
    ):
        self.calls += 1
        self.expect("FrameResized window", _addr(window._ptr) == 0x10300)
        self.expect("FrameResized newWidth", newWidth == 3.75)
        self.expect("FrameResized newHeight", newHeight == 4.0)

    def WindowActivated(mut self, window: BWindowRef[_], focus: Bool):
        self.calls += 1
        self.expect("WindowActivated window", _addr(window._ptr) == 0x10400)
        self.expect("WindowActivated focus", focus == False)

    def WorkspaceActivated(
        mut self,
        window: BWindowRef[_],
        workspace: Int32,
        state: Bool,
    ):
        self.calls += 1
        self.expect("WorkspaceActivated window", _addr(window._ptr) == 0x10500)
        self.expect("WorkspaceActivated workspace", workspace == -517)
        self.expect("WorkspaceActivated state", state == False)

    def MenusBeginning(mut self, window: BWindowRef[_]):
        self.calls += 1
        self.expect("MenusBeginning window", _addr(window._ptr) == 0x10600)

    def MenusEnded(mut self, window: BWindowRef[_]):
        self.calls += 1
        self.expect("MenusEnded window", _addr(window._ptr) == 0x10700)

    def Zoom(
        mut self,
        window: BWindowRef[_],
        origin: BPoint,
        width: Float32,
        height: Float32,
    ):
        self.calls += 1
        self.expect("Zoom window", _addr(window._ptr) == 0x10800)
        self.expect("Zoom origin", origin == BPoint(81.25, 81.5))
        self.expect("Zoom width", width == 9.0)
        self.expect("Zoom height", height == 9.25)

    def Minimize(mut self, window: BWindowRef[_], minimize: Bool):
        self.calls += 1
        self.expect("Minimize window", _addr(window._ptr) == 0x10900)
        self.expect("Minimize minimize", minimize == True)


struct OracleBView(
    ViewDraw,
    ViewDrawAfterChildren,
    ViewMouseDown,
    ViewMouseUp,
    ViewMouseMoved,
    ViewKeyDown,
    ViewKeyUp,
    ViewMessageReceived,
    ViewAttachedToWindow,
    ViewAllAttached,
    ViewDetachedFromWindow,
    ViewAllDetached,
    ViewFrameMoved,
    ViewFrameResized,
    ViewWindowActivated,
    ViewPulse,
    Movable,
):
    """Every hook of `BView`, checking its arguments."""

    var calls: Int
    var wrong: Int

    def __init__(out self):
        self.calls = 0
        self.wrong = 0

    def expect(mut self, what: String, ok: Bool):
        if not ok:
            self.wrong += 1
            print("  wrong:", what)

    def Draw(mut self, view: BViewRef[_], updateRect: BRect):
        self.calls += 1
        self.expect("Draw view", _addr(view._ptr) == 0x10000)
        self.expect(
            "Draw updateRect",
            updateRect == BRect(1.25, 1.5, 1.75, 2.0),
        )

    def DrawAfterChildren(mut self, view: BViewRef[_], updateRect: BRect):
        self.calls += 1
        self.expect("DrawAfterChildren view", _addr(view._ptr) == 0x10100)
        self.expect(
            "DrawAfterChildren updateRect",
            updateRect == BRect(11.25, 11.5, 11.75, 12.0),
        )

    def MouseDown(mut self, view: BViewRef[_], where: BPoint):
        self.calls += 1
        self.expect("MouseDown view", _addr(view._ptr) == 0x10200)
        self.expect("MouseDown where", where == BPoint(21.25, 21.5))

    def MouseUp(mut self, view: BViewRef[_], where: BPoint):
        self.calls += 1
        self.expect("MouseUp view", _addr(view._ptr) == 0x10300)
        self.expect("MouseUp where", where == BPoint(31.25, 31.5))

    def MouseMoved(
        mut self,
        view: BViewRef[_],
        where: BPoint,
        code: UInt32,
        dragMessage: BMessageRef[_],
    ):
        self.calls += 1
        self.expect("MouseMoved view", _addr(view._ptr) == 0x10400)
        self.expect("MouseMoved where", where == BPoint(41.25, 41.5))
        self.expect("MouseMoved code", code == 423)
        self.expect("MouseMoved dragMessage", dragMessage.what == 0x6F720043)

    def KeyDown(mut self, view: BViewRef[_], bytes: String, numBytes: Int32):
        self.calls += 1
        self.expect("KeyDown view", _addr(view._ptr) == 0x10500)
        self.expect("KeyDown bytes", bytes == "oracle-5-1-é")
        self.expect("KeyDown numBytes", numBytes == -527)

    def KeyUp(mut self, view: BViewRef[_], bytes: String, numBytes: Int32):
        self.calls += 1
        self.expect("KeyUp view", _addr(view._ptr) == 0x10600)
        self.expect("KeyUp bytes", bytes == "oracle-6-1-é")
        self.expect("KeyUp numBytes", numBytes == -627)

    def MessageReceived(mut self, view: BViewRef[_], message: BMessageRef[_]):
        self.calls += 1
        self.expect("MessageReceived view", _addr(view._ptr) == 0x10700)
        self.expect("MessageReceived message", message.what == 0x6F720071)

    def AttachedToWindow(mut self, view: BViewRef[_]):
        self.calls += 1
        self.expect("AttachedToWindow view", _addr(view._ptr) == 0x10800)

    def AllAttached(mut self, view: BViewRef[_]):
        self.calls += 1
        self.expect("AllAttached view", _addr(view._ptr) == 0x10900)

    def DetachedFromWindow(mut self, view: BViewRef[_]):
        self.calls += 1
        self.expect("DetachedFromWindow view", _addr(view._ptr) == 0x10A00)

    def AllDetached(mut self, view: BViewRef[_]):
        self.calls += 1
        self.expect("AllDetached view", _addr(view._ptr) == 0x10B00)

    def FrameMoved(mut self, view: BViewRef[_], newPosition: BPoint):
        self.calls += 1
        self.expect("FrameMoved view", _addr(view._ptr) == 0x10C00)
        self.expect(
            "FrameMoved newPosition",
            newPosition == BPoint(121.25, 121.5),
        )

    def FrameResized(
        mut self,
        view: BViewRef[_],
        newWidth: Float32,
        newHeight: Float32,
    ):
        self.calls += 1
        self.expect("FrameResized view", _addr(view._ptr) == 0x10D00)
        self.expect("FrameResized newWidth", newWidth == 13.75)
        self.expect("FrameResized newHeight", newHeight == 14.0)

    def WindowActivated(mut self, view: BViewRef[_], active: Bool):
        self.calls += 1
        self.expect("WindowActivated view", _addr(view._ptr) == 0x10E00)
        self.expect("WindowActivated active", active == False)

    def Pulse(mut self, view: BViewRef[_]):
        self.calls += 1
        self.expect("Pulse view", _addr(view._ptr) == 0x10F00)


def main() raises:
    var checks = Checks()

    # BHandler's hooks, through its generated table and trampolines
    var hooksBHandler = _BHandler_hooks[OracleBHandler]()
    var contextBHandler = _to_heap(OracleBHandler())
    var failuresBHandler = external_call["mojobe_oracle_BHandler", Int32](
        Pointer(to=hooksBHandler),
        contextBHandler,
    )
    ref seenBHandler = contextBHandler.unsafe_bitcast[OracleBHandler]()[]
    checks.check("BHandler: all 1 hooks called, their results seen by C++",
        seenBHandler.calls == 1 and failuresBHandler == 0)
    checks.check(
        "BHandler: every argument as C++ passed it",
        seenBHandler.wrong == 0,
    )
    _destroy[OracleBHandler](contextBHandler)

    # BLooper's hooks, through its generated table and trampolines
    var hooksBLooper = _BLooper_hooks[OracleBLooper]()
    var contextBLooper = _to_heap(OracleBLooper())
    var failuresBLooper = external_call["mojobe_oracle_BLooper", Int32](
        Pointer(to=hooksBLooper),
        contextBLooper,
    )
    ref seenBLooper = contextBLooper.unsafe_bitcast[OracleBLooper]()[]
    checks.check("BLooper: all 2 hooks called, their results seen by C++",
        seenBLooper.calls == 2 and failuresBLooper == 0)
    checks.check(
        "BLooper: every argument as C++ passed it",
        seenBLooper.wrong == 0,
    )
    _destroy[OracleBLooper](contextBLooper)

    # BApplication's hooks, through its generated table and trampolines
    var hooksBApplication = _BApplication_hooks[OracleBApplication]()
    var contextBApplication = _to_heap(OracleBApplication())
    var failuresBApplication = external_call["mojobe_oracle_BApplication", Int32](
        Pointer(to=hooksBApplication),
        contextBApplication,
    )
    ref seenBApplication = contextBApplication.unsafe_bitcast[OracleBApplication]()[]
    checks.check("BApplication: all 5 hooks called, their results seen by C++",
        seenBApplication.calls == 5 and failuresBApplication == 0)
    checks.check(
        "BApplication: every argument as C++ passed it",
        seenBApplication.wrong == 0,
    )
    _destroy[OracleBApplication](contextBApplication)

    # BWindow's hooks, through its generated table and trampolines
    var hooksBWindow = _BWindow_hooks[OracleBWindow]()
    var contextBWindow = _to_heap(OracleBWindow())
    var failuresBWindow = external_call["mojobe_oracle_BWindow", Int32](
        Pointer(to=hooksBWindow),
        contextBWindow,
    )
    ref seenBWindow = contextBWindow.unsafe_bitcast[OracleBWindow]()[]
    checks.check("BWindow: all 10 hooks called, their results seen by C++",
        seenBWindow.calls == 10 and failuresBWindow == 0)
    checks.check(
        "BWindow: every argument as C++ passed it",
        seenBWindow.wrong == 0,
    )
    _destroy[OracleBWindow](contextBWindow)

    # BView's hooks, through its generated table and trampolines
    var hooksBView = _BView_hooks[OracleBView]()
    var contextBView = _to_heap(OracleBView())
    var failuresBView = external_call["mojobe_oracle_BView", Int32](
        Pointer(to=hooksBView),
        contextBView,
    )
    ref seenBView = contextBView.unsafe_bitcast[OracleBView]()[]
    checks.check("BView: all 16 hooks called, their results seen by C++",
        seenBView.calls == 16 and failuresBView == 0)
    checks.check("BView: every argument as C++ passed it", seenBView.wrong == 0)
    _destroy[OracleBView](contextBView)

    var givenBRect = BRect(0.25, 1.25, 2.25, 3.25)
    var seenBRect = givenBRect
    var beforeBRect = Int8(0)
    var afterBRect = Float64(0)
    var resultBRect = external_call["mojobe_oracle_echo_BRect", BRect](
        Int8(-5), givenBRect, Float64(2.75), Pointer(to=seenBRect),
        Pointer(to=beforeBRect), Pointer(to=afterBRect))
    checks.check("BRect by value, between an int8 and a double",
        seenBRect == givenBRect and beforeBRect == -5 and afterBRect == 2.75)
    checks.check("BRect returned", resultBRect == BRect(1.25, 2.25, 3.25, 4.25))

    var givenBPoint = BPoint(0.25, 1.25)
    var seenBPoint = givenBPoint
    var beforeBPoint = Int8(0)
    var afterBPoint = Float64(0)
    var resultBPoint = external_call["mojobe_oracle_echo_BPoint", BPoint](
        Int8(-5), givenBPoint, Float64(2.75), Pointer(to=seenBPoint),
        Pointer(to=beforeBPoint), Pointer(to=afterBPoint))
    checks.check("BPoint by value, between an int8 and a double",
        seenBPoint == givenBPoint and beforeBPoint == -5 and afterBPoint == 2.75)
    checks.check("BPoint returned", resultBPoint == BPoint(1.25, 2.25))

    var givenrgb_color = rgb_color(2, 9, 16, 23)
    var seenrgb_color = givenrgb_color
    var beforergb_color = Int8(0)
    var afterrgb_color = Float64(0)
    var resultrgb_color = external_call["mojobe_oracle_echo_rgb_color", rgb_color](
        Int8(-5), givenrgb_color, Float64(2.75), Pointer(to=seenrgb_color),
        Pointer(to=beforergb_color), Pointer(to=afterrgb_color))
    checks.check("rgb_color by value, between an int8 and a double",
        seenrgb_color == givenrgb_color and beforergb_color == -5 and afterrgb_color == 2.75)
    checks.check(
        "rgb_color returned",
        resultrgb_color == rgb_color(3, 10, 17, 24),
    )

    var givenpattern = pattern(2747508133085382659)
    var seenpattern = givenpattern
    var beforepattern = Int8(0)
    var afterpattern = Float64(0)
    var resultpattern = external_call["mojobe_oracle_echo_pattern", pattern](
        Int8(-5), givenpattern, Float64(2.75), Pointer(to=seenpattern),
        Pointer(to=beforepattern), Pointer(to=afterpattern))
    checks.check("pattern by value, between an int8 and a double",
        seenpattern == givenpattern and beforepattern == -5 and afterpattern == 2.75)
    checks.check(
        "pattern returned",
        resultpattern == pattern(2819848305923459332),
    )

    var givenBSpacing = BSpacing(-3)
    var seenBSpacing = givenBSpacing
    var beforeBSpacing = Int8(0)
    var afterBSpacing = Float64(0)
    var resultBSpacing = external_call["mojobe_oracle_echo_BSpacing", BSpacing](
        Int8(-5), givenBSpacing, Float64(2.75), Pointer(to=seenBSpacing),
        Pointer(to=beforeBSpacing), Pointer(to=afterBSpacing))
    checks.check("BSpacing by value, between an int8 and a double",
        seenBSpacing == givenBSpacing and beforeBSpacing == -5 and afterBSpacing == 2.75)
    checks.check("BSpacing returned", resultBSpacing == BSpacing(-2))

    var givenalignment = alignment(-3)
    var seenalignment = givenalignment
    var beforealignment = Int8(0)
    var afteralignment = Float64(0)
    var resultalignment = external_call["mojobe_oracle_echo_alignment", alignment](
        Int8(-5), givenalignment, Float64(2.75), Pointer(to=seenalignment),
        Pointer(to=beforealignment), Pointer(to=afteralignment))
    checks.check("alignment by value, between an int8 and a double",
        seenalignment == givenalignment and beforealignment == -5 and afteralignment == 2.75)
    checks.check("alignment returned", resultalignment == alignment(-2))

    var givenalpha_function = alpha_function(3)
    var seenalpha_function = givenalpha_function
    var beforealpha_function = Int8(0)
    var afteralpha_function = Float64(0)
    var resultalpha_function = external_call["mojobe_oracle_echo_alpha_function", alpha_function](
        Int8(-5), givenalpha_function, Float64(2.75), Pointer(
            to=seenalpha_function,
        ),
        Pointer(to=beforealpha_function), Pointer(to=afteralpha_function))
    checks.check("alpha_function by value, between an int8 and a double",
        seenalpha_function == givenalpha_function and beforealpha_function == -5 and afteralpha_function == 2.75)
    checks.check(
        "alpha_function returned",
        resultalpha_function == alpha_function(4),
    )

    var givenbitmap_drawing_options = bitmap_drawing_options(3)
    var seenbitmap_drawing_options = givenbitmap_drawing_options
    var beforebitmap_drawing_options = Int8(0)
    var afterbitmap_drawing_options = Float64(0)
    var resultbitmap_drawing_options = external_call["mojobe_oracle_echo_bitmap_drawing_options", bitmap_drawing_options](
        Int8(-5), givenbitmap_drawing_options, Float64(2.75), Pointer(
            to=seenbitmap_drawing_options,
        ),
        Pointer(to=beforebitmap_drawing_options), Pointer(
            to=afterbitmap_drawing_options,
        ))
    checks.check("bitmap_drawing_options by value, between an int8 and a double",
        seenbitmap_drawing_options == givenbitmap_drawing_options and beforebitmap_drawing_options == -5 and afterbitmap_drawing_options == 2.75)
    checks.check(
        "bitmap_drawing_options returned",
        resultbitmap_drawing_options == bitmap_drawing_options(4),
    )

    var givenbitmap_tiling = bitmap_tiling(3)
    var seenbitmap_tiling = givenbitmap_tiling
    var beforebitmap_tiling = Int8(0)
    var afterbitmap_tiling = Float64(0)
    var resultbitmap_tiling = external_call["mojobe_oracle_echo_bitmap_tiling", bitmap_tiling](
        Int8(-5), givenbitmap_tiling, Float64(2.75), Pointer(
            to=seenbitmap_tiling,
        ),
        Pointer(to=beforebitmap_tiling), Pointer(to=afterbitmap_tiling))
    checks.check("bitmap_tiling by value, between an int8 and a double",
        seenbitmap_tiling == givenbitmap_tiling and beforebitmap_tiling == -5 and afterbitmap_tiling == 2.75)
    checks.check(
        "bitmap_tiling returned",
        resultbitmap_tiling == bitmap_tiling(4),
    )

    var givenborder_style = border_style(3)
    var seenborder_style = givenborder_style
    var beforeborder_style = Int8(0)
    var afterborder_style = Float64(0)
    var resultborder_style = external_call["mojobe_oracle_echo_border_style", border_style](
        Int8(-5), givenborder_style, Float64(2.75), Pointer(
            to=seenborder_style,
        ),
        Pointer(to=beforeborder_style), Pointer(to=afterborder_style))
    checks.check("border_style by value, between an int8 and a double",
        seenborder_style == givenborder_style and beforeborder_style == -5 and afterborder_style == 2.75)
    checks.check("border_style returned", resultborder_style == border_style(4))

    var givenbuffer_layout = buffer_layout(3)
    var seenbuffer_layout = givenbuffer_layout
    var beforebuffer_layout = Int8(0)
    var afterbuffer_layout = Float64(0)
    var resultbuffer_layout = external_call["mojobe_oracle_echo_buffer_layout", buffer_layout](
        Int8(-5), givenbuffer_layout, Float64(2.75), Pointer(
            to=seenbuffer_layout,
        ),
        Pointer(to=beforebuffer_layout), Pointer(to=afterbuffer_layout))
    checks.check("buffer_layout by value, between an int8 and a double",
        seenbuffer_layout == givenbuffer_layout and beforebuffer_layout == -5 and afterbuffer_layout == 2.75)
    checks.check(
        "buffer_layout returned",
        resultbuffer_layout == buffer_layout(4),
    )

    var givenbuffer_orientation = buffer_orientation(3)
    var seenbuffer_orientation = givenbuffer_orientation
    var beforebuffer_orientation = Int8(0)
    var afterbuffer_orientation = Float64(0)
    var resultbuffer_orientation = external_call["mojobe_oracle_echo_buffer_orientation", buffer_orientation](
        Int8(-5), givenbuffer_orientation, Float64(2.75), Pointer(
            to=seenbuffer_orientation,
        ),
        Pointer(to=beforebuffer_orientation), Pointer(
            to=afterbuffer_orientation,
        ))
    checks.check("buffer_orientation by value, between an int8 and a double",
        seenbuffer_orientation == givenbuffer_orientation and beforebuffer_orientation == -5 and afterbuffer_orientation == 2.75)
    checks.check(
        "buffer_orientation returned",
        resultbuffer_orientation == buffer_orientation(4),
    )

    var givenbutton_width = button_width(3)
    var seenbutton_width = givenbutton_width
    var beforebutton_width = Int8(0)
    var afterbutton_width = Float64(0)
    var resultbutton_width = external_call["mojobe_oracle_echo_button_width", button_width](
        Int8(-5), givenbutton_width, Float64(2.75), Pointer(
            to=seenbutton_width,
        ),
        Pointer(to=beforebutton_width), Pointer(to=afterbutton_width))
    checks.check("button_width by value, between an int8 and a double",
        seenbutton_width == givenbutton_width and beforebutton_width == -5 and afterbutton_width == 2.75)
    checks.check("button_width returned", resultbutton_width == button_width(4))

    var givencap_mode = cap_mode(3)
    var seencap_mode = givencap_mode
    var beforecap_mode = Int8(0)
    var aftercap_mode = Float64(0)
    var resultcap_mode = external_call["mojobe_oracle_echo_cap_mode", cap_mode](
        Int8(-5), givencap_mode, Float64(2.75), Pointer(to=seencap_mode),
        Pointer(to=beforecap_mode), Pointer(to=aftercap_mode))
    checks.check("cap_mode by value, between an int8 and a double",
        seencap_mode == givencap_mode and beforecap_mode == -5 and aftercap_mode == 2.75)
    checks.check("cap_mode returned", resultcap_mode == cap_mode(4))

    var givencolor_which = color_which(3)
    var seencolor_which = givencolor_which
    var beforecolor_which = Int8(0)
    var aftercolor_which = Float64(0)
    var resultcolor_which = external_call["mojobe_oracle_echo_color_which", color_which](
        Int8(-5), givencolor_which, Float64(2.75), Pointer(to=seencolor_which),
        Pointer(to=beforecolor_which), Pointer(to=aftercolor_which))
    checks.check("color_which by value, between an int8 and a double",
        seencolor_which == givencolor_which and beforecolor_which == -5 and aftercolor_which == 2.75)
    checks.check("color_which returned", resultcolor_which == color_which(4))

    var givencommand_code = command_code(3)
    var seencommand_code = givencommand_code
    var beforecommand_code = Int8(0)
    var aftercommand_code = Float64(0)
    var resultcommand_code = external_call["mojobe_oracle_echo_command_code", command_code](
        Int8(-5), givencommand_code, Float64(2.75), Pointer(
            to=seencommand_code,
        ),
        Pointer(to=beforecommand_code), Pointer(to=aftercommand_code))
    checks.check("command_code by value, between an int8 and a double",
        seencommand_code == givencommand_code and beforecommand_code == -5 and aftercommand_code == 2.75)
    checks.check("command_code returned", resultcommand_code == command_code(4))

    var givencpu_platform = cpu_platform(3)
    var seencpu_platform = givencpu_platform
    var beforecpu_platform = Int8(0)
    var aftercpu_platform = Float64(0)
    var resultcpu_platform = external_call["mojobe_oracle_echo_cpu_platform", cpu_platform](
        Int8(-5), givencpu_platform, Float64(2.75), Pointer(
            to=seencpu_platform,
        ),
        Pointer(to=beforecpu_platform), Pointer(to=aftercpu_platform))
    checks.check("cpu_platform by value, between an int8 and a double",
        seencpu_platform == givencpu_platform and beforecpu_platform == -5 and aftercpu_platform == 2.75)
    checks.check("cpu_platform returned", resultcpu_platform == cpu_platform(4))

    var givencpu_vendor = cpu_vendor(3)
    var seencpu_vendor = givencpu_vendor
    var beforecpu_vendor = Int8(0)
    var aftercpu_vendor = Float64(0)
    var resultcpu_vendor = external_call["mojobe_oracle_echo_cpu_vendor", cpu_vendor](
        Int8(-5), givencpu_vendor, Float64(2.75), Pointer(to=seencpu_vendor),
        Pointer(to=beforecpu_vendor), Pointer(to=aftercpu_vendor))
    checks.check("cpu_vendor by value, between an int8 and a double",
        seencpu_vendor == givencpu_vendor and beforecpu_vendor == -5 and aftercpu_vendor == 2.75)
    checks.check("cpu_vendor returned", resultcpu_vendor == cpu_vendor(4))

    var givendrawing_mode = drawing_mode(3)
    var seendrawing_mode = givendrawing_mode
    var beforedrawing_mode = Int8(0)
    var afterdrawing_mode = Float64(0)
    var resultdrawing_mode = external_call["mojobe_oracle_echo_drawing_mode", drawing_mode](
        Int8(-5), givendrawing_mode, Float64(2.75), Pointer(
            to=seendrawing_mode,
        ),
        Pointer(to=beforedrawing_mode), Pointer(to=afterdrawing_mode))
    checks.check("drawing_mode by value, between an int8 and a double",
        seendrawing_mode == givendrawing_mode and beforedrawing_mode == -5 and afterdrawing_mode == 2.75)
    checks.check("drawing_mode returned", resultdrawing_mode == drawing_mode(4))

    var givenfont_direction = font_direction(3)
    var seenfont_direction = givenfont_direction
    var beforefont_direction = Int8(0)
    var afterfont_direction = Float64(0)
    var resultfont_direction = external_call["mojobe_oracle_echo_font_direction", font_direction](
        Int8(-5), givenfont_direction, Float64(2.75), Pointer(
            to=seenfont_direction,
        ),
        Pointer(to=beforefont_direction), Pointer(to=afterfont_direction))
    checks.check("font_direction by value, between an int8 and a double",
        seenfont_direction == givenfont_direction and beforefont_direction == -5 and afterfont_direction == 2.75)
    checks.check(
        "font_direction returned",
        resultfont_direction == font_direction(4),
    )

    var givenfont_file_format = font_file_format(3)
    var seenfont_file_format = givenfont_file_format
    var beforefont_file_format = Int8(0)
    var afterfont_file_format = Float64(0)
    var resultfont_file_format = external_call["mojobe_oracle_echo_font_file_format", font_file_format](
        Int8(-5), givenfont_file_format, Float64(2.75), Pointer(
            to=seenfont_file_format,
        ),
        Pointer(to=beforefont_file_format), Pointer(to=afterfont_file_format))
    checks.check("font_file_format by value, between an int8 and a double",
        seenfont_file_format == givenfont_file_format and beforefont_file_format == -5 and afterfont_file_format == 2.75)
    checks.check(
        "font_file_format returned",
        resultfont_file_format == font_file_format(4),
    )

    var givenfont_metric_mode = font_metric_mode(3)
    var seenfont_metric_mode = givenfont_metric_mode
    var beforefont_metric_mode = Int8(0)
    var afterfont_metric_mode = Float64(0)
    var resultfont_metric_mode = external_call["mojobe_oracle_echo_font_metric_mode", font_metric_mode](
        Int8(-5), givenfont_metric_mode, Float64(2.75), Pointer(
            to=seenfont_metric_mode,
        ),
        Pointer(to=beforefont_metric_mode), Pointer(to=afterfont_metric_mode))
    checks.check("font_metric_mode by value, between an int8 and a double",
        seenfont_metric_mode == givenfont_metric_mode and beforefont_metric_mode == -5 and afterfont_metric_mode == 2.75)
    checks.check(
        "font_metric_mode returned",
        resultfont_metric_mode == font_metric_mode(4),
    )

    var givenjoin_mode = join_mode(3)
    var seenjoin_mode = givenjoin_mode
    var beforejoin_mode = Int8(0)
    var afterjoin_mode = Float64(0)
    var resultjoin_mode = external_call["mojobe_oracle_echo_join_mode", join_mode](
        Int8(-5), givenjoin_mode, Float64(2.75), Pointer(to=seenjoin_mode),
        Pointer(to=beforejoin_mode), Pointer(to=afterjoin_mode))
    checks.check("join_mode by value, between an int8 and a double",
        seenjoin_mode == givenjoin_mode and beforejoin_mode == -5 and afterjoin_mode == 2.75)
    checks.check("join_mode returned", resultjoin_mode == join_mode(4))

    var givenmenu_bar_border = menu_bar_border(3)
    var seenmenu_bar_border = givenmenu_bar_border
    var beforemenu_bar_border = Int8(0)
    var aftermenu_bar_border = Float64(0)
    var resultmenu_bar_border = external_call["mojobe_oracle_echo_menu_bar_border", menu_bar_border](
        Int8(-5), givenmenu_bar_border, Float64(2.75), Pointer(
            to=seenmenu_bar_border,
        ),
        Pointer(to=beforemenu_bar_border), Pointer(to=aftermenu_bar_border))
    checks.check("menu_bar_border by value, between an int8 and a double",
        seenmenu_bar_border == givenmenu_bar_border and beforemenu_bar_border == -5 and aftermenu_bar_border == 2.75)
    checks.check(
        "menu_bar_border returned",
        resultmenu_bar_border == menu_bar_border(4),
    )

    var givenmenu_layout = menu_layout(3)
    var seenmenu_layout = givenmenu_layout
    var beforemenu_layout = Int8(0)
    var aftermenu_layout = Float64(0)
    var resultmenu_layout = external_call["mojobe_oracle_echo_menu_layout", menu_layout](
        Int8(-5), givenmenu_layout, Float64(2.75), Pointer(to=seenmenu_layout),
        Pointer(to=beforemenu_layout), Pointer(to=aftermenu_layout))
    checks.check("menu_layout by value, between an int8 and a double",
        seenmenu_layout == givenmenu_layout and beforemenu_layout == -5 and aftermenu_layout == 2.75)
    checks.check("menu_layout returned", resultmenu_layout == menu_layout(4))

    var givenmode_focus_follows_mouse = mode_focus_follows_mouse(3)
    var seenmode_focus_follows_mouse = givenmode_focus_follows_mouse
    var beforemode_focus_follows_mouse = Int8(0)
    var aftermode_focus_follows_mouse = Float64(0)
    var resultmode_focus_follows_mouse = external_call["mojobe_oracle_echo_mode_focus_follows_mouse", mode_focus_follows_mouse](
        Int8(-5), givenmode_focus_follows_mouse, Float64(2.75), Pointer(
            to=seenmode_focus_follows_mouse,
        ),
        Pointer(to=beforemode_focus_follows_mouse), Pointer(
            to=aftermode_focus_follows_mouse,
        ))
    checks.check("mode_focus_follows_mouse by value, between an int8 and a double",
        seenmode_focus_follows_mouse == givenmode_focus_follows_mouse and beforemode_focus_follows_mouse == -5 and aftermode_focus_follows_mouse == 2.75)
    checks.check(
        "mode_focus_follows_mouse returned",
        resultmode_focus_follows_mouse == mode_focus_follows_mouse(4),
    )

    var givenmode_mouse = mode_mouse(-3)
    var seenmode_mouse = givenmode_mouse
    var beforemode_mouse = Int8(0)
    var aftermode_mouse = Float64(0)
    var resultmode_mouse = external_call["mojobe_oracle_echo_mode_mouse", mode_mouse](
        Int8(-5), givenmode_mouse, Float64(2.75), Pointer(to=seenmode_mouse),
        Pointer(to=beforemode_mouse), Pointer(to=aftermode_mouse))
    checks.check("mode_mouse by value, between an int8 and a double",
        seenmode_mouse == givenmode_mouse and beforemode_mouse == -5 and aftermode_mouse == 2.75)
    checks.check("mode_mouse returned", resultmode_mouse == mode_mouse(-2))

    var givenorientation = orientation(3)
    var seenorientation = givenorientation
    var beforeorientation = Int8(0)
    var afterorientation = Float64(0)
    var resultorientation = external_call["mojobe_oracle_echo_orientation", orientation](
        Int8(-5), givenorientation, Float64(2.75), Pointer(to=seenorientation),
        Pointer(to=beforeorientation), Pointer(to=afterorientation))
    checks.check("orientation by value, between an int8 and a double",
        seenorientation == givenorientation and beforeorientation == -5 and afterorientation == 2.75)
    checks.check("orientation returned", resultorientation == orientation(4))

    var givenoverlay_options = overlay_options(3)
    var seenoverlay_options = givenoverlay_options
    var beforeoverlay_options = Int8(0)
    var afteroverlay_options = Float64(0)
    var resultoverlay_options = external_call["mojobe_oracle_echo_overlay_options", overlay_options](
        Int8(-5), givenoverlay_options, Float64(2.75), Pointer(
            to=seenoverlay_options,
        ),
        Pointer(to=beforeoverlay_options), Pointer(to=afteroverlay_options))
    checks.check("overlay_options by value, between an int8 and a double",
        seenoverlay_options == givenoverlay_options and beforeoverlay_options == -5 and afteroverlay_options == 2.75)
    checks.check(
        "overlay_options returned",
        resultoverlay_options == overlay_options(4),
    )

    var givenrect_tracking_style = rect_tracking_style(3)
    var seenrect_tracking_style = givenrect_tracking_style
    var beforerect_tracking_style = Int8(0)
    var afterrect_tracking_style = Float64(0)
    var resultrect_tracking_style = external_call["mojobe_oracle_echo_rect_tracking_style", rect_tracking_style](
        Int8(-5), givenrect_tracking_style, Float64(2.75), Pointer(
            to=seenrect_tracking_style,
        ),
        Pointer(to=beforerect_tracking_style), Pointer(
            to=afterrect_tracking_style,
        ))
    checks.check("rect_tracking_style by value, between an int8 and a double",
        seenrect_tracking_style == givenrect_tracking_style and beforerect_tracking_style == -5 and afterrect_tracking_style == 2.75)
    checks.check(
        "rect_tracking_style returned",
        resultrect_tracking_style == rect_tracking_style(4),
    )

    var givenset_font_mask = set_font_mask(3)
    var seenset_font_mask = givenset_font_mask
    var beforeset_font_mask = Int8(0)
    var afterset_font_mask = Float64(0)
    var resultset_font_mask = external_call["mojobe_oracle_echo_set_font_mask", set_font_mask](
        Int8(-5), givenset_font_mask, Float64(2.75), Pointer(
            to=seenset_font_mask,
        ),
        Pointer(to=beforeset_font_mask), Pointer(to=afterset_font_mask))
    checks.check("set_font_mask by value, between an int8 and a double",
        seenset_font_mask == givenset_font_mask and beforeset_font_mask == -5 and afterset_font_mask == 2.75)
    checks.check(
        "set_font_mask returned",
        resultset_font_mask == set_font_mask(4),
    )

    var givensource_alpha = source_alpha(3)
    var seensource_alpha = givensource_alpha
    var beforesource_alpha = Int8(0)
    var aftersource_alpha = Float64(0)
    var resultsource_alpha = external_call["mojobe_oracle_echo_source_alpha", source_alpha](
        Int8(-5), givensource_alpha, Float64(2.75), Pointer(
            to=seensource_alpha,
        ),
        Pointer(to=beforesource_alpha), Pointer(to=aftersource_alpha))
    checks.check("source_alpha by value, between an int8 and a double",
        seensource_alpha == givensource_alpha and beforesource_alpha == -5 and aftersource_alpha == 2.75)
    checks.check("source_alpha returned", resultsource_alpha == source_alpha(4))

    var giventopology_level_type = topology_level_type(3)
    var seentopology_level_type = giventopology_level_type
    var beforetopology_level_type = Int8(0)
    var aftertopology_level_type = Float64(0)
    var resulttopology_level_type = external_call["mojobe_oracle_echo_topology_level_type", topology_level_type](
        Int8(-5), giventopology_level_type, Float64(2.75), Pointer(
            to=seentopology_level_type,
        ),
        Pointer(to=beforetopology_level_type), Pointer(
            to=aftertopology_level_type,
        ))
    checks.check("topology_level_type by value, between an int8 and a double",
        seentopology_level_type == giventopology_level_type and beforetopology_level_type == -5 and aftertopology_level_type == 2.75)
    checks.check(
        "topology_level_type returned",
        resulttopology_level_type == topology_level_type(4),
    )

    var givenvertical_alignment = vertical_alignment(-3)
    var seenvertical_alignment = givenvertical_alignment
    var beforevertical_alignment = Int8(0)
    var aftervertical_alignment = Float64(0)
    var resultvertical_alignment = external_call["mojobe_oracle_echo_vertical_alignment", vertical_alignment](
        Int8(-5), givenvertical_alignment, Float64(2.75), Pointer(
            to=seenvertical_alignment,
        ),
        Pointer(to=beforevertical_alignment), Pointer(
            to=aftervertical_alignment,
        ))
    checks.check("vertical_alignment by value, between an int8 and a double",
        seenvertical_alignment == givenvertical_alignment and beforevertical_alignment == -5 and aftervertical_alignment == 2.75)
    checks.check(
        "vertical_alignment returned",
        resultvertical_alignment == vertical_alignment(-2),
    )

    var givenwindow_alignment = window_alignment(3)
    var seenwindow_alignment = givenwindow_alignment
    var beforewindow_alignment = Int8(0)
    var afterwindow_alignment = Float64(0)
    var resultwindow_alignment = external_call["mojobe_oracle_echo_window_alignment", window_alignment](
        Int8(-5), givenwindow_alignment, Float64(2.75), Pointer(
            to=seenwindow_alignment,
        ),
        Pointer(to=beforewindow_alignment), Pointer(to=afterwindow_alignment))
    checks.check("window_alignment by value, between an int8 and a double",
        seenwindow_alignment == givenwindow_alignment and beforewindow_alignment == -5 and afterwindow_alignment == 2.75)
    checks.check(
        "window_alignment returned",
        resultwindow_alignment == window_alignment(4),
    )

    var givenwindow_feel = window_feel(3)
    var seenwindow_feel = givenwindow_feel
    var beforewindow_feel = Int8(0)
    var afterwindow_feel = Float64(0)
    var resultwindow_feel = external_call["mojobe_oracle_echo_window_feel", window_feel](
        Int8(-5), givenwindow_feel, Float64(2.75), Pointer(to=seenwindow_feel),
        Pointer(to=beforewindow_feel), Pointer(to=afterwindow_feel))
    checks.check("window_feel by value, between an int8 and a double",
        seenwindow_feel == givenwindow_feel and beforewindow_feel == -5 and afterwindow_feel == 2.75)
    checks.check("window_feel returned", resultwindow_feel == window_feel(4))

    var givenwindow_look = window_look(3)
    var seenwindow_look = givenwindow_look
    var beforewindow_look = Int8(0)
    var afterwindow_look = Float64(0)
    var resultwindow_look = external_call["mojobe_oracle_echo_window_look", window_look](
        Int8(-5), givenwindow_look, Float64(2.75), Pointer(to=seenwindow_look),
        Pointer(to=beforewindow_look), Pointer(to=afterwindow_look))
    checks.check("window_look by value, between an int8 and a double",
        seenwindow_look == givenwindow_look and beforewindow_look == -5 and afterwindow_look == 2.75)
    checks.check("window_look returned", resultwindow_look == window_look(4))

    var givenwindow_type = window_type(3)
    var seenwindow_type = givenwindow_type
    var beforewindow_type = Int8(0)
    var afterwindow_type = Float64(0)
    var resultwindow_type = external_call["mojobe_oracle_echo_window_type", window_type](
        Int8(-5), givenwindow_type, Float64(2.75), Pointer(to=seenwindow_type),
        Pointer(to=beforewindow_type), Pointer(to=afterwindow_type))
    checks.check("window_type by value, between an int8 and a double",
        seenwindow_type == givenwindow_type and beforewindow_type == -5 and afterwindow_type == 2.75)
    checks.check("window_type returned", resultwindow_type == window_type(4))

    var stack = external_call["mojobe_oracle_stack", Float64](
        Int32(1), Int32(2), Int32(3), Int32(4), Int32(5), Int32(6), Int32(7), Int32(8), Int32(9), Int32(
            10,
        ), Int32(11), Int32(12),
        Float32(0.25), Float32(1.25), Float32(2.25), Float32(3.25), Float32(
            4.25,
        ), Float32(5.25), Float32(6.25), Float32(7.25), Float32(8.25), Float32(9.25),
        True, Int8(-7), UInt16(65000), Int64(-123456789),
        UInt64(987654321), Float64(0.125))
    checks.check(
        "30 arguments, most of them on the stack",
        stack == 10000326810.5,
    )

    var total = checks.passed + checks.failed
    if checks.failed:
        print("SELFTEST FAIL", checks.passed, "/", total)
    else:
        print("SELFTEST PASS", String(checks.passed) + "/" + String(total))
