# ===----------------------------------------------------------------------=== #
# Copyright (c) 2026, MojoProse. All rights reserved.
#
# Licensed under the Apache License v2.0 with LLVM Exceptions:
# https://llvm.org/LICENSE.txt
#
# Generated by Haiku/generator/mojobe_gen.py from the Haiku headers and
# bridge.toml. Do not edit: change the generator or its annotations.
# ===----------------------------------------------------------------------=== #
"""The Haiku headers' constants, as clang evaluates them for the Haiku
target. A named enum is a type of its own, so that a `window_type` is
not taken for a `window_look`; the rest are integers."""


@fieldwise_init
struct BSpacing(Equatable, TrivialRegisterPassable):
    """`enum BSpacing`."""

    var value: Int32

    def __or__(self, other: Self) -> Self:
        return Self(self.value | other.value)


@fieldwise_init
struct alert_type(Equatable, TrivialRegisterPassable):
    """`enum alert_type`."""

    var value: UInt32

    def __or__(self, other: Self) -> Self:
        return Self(self.value | other.value)


@fieldwise_init
struct alignment(Equatable, TrivialRegisterPassable):
    """`enum alignment`."""

    var value: Int32

    def __or__(self, other: Self) -> Self:
        return Self(self.value | other.value)


@fieldwise_init
struct alpha_function(Equatable, TrivialRegisterPassable):
    """`enum alpha_function`."""

    var value: UInt32

    def __or__(self, other: Self) -> Self:
        return Self(self.value | other.value)


@fieldwise_init
struct bitmap_drawing_options(Equatable, TrivialRegisterPassable):
    """`enum bitmap_drawing_options`."""

    var value: UInt32

    def __or__(self, other: Self) -> Self:
        return Self(self.value | other.value)


@fieldwise_init
struct bitmap_tiling(Equatable, TrivialRegisterPassable):
    """`enum bitmap_tiling`."""

    var value: UInt32

    def __or__(self, other: Self) -> Self:
        return Self(self.value | other.value)


@fieldwise_init
struct border_style(Equatable, TrivialRegisterPassable):
    """`enum border_style`."""

    var value: UInt32

    def __or__(self, other: Self) -> Self:
        return Self(self.value | other.value)


@fieldwise_init
struct buffer_layout(Equatable, TrivialRegisterPassable):
    """`enum buffer_layout`."""

    var value: UInt32

    def __or__(self, other: Self) -> Self:
        return Self(self.value | other.value)


@fieldwise_init
struct buffer_orientation(Equatable, TrivialRegisterPassable):
    """`enum buffer_orientation`."""

    var value: UInt32

    def __or__(self, other: Self) -> Self:
        return Self(self.value | other.value)


@fieldwise_init
struct button_spacing(Equatable, TrivialRegisterPassable):
    """`enum button_spacing`."""

    var value: UInt32

    def __or__(self, other: Self) -> Self:
        return Self(self.value | other.value)


@fieldwise_init
struct button_width(Equatable, TrivialRegisterPassable):
    """`enum button_width`."""

    var value: UInt32

    def __or__(self, other: Self) -> Self:
        return Self(self.value | other.value)


@fieldwise_init
struct cap_mode(Equatable, TrivialRegisterPassable):
    """`enum cap_mode`."""

    var value: UInt32

    def __or__(self, other: Self) -> Self:
        return Self(self.value | other.value)


@fieldwise_init
struct color_space(Equatable, TrivialRegisterPassable):
    """`enum color_space`."""

    var value: UInt32

    def __or__(self, other: Self) -> Self:
        return Self(self.value | other.value)


@fieldwise_init
struct color_which(Equatable, TrivialRegisterPassable):
    """`enum color_which`."""

    var value: UInt32

    def __or__(self, other: Self) -> Self:
        return Self(self.value | other.value)


@fieldwise_init
struct command_code(Equatable, TrivialRegisterPassable):
    """`enum command_code`."""

    var value: UInt32

    def __or__(self, other: Self) -> Self:
        return Self(self.value | other.value)


@fieldwise_init
struct coordinate_space(Equatable, TrivialRegisterPassable):
    """`enum coordinate_space`."""

    var value: UInt32

    def __or__(self, other: Self) -> Self:
        return Self(self.value | other.value)


@fieldwise_init
struct cpu_platform(Equatable, TrivialRegisterPassable):
    """`enum cpu_platform`."""

    var value: UInt32

    def __or__(self, other: Self) -> Self:
        return Self(self.value | other.value)


@fieldwise_init
struct cpu_vendor(Equatable, TrivialRegisterPassable):
    """`enum cpu_vendor`."""

    var value: UInt32

    def __or__(self, other: Self) -> Self:
        return Self(self.value | other.value)


@fieldwise_init
struct direct_buffer_state(Equatable, TrivialRegisterPassable):
    """`enum direct_buffer_state`."""

    var value: UInt32

    def __or__(self, other: Self) -> Self:
        return Self(self.value | other.value)


@fieldwise_init
struct direct_driver_state(Equatable, TrivialRegisterPassable):
    """`enum direct_driver_state`."""

    var value: UInt32

    def __or__(self, other: Self) -> Self:
        return Self(self.value | other.value)


@fieldwise_init
struct directory_which(Equatable, TrivialRegisterPassable):
    """`enum directory_which`."""

    var value: UInt32

    def __or__(self, other: Self) -> Self:
        return Self(self.value | other.value)


@fieldwise_init
struct drawing_mode(Equatable, TrivialRegisterPassable):
    """`enum drawing_mode`."""

    var value: UInt32

    def __or__(self, other: Self) -> Self:
        return Self(self.value | other.value)


@fieldwise_init
struct file_panel_button(Equatable, TrivialRegisterPassable):
    """`enum file_panel_button`."""

    var value: UInt32

    def __or__(self, other: Self) -> Self:
        return Self(self.value | other.value)


@fieldwise_init
struct file_panel_mode(Equatable, TrivialRegisterPassable):
    """`enum file_panel_mode`."""

    var value: UInt32

    def __or__(self, other: Self) -> Self:
        return Self(self.value | other.value)


@fieldwise_init
struct font_direction(Equatable, TrivialRegisterPassable):
    """`enum font_direction`."""

    var value: UInt32

    def __or__(self, other: Self) -> Self:
        return Self(self.value | other.value)


@fieldwise_init
struct font_file_format(Equatable, TrivialRegisterPassable):
    """`enum font_file_format`."""

    var value: UInt32

    def __or__(self, other: Self) -> Self:
        return Self(self.value | other.value)


@fieldwise_init
struct font_metric_mode(Equatable, TrivialRegisterPassable):
    """`enum font_metric_mode`."""

    var value: UInt32

    def __or__(self, other: Self) -> Self:
        return Self(self.value | other.value)


@fieldwise_init
struct game_blit_op(Equatable, TrivialRegisterPassable):
    """`enum game_blit_op`."""

    var value: UInt32

    def __or__(self, other: Self) -> Self:
        return Self(self.value | other.value)


@fieldwise_init
struct game_pane_effect(Equatable, TrivialRegisterPassable):
    """`enum game_pane_effect`."""

    var value: UInt32

    def __or__(self, other: Self) -> Self:
        return Self(self.value | other.value)


@fieldwise_init
struct game_pane_plane(Equatable, TrivialRegisterPassable):
    """`enum game_pane_plane`."""

    var value: UInt32

    def __or__(self, other: Self) -> Self:
        return Self(self.value | other.value)


@fieldwise_init
struct hash_mark_location(Equatable, TrivialRegisterPassable):
    """`enum hash_mark_location`."""

    var value: UInt32

    def __or__(self, other: Self) -> Self:
        return Self(self.value | other.value)


@fieldwise_init
struct image_type(Equatable, TrivialRegisterPassable):
    """`enum image_type`."""

    var value: UInt32

    def __or__(self, other: Self) -> Self:
        return Self(self.value | other.value)


@fieldwise_init
struct join_mode(Equatable, TrivialRegisterPassable):
    """`enum join_mode`."""

    var value: UInt32

    def __or__(self, other: Self) -> Self:
        return Self(self.value | other.value)


@fieldwise_init
struct menu_bar_border(Equatable, TrivialRegisterPassable):
    """`enum menu_bar_border`."""

    var value: UInt32

    def __or__(self, other: Self) -> Self:
        return Self(self.value | other.value)


@fieldwise_init
struct menu_layout(Equatable, TrivialRegisterPassable):
    """`enum menu_layout`."""

    var value: UInt32

    def __or__(self, other: Self) -> Self:
        return Self(self.value | other.value)


@fieldwise_init
struct mode_focus_follows_mouse(Equatable, TrivialRegisterPassable):
    """`enum mode_focus_follows_mouse`."""

    var value: UInt32

    def __or__(self, other: Self) -> Self:
        return Self(self.value | other.value)


@fieldwise_init
struct mode_mouse(Equatable, TrivialRegisterPassable):
    """`enum mode_mouse`."""

    var value: Int32

    def __or__(self, other: Self) -> Self:
        return Self(self.value | other.value)


@fieldwise_init
struct node_flavor(Equatable, TrivialRegisterPassable):
    """`enum node_flavor`."""

    var value: UInt32

    def __or__(self, other: Self) -> Self:
        return Self(self.value | other.value)


@fieldwise_init
struct orientation(Equatable, TrivialRegisterPassable):
    """`enum orientation`."""

    var value: UInt32

    def __or__(self, other: Self) -> Self:
        return Self(self.value | other.value)


@fieldwise_init
struct overlay_options(Equatable, TrivialRegisterPassable):
    """`enum overlay_options`."""

    var value: UInt32

    def __or__(self, other: Self) -> Self:
        return Self(self.value | other.value)


@fieldwise_init
struct path_base_directory(Equatable, TrivialRegisterPassable):
    """`enum path_base_directory`."""

    var value: UInt32

    def __or__(self, other: Self) -> Self:
        return Self(self.value | other.value)


@fieldwise_init
struct rect_tracking_style(Equatable, TrivialRegisterPassable):
    """`enum rect_tracking_style`."""

    var value: UInt32

    def __or__(self, other: Self) -> Self:
        return Self(self.value | other.value)


@fieldwise_init
struct set_font_mask(Equatable, TrivialRegisterPassable):
    """`enum set_font_mask`."""

    var value: UInt32

    def __or__(self, other: Self) -> Self:
        return Self(self.value | other.value)


@fieldwise_init
struct source_alpha(Equatable, TrivialRegisterPassable):
    """`enum source_alpha`."""

    var value: UInt32

    def __or__(self, other: Self) -> Self:
        return Self(self.value | other.value)


@fieldwise_init
struct swap_action(Equatable, TrivialRegisterPassable):
    """`enum swap_action`."""

    var value: UInt32

    def __or__(self, other: Self) -> Self:
        return Self(self.value | other.value)


@fieldwise_init
struct thread_state(Equatable, TrivialRegisterPassable):
    """`enum thread_state`."""

    var value: UInt32

    def __or__(self, other: Self) -> Self:
        return Self(self.value | other.value)


@fieldwise_init
struct thumb_style(Equatable, TrivialRegisterPassable):
    """`enum thumb_style`."""

    var value: UInt32

    def __or__(self, other: Self) -> Self:
        return Self(self.value | other.value)


@fieldwise_init
struct topology_level_type(Equatable, TrivialRegisterPassable):
    """`enum topology_level_type`."""

    var value: UInt32

    def __or__(self, other: Self) -> Self:
        return Self(self.value | other.value)


@fieldwise_init
struct undo_state(Equatable, TrivialRegisterPassable):
    """`enum undo_state`."""

    var value: UInt32

    def __or__(self, other: Self) -> Self:
        return Self(self.value | other.value)


@fieldwise_init
struct vertical_alignment(Equatable, TrivialRegisterPassable):
    """`enum vertical_alignment`."""

    var value: Int32

    def __or__(self, other: Self) -> Self:
        return Self(self.value | other.value)


@fieldwise_init
struct window_alignment(Equatable, TrivialRegisterPassable):
    """`enum window_alignment`."""

    var value: UInt32

    def __or__(self, other: Self) -> Self:
        return Self(self.value | other.value)


@fieldwise_init
struct window_feel(Equatable, TrivialRegisterPassable):
    """`enum window_feel`."""

    var value: UInt32

    def __or__(self, other: Self) -> Self:
        return Self(self.value | other.value)


@fieldwise_init
struct window_look(Equatable, TrivialRegisterPassable):
    """`enum window_look`."""

    var value: UInt32

    def __or__(self, other: Self) -> Self:
        return Self(self.value | other.value)


@fieldwise_init
struct window_type(Equatable, TrivialRegisterPassable):
    """`enum window_type`."""

    var value: UInt32

    def __or__(self, other: Self) -> Self:
        return Self(self.value | other.value)


comptime B_15_BIT_1024x768: UInt32 = 0x100000
comptime B_15_BIT_1152x900: UInt32 = 0x800000
comptime B_15_BIT_1280x1024: UInt32 = 0x200000
comptime B_15_BIT_1600x1200: UInt32 = 0x400000
comptime B_15_BIT_640x480: UInt32 = 0x40000
comptime B_15_BIT_800x600: UInt32 = 0x80000
comptime B_16_BIT_1024x768: UInt32 = 0x80
comptime B_16_BIT_1152x900: UInt32 = 0x10000
comptime B_16_BIT_1280x1024: UInt32 = 0x100
comptime B_16_BIT_1600x1200: UInt32 = 0x200
comptime B_16_BIT_640x480: UInt32 = 0x20
comptime B_16_BIT_800x600: UInt32 = 0x40
comptime B_32_BIT_1024x768: UInt32 = 0x1000
comptime B_32_BIT_1152x900: UInt32 = 0x20000
comptime B_32_BIT_1280x1024: UInt32 = 0x2000
comptime B_32_BIT_1600x1200: UInt32 = 0x4000
comptime B_32_BIT_640x480: UInt32 = 0x400
comptime B_32_BIT_800x600: UInt32 = 0x800
comptime B_32_BIT_CONTIGUOUS: Int32 = 6
comptime B_32_BIT_FULL_LOCK: Int32 = 5
comptime B_8_BIT_1024x768: UInt32 = 4
comptime B_8_BIT_1152x900: UInt32 = 0x8000
comptime B_8_BIT_1280x1024: UInt32 = 8
comptime B_8_BIT_1600x1200: UInt32 = 0x10
comptime B_8_BIT_640x400: UInt32 = 0x80000000
comptime B_8_BIT_640x480: UInt32 = 1
comptime B_8_BIT_800x600: UInt32 = 2
comptime B_ABOUT_REQUESTED: UInt32 = 0x5f414252
comptime B_ABSOLUTE_REAL_TIME_TIMEOUT: UInt32 = 0x50
comptime B_ABSOLUTE_TIMEOUT: UInt32 = 0x10
comptime B_ACCELERANT_VERSION: Int32 = 1
comptime B_ACQUIRE_OVERLAY_LOCK: UInt32 = 0x5f414f56
comptime B_ACTIVE_ICON_BITMAP: UInt32 = 1
comptime B_ADD_ON_IMAGE = image_type(3)
comptime B_AFFINE_TRANSFORM_TYPE: UInt32 = 0x414d5458
comptime B_ALIGNMENT_TYPE: UInt32 = 0x414c474e
comptime B_ALIGN_BOTTOM = vertical_alignment(0x30)
comptime B_ALIGN_CENTER = alignment(2)
comptime B_ALIGN_HORIZONTAL_CENTER = alignment(2)
comptime B_ALIGN_HORIZONTAL_UNSET = alignment(-1)
comptime B_ALIGN_LEFT = alignment(0)
comptime B_ALIGN_MIDDLE = vertical_alignment(0x20)
comptime B_ALIGN_NO_VERTICAL = vertical_alignment(-1)
comptime B_ALIGN_RIGHT = alignment(1)
comptime B_ALIGN_TOP = vertical_alignment(0x10)
comptime B_ALIGN_USE_FULL_HEIGHT = vertical_alignment(-2)
comptime B_ALIGN_USE_FULL_WIDTH = alignment(-2)
comptime B_ALIGN_VERTICAL_CENTER = vertical_alignment(0x20)
comptime B_ALIGN_VERTICAL_UNSET = vertical_alignment(-1)
comptime B_ALL_WORKSPACES: UInt32 = 0xffffffff
comptime B_ALPHA_COMPOSITE = alpha_function(1)
comptime B_ALPHA_COMPOSITE_CLEAR = alpha_function(0xa)
comptime B_ALPHA_COMPOSITE_DARKEN = alpha_function(0xd)
comptime B_ALPHA_COMPOSITE_DESTINATION_ATOP = alpha_function(8)
comptime B_ALPHA_COMPOSITE_DESTINATION_IN = alpha_function(6)
comptime B_ALPHA_COMPOSITE_DESTINATION_OUT = alpha_function(7)
comptime B_ALPHA_COMPOSITE_DESTINATION_OVER = alpha_function(5)
comptime B_ALPHA_COMPOSITE_DIFFERENCE = alpha_function(0xb)
comptime B_ALPHA_COMPOSITE_LIGHTEN = alpha_function(0xc)
comptime B_ALPHA_COMPOSITE_SOURCE_ATOP = alpha_function(4)
comptime B_ALPHA_COMPOSITE_SOURCE_IN = alpha_function(2)
comptime B_ALPHA_COMPOSITE_SOURCE_OUT = alpha_function(3)
comptime B_ALPHA_COMPOSITE_SOURCE_OVER = alpha_function(1)
comptime B_ALPHA_COMPOSITE_XOR = alpha_function(9)
comptime B_ALPHA_OVERLAY = alpha_function(0)
comptime B_ALREADY_RUNNING: Int32 = -2147475452
comptime B_AMBIGUOUS_APP_LAUNCH: Int32 = -2147475450
comptime B_ANY_ADDRESS: Int32 = 0
comptime B_ANY_BYTES_PER_ROW: Int32 = -1
comptime B_ANY_KERNEL_ADDRESS: Int32 = 4
comptime B_ANY_NODE = node_flavor(7)
comptime B_ANY_TYPE: UInt32 = 0x414e5954
comptime B_APPS_DIRECTORY = directory_which(0xfa0)
comptime B_APP_ACTIVATED: UInt32 = 0x5f414354
comptime B_APP_ERROR_BASE: Int32 = -2147475456
comptime B_APP_IMAGE = image_type(1)
comptime B_ARCHIVED_OBJECT = command_code(0x41524356)
comptime B_ARGV_RECEIVED: UInt32 = 0x5f415247
comptime B_ASCII_ACKNOWLEDGE: UInt32 = 6
comptime B_ASCII_BELL: UInt32 = 7
comptime B_ASCII_CANCEL: UInt32 = 0x18
comptime B_ASCII_CARRIAGE_RETURN: UInt32 = 0xd
comptime B_ASCII_END_MEDIUM: UInt32 = 0x19
comptime B_ASCII_END_TEXT: UInt32 = 3
comptime B_ASCII_END_TRANSMISSION_BLOCK: UInt32 = 0x17
comptime B_ASCII_NEGATIVE_ACK: UInt32 = 0x15
comptime B_ASCII_NUL: UInt32 = 0
comptime B_ASCII_SHIFT_IN: UInt32 = 0xf
comptime B_ASCII_SHIFT_OUT: UInt32 = 0xe
comptime B_ASCII_START_TEXT: UInt32 = 2
comptime B_ASCII_SYNC_IDLE: UInt32 = 0x16
comptime B_ASCII_TYPE: UInt32 = 0x54455854
comptime B_ASCII_XOFF: UInt32 = 0x13
comptime B_ASCII_XON: UInt32 = 0x11
comptime B_ASYNCHRONOUS_CONTROLS: UInt32 = 0x80000
comptime B_ATOMREF_TYPE: UInt32 = 0x41544d52
comptime B_ATOM_TYPE: UInt32 = 0x41544f4d
comptime B_ATTR_NAME_LENGTH: Int32 = 0xff
comptime B_AUTO_UPDATE_SIZE_LIMITS: UInt32 = 0x400000
comptime B_AVOID_FOCUS: UInt32 = 0x2000
comptime B_AVOID_FRONT: UInt32 = 0x80
comptime B_BACKSPACE: UInt32 = 8
comptime B_BAD_ADDRESS: Int32 = -2147478783
comptime B_BAD_DATA: Int32 = -2147483632
comptime B_BAD_HANDLER: Int32 = -2147475453
comptime B_BAD_IMAGE_ID: Int32 = -2147478784
comptime B_BAD_INDEX: Int32 = -2147483645
comptime B_BAD_MIME_SNIFFER_RULE: Int32 = -2147475441
comptime B_BAD_PORT_ID: Int32 = -2147479040
comptime B_BAD_REPLY: Int32 = -2147475456
comptime B_BAD_SCRIPT_SYNTAX: Int32 = -2147475448
comptime B_BAD_SEM_ID: Int32 = -2147479552
comptime B_BAD_SUBSCRIBER: Int32 = -2147467260
comptime B_BAD_TEAM_ID: Int32 = -2147479293
comptime B_BAD_THREAD_ID: Int32 = -2147479296
comptime B_BAD_THREAD_STATE: Int32 = -2147479294
comptime B_BAD_TYPE: Int32 = -2147483644
comptime B_BAD_VALUE: Int32 = -2147483643
comptime B_BASE_ADDRESS: Int32 = 2
comptime B_BEOS_ADDONS_DIRECTORY = directory_which(0x3ea)
comptime B_BEOS_APPS_DIRECTORY = directory_which(0x3ef)
comptime B_BEOS_BIN_DIRECTORY = directory_which(0x3f0)
comptime B_BEOS_BOOT_DIRECTORY = directory_which(0x3eb)
comptime B_BEOS_DIRECTORY = directory_which(0x3e8)
comptime B_BEOS_DOCUMENTATION_DIRECTORY = directory_which(0x3f2)
comptime B_BEOS_ETC_DIRECTORY = directory_which(0x3f1)
comptime B_BEOS_FONTS_DIRECTORY = directory_which(0x3ec)
comptime B_BEOS_LIB_DIRECTORY = directory_which(0x3ed)
comptime B_BEOS_MEDIA_NODES_DIRECTORY = directory_which(0x3f5)
comptime B_BEOS_PREFERENCES_DIRECTORY = directory_which(0x3f3)
comptime B_BEOS_SERVERS_DIRECTORY = directory_which(0x3ee)
comptime B_BEOS_SOUNDS_DIRECTORY = directory_which(0x3f6)
comptime B_BEOS_SYSTEM_DIRECTORY = directory_which(0x3e9)
comptime B_BEOS_TRANSLATORS_DIRECTORY = directory_which(0x3f4)
comptime B_BEOS_VERSION: Int32 = 0x500
comptime B_BEOS_VERSION_4: Int32 = 0x400
comptime B_BEOS_VERSION_4_5: Int32 = 0x450
comptime B_BEOS_VERSION_5: Int32 = 0x500
comptime B_BEOS_VERSION_MAUI: Int32 = 0x500
comptime B_BEVEL_JOIN = join_mode(2)
comptime B_BIG_RGB_16_BIT = color_space(0x1010)
comptime B_BIG_RGB_32_BIT = color_space(0x1008)
comptime B_BITMAPS_SUPPORT_ATTACHED_VIEWS: UInt32 = 2
comptime B_BITMAPS_SUPPORT_OVERLAY: UInt32 = 4
comptime B_BITMAP_ACCEPTS_VIEWS: UInt32 = 2
comptime B_BITMAP_CLEAR_TO_WHITE: UInt32 = 1
comptime B_BITMAP_IS_AREA: UInt32 = 4
comptime B_BITMAP_IS_CONTIGUOUS: UInt32 = 0x1c
comptime B_BITMAP_IS_LOCKED: UInt32 = 0xc
comptime B_BITMAP_IS_OFFSCREEN: UInt32 = 0x20
comptime B_BITMAP_NO_SERVER_LINK: UInt32 = 0x100
comptime B_BITMAP_RESERVE_OVERLAY_CHANNEL: UInt32 = 0x80
comptime B_BITMAP_SPACING: UInt32 = 2
comptime B_BITMAP_WILL_OVERLAY: UInt32 = 0x60
comptime B_BLOCK_THUMB = thumb_style(0)
comptime B_BOLD_FACE: UInt32 = 0x20
comptime B_BOOL_TYPE: UInt32 = 0x424f4f4c
comptime B_BORDERED_WINDOW = window_type(0x14)
comptime B_BORDERED_WINDOW_LOOK = window_look(0x14)
comptime B_BORDER_CONTENTS = menu_bar_border(1)
comptime B_BORDER_EACH_ITEM = menu_bar_border(2)
comptime B_BORDER_FRAME = menu_bar_border(0)
comptime B_BUFFER_BOTTOM_TO_TOP = buffer_orientation(1)
comptime B_BUFFER_MOVED = direct_buffer_state(0x40)
comptime B_BUFFER_NONINTERLEAVED = buffer_layout(1)
comptime B_BUFFER_NOT_AVAILABLE: Int32 = -2147467258
comptime B_BUFFER_OVERFLOW: Int32 = -2147454935
comptime B_BUFFER_RESET = direct_buffer_state(0x80)
comptime B_BUFFER_RESIZED = direct_buffer_state(0x20)
comptime B_BUFFER_TOP_TO_BOTTOM = buffer_orientation(0)
comptime B_BUSTED_PIPE: Int32 = -2147459059
comptime B_BUSY: Int32 = -2147483634
comptime B_BUTT_CAP = cap_mode(3)
comptime B_BUTT_JOIN = join_mode(3)
comptime B_BYTE_ALIGNMENT = window_alignment(0)
comptime B_CANCEL: UInt32 = 0x5f434e43
comptime B_CANCELED: Int32 = -2147483636
comptime B_CANCEL_BUTTON = file_panel_button(0)
comptime B_CAN_INTERRUPT: UInt32 = 1
comptime B_CAPS_LOCK: UInt32 = 8
comptime B_CAPS_LOCK_KEY: UInt32 = 0x3b
comptime B_CAPS_SHIFT_TABLE: UInt32 = 0x20
comptime B_CAPS_TABLE: UInt32 = 0x40
comptime B_CHAR_SPACING: UInt32 = 0
comptime B_CHAR_TYPE: UInt32 = 0x43484152
comptime B_CHECK_PERMISSION: UInt32 = 4
comptime B_CLICK_TO_FOCUS_MOUSE = mode_mouse(-1)
comptime B_CLIPPING_MODIFIED = direct_buffer_state(0x10)
comptime B_CLONEABLE_AREA: Int32 = 0x100
comptime B_CLONE_ADDRESS: Int32 = 3
comptime B_CLOSE_ON_ESCAPE: UInt32 = 0x800000
comptime B_CLOSE_REQUESTED: UInt32 = 0x5f515251
comptime B_CMAP8 = color_space(4)
comptime B_CMY24 = color_space(0xc001)
comptime B_CMY32 = color_space(0xc002)
comptime B_CMYA32 = color_space(0xe002)
comptime B_CMYK32 = color_space(0xc003)
comptime B_COLORS_UPDATED: UInt32 = 0x5f434c55
comptime B_COLOR_8_BIT = color_space(4)
comptime B_COLOR_8_BIT_TYPE: UInt32 = 0x434c5242
comptime B_COMMAND_KEY: UInt32 = 2
comptime B_CONDENSED_FACE: UInt32 = 0x80
comptime B_CONSTANT_ALPHA = source_alpha(1)
comptime B_CONTIGUOUS: Int32 = 3
comptime B_CONTROL_BACKGROUND_COLOR = color_which(0xd)
comptime B_CONTROL_BORDER_COLOR = color_which(0xf)
comptime B_CONTROL_HIGHLIGHT_COLOR = color_which(0x10)
comptime B_CONTROL_INVOKED = command_code(0x4349564b)
comptime B_CONTROL_KEY: UInt32 = 4
comptime B_CONTROL_MARK_COLOR = color_which(0x1b)
comptime B_CONTROL_MODIFIED = command_code(0x434d4f44)
comptime B_CONTROL_OFF: UInt32 = 0
comptime B_CONTROL_ON: UInt32 = 1
comptime B_CONTROL_PARTIALLY_ON: UInt32 = 2
comptime B_CONTROL_TABLE: UInt32 = 1
comptime B_CONTROL_TEXT_COLOR = color_which(0xe)
comptime B_COPY = command_code(0x434f5059)
comptime B_COPY_TARGET = command_code(0x44444350)
comptime B_COUNT_PROPERTIES = command_code(0x50434e54)
comptime B_CPU_ALPHA = cpu_platform(8)
comptime B_CPU_ARM = cpu_platform(6)
comptime B_CPU_ARM_64 = cpu_platform(7)
comptime B_CPU_M68K = cpu_platform(5)
comptime B_CPU_MIPS = cpu_platform(9)
comptime B_CPU_PPC = cpu_platform(3)
comptime B_CPU_PPC_64 = cpu_platform(4)
comptime B_CPU_RISC_V = cpu_platform(0xc)
comptime B_CPU_SH = cpu_platform(0xa)
comptime B_CPU_SPARC = cpu_platform(0xb)
comptime B_CPU_UNKNOWN = cpu_platform(0)
comptime B_CPU_VENDOR_AMD = cpu_vendor(1)
comptime B_CPU_VENDOR_AMPERE = cpu_vendor(0x1b)
comptime B_CPU_VENDOR_APM = cpu_vendor(0x17)
comptime B_CPU_VENDOR_APPLE = cpu_vendor(0x1a)
comptime B_CPU_VENDOR_ARM = cpu_vendor(0xf)
comptime B_CPU_VENDOR_BROADCOM = cpu_vendor(0x10)
comptime B_CPU_VENDOR_CAVIUM = cpu_vendor(0x11)
comptime B_CPU_VENDOR_CYRIX = cpu_vendor(2)
comptime B_CPU_VENDOR_DEC = cpu_vendor(0x12)
comptime B_CPU_VENDOR_FREESCALE = cpu_vendor(0x15)
comptime B_CPU_VENDOR_FUJITSU = cpu_vendor(0xe)
comptime B_CPU_VENDOR_HISILICON = cpu_vendor(0x13)
comptime B_CPU_VENDOR_HYGON = cpu_vendor(0xc)
comptime B_CPU_VENDOR_IBM = cpu_vendor(9)
comptime B_CPU_VENDOR_IDT = cpu_vendor(3)
comptime B_CPU_VENDOR_INFINEON = cpu_vendor(0x14)
comptime B_CPU_VENDOR_INTEL = cpu_vendor(4)
comptime B_CPU_VENDOR_MARVELL = cpu_vendor(0x19)
comptime B_CPU_VENDOR_MICROSOFT = cpu_vendor(0x1c)
comptime B_CPU_VENDOR_MOTOROLA = cpu_vendor(0xa)
comptime B_CPU_VENDOR_NATIONAL_SEMICONDUCTOR = cpu_vendor(5)
comptime B_CPU_VENDOR_NEC = cpu_vendor(0xb)
comptime B_CPU_VENDOR_NVIDIA = cpu_vendor(0x16)
comptime B_CPU_VENDOR_QUALCOMM = cpu_vendor(0x18)
comptime B_CPU_VENDOR_RISE = cpu_vendor(6)
comptime B_CPU_VENDOR_SUN = cpu_vendor(0xd)
comptime B_CPU_VENDOR_TRANSMETA = cpu_vendor(7)
comptime B_CPU_VENDOR_UNKNOWN = cpu_vendor(0)
comptime B_CPU_VENDOR_VIA = cpu_vendor(8)
comptime B_CPU_x86 = cpu_platform(1)
comptime B_CPU_x86_64 = cpu_platform(2)
comptime B_CREATE_ACTIVE_ICON_BITMAP: UInt32 = 0x400
comptime B_CREATE_DISABLED_ICON_BITMAPS: UInt32 = 0x1000
comptime B_CREATE_FILE: Int32 = 0x200
comptime B_CREATE_PARTIALLY_ACTIVE_ICON_BITMAP: UInt32 = 0x800
comptime B_CREATE_PROPERTY = command_code(0x50435254)
comptime B_CROSS_DEVICE_LINK: Int32 = -2147459061
comptime B_CURRENT_STATE_COORDINATES = coordinate_space(0)
comptime B_CURRENT_TEAM: Int32 = 0
comptime B_CURRENT_WORKSPACE: Int32 = 0
comptime B_CUT = command_code(0x43435554)
comptime B_DARKEN_1_TINT: Float32 = 1.1469999551773071
comptime B_DARKEN_2_TINT: Float32 = 1.2949999570846558
comptime B_DARKEN_3_TINT: Float32 = 1.406999945640564
comptime B_DARKEN_4_TINT: Float32 = 1.5549999475479126
comptime B_DARKEN_MAX_TINT: Float32 = 2.0
comptime B_DEBUGGER_ALREADY_INSTALLED: Int32 = -2147478528
comptime B_DEFAULT_BUTTON = file_panel_button(1)
comptime B_DEFAULT_MITER_LIMIT: Float32 = 10.0
comptime B_DELETE: UInt32 = 0x7f
comptime B_DELETE_PROPERTY = command_code(0x5044454c)
comptime B_DELETE_TRANSLATOR: UInt32 = 0x5f445254
comptime B_DESKTOP_COLOR = color_which(5)
comptime B_DESKTOP_DIRECTORY = directory_which(0)
comptime B_DEVICE_CONTROL_2: UInt32 = 0x12
comptime B_DEVICE_CONTROL_4: UInt32 = 0x14
comptime B_DEVICE_ERROR_BASE: Int32 = -2147442688
comptime B_DEVICE_FULL: Int32 = -2147459065
comptime B_DEVICE_NOT_FOUND: Int32 = -2147454969
comptime B_DEV_BAD_DRIVE_NUM: Int32 = -2147442686
comptime B_DEV_BAD_PID: Int32 = -2147442666
comptime B_DEV_CONFIGURATION_ERROR: Int32 = -2147442672
comptime B_DEV_CRC_ERROR: Int32 = -2147442668
comptime B_DEV_DATA_OVERRUN: Int32 = -2147442664
comptime B_DEV_DATA_UNDERRUN: Int32 = -2147442663
comptime B_DEV_DISABLED_BY_USER: Int32 = -2147442671
comptime B_DEV_DOOR_OPEN: Int32 = -2147442670
comptime B_DEV_FIFO_OVERRUN: Int32 = -2147442662
comptime B_DEV_FIFO_UNDERRUN: Int32 = -2147442661
comptime B_DEV_FORMAT_ERROR: Int32 = -2147442683
comptime B_DEV_ID_ERROR: Int32 = -2147442679
comptime B_DEV_INVALID_IOCTL: Int32 = -2147442688
comptime B_DEV_INVALID_PIPE: Int32 = -2147442669
comptime B_DEV_MEDIA_CHANGED: Int32 = -2147442675
comptime B_DEV_MEDIA_CHANGE_REQUESTED: Int32 = -2147442674
comptime B_DEV_MULTIPLE_ERRORS: Int32 = -2147442659
comptime B_DEV_NAME_LENGTH: Int32 = 0x80
comptime B_DEV_NOT_READY: Int32 = -2147442676
comptime B_DEV_NO_MEDIA: Int32 = -2147442685
comptime B_DEV_NO_MEMORY: Int32 = -2147442687
comptime B_DEV_PENDING: Int32 = -2147442660
comptime B_DEV_READ_ERROR: Int32 = -2147442678
comptime B_DEV_RECALIBRATE_ERROR: Int32 = -2147442681
comptime B_DEV_RESOURCE_CONFLICT: Int32 = -2147442673
comptime B_DEV_SEEK_ERROR: Int32 = -2147442680
comptime B_DEV_STALLED: Int32 = -2147442667
comptime B_DEV_TIMEOUT: Int32 = -2147442682
comptime B_DEV_TOO_LATE: Int32 = -2147442658
comptime B_DEV_UNEXPECTED_PID: Int32 = -2147442665
comptime B_DEV_UNREADABLE: Int32 = -2147442684
comptime B_DEV_WRITE_ERROR: Int32 = -2147442677
comptime B_DIRECTORY_NODE = node_flavor(4)
comptime B_DIRECTORY_NOT_EMPTY: Int32 = -2147459066
comptime B_DIRECT_MODE_MASK = direct_buffer_state(0xf)
comptime B_DIRECT_MODIFY = direct_buffer_state(2)
comptime B_DIRECT_SPECIFIER: UInt32 = 1
comptime B_DIRECT_START = direct_buffer_state(0)
comptime B_DIRECT_STOP = direct_buffer_state(1)
comptime B_DISABLED_ICON_BITMAP: UInt32 = 0x80
comptime B_DISABLED_LABEL_TINT: Float32 = 1.406999945640564
comptime B_DISABLED_MARK_TINT: Float32 = 0.38499999046325684
comptime B_DISABLE_ANTIALIASING: UInt32 = 1
comptime B_DISPLAY_PRIORITY: Int32 = 0xf
comptime B_DOCUMENT_BACKGROUND_COLOR = color_which(0xb)
comptime B_DOCUMENT_TEXT_COLOR = color_which(0xc)
comptime B_DOCUMENT_WINDOW = window_type(0xb)
comptime B_DOCUMENT_WINDOW_LOOK = window_look(0xb)
comptime B_DONT_DO_THAT: Int32 = -2147483631
comptime B_DOUBLE_TYPE: UInt32 = 0x44424c45
comptime B_DOWN_ARROW: UInt32 = 0x1f
comptime B_DO_NOT_RESCHEDULE: UInt32 = 2
comptime B_DO_NOT_RESIZE_TO_FIT: UInt32 = 1
comptime B_DRAW_ON_CHILDREN: UInt32 = 0x800000
comptime B_DRIVER_CHANGED = direct_driver_state(1)
comptime B_DUPLICATE_REPLY: Int32 = -2147475455
comptime B_EMPTY_ALERT = alert_type(0)
comptime B_END: UInt32 = 4
comptime B_ENDORSABLE = command_code(0x454e444f)
comptime B_ENTER: UInt32 = 0xa
comptime B_ENTERED_VIEW: UInt32 = 0
comptime B_ENTRY_NOT_FOUND: Int32 = -2147459069
comptime B_ERASE_FILE: Int32 = 0x400
comptime B_ERROR: Int32 = -1
comptime B_ERRORS_END: Int32 = -2147418113
comptime B_ESCAPE: UInt32 = 0x1b
comptime B_EVENT_ACQUIRE_SEMAPHORE: UInt32 = 1
comptime B_EVENT_DISCONNECTED: UInt32 = 0x80
comptime B_EVENT_ERROR: UInt32 = 4
comptime B_EVENT_HIGH_PRIORITY_READ: UInt32 = 0x20
comptime B_EVENT_HIGH_PRIORITY_WRITE: UInt32 = 0x40
comptime B_EVENT_INVALID: UInt32 = 0x1000
comptime B_EVENT_PRIORITY_READ: UInt32 = 8
comptime B_EVENT_PRIORITY_WRITE: UInt32 = 0x10
comptime B_EVENT_READ: UInt32 = 1
comptime B_EVENT_WRITE: UInt32 = 2
comptime B_EVEN_ODD: UInt32 = 0
comptime B_EVEN_SPACING = button_spacing(0)
comptime B_EXACT_ADDRESS: Int32 = 1
comptime B_EXECUTE_AREA: Int32 = 4
comptime B_EXECUTE_PROPERTY = command_code(0x50455845)
comptime B_EXITED_VIEW: UInt32 = 2
comptime B_F10_KEY: UInt32 = 0xb
comptime B_F11_KEY: UInt32 = 0xc
comptime B_F12_KEY: UInt32 = 0xd
comptime B_F1_KEY: UInt32 = 2
comptime B_F2_KEY: UInt32 = 3
comptime B_F3_KEY: UInt32 = 4
comptime B_F4_KEY: UInt32 = 5
comptime B_F5_KEY: UInt32 = 6
comptime B_F6_KEY: UInt32 = 7
comptime B_F7_KEY: UInt32 = 8
comptime B_F8_KEY: UInt32 = 9
comptime B_F9_KEY: UInt32 = 0xa
comptime B_FAILURE_COLOR = color_which(0x65)
comptime B_FAIL_IF_EXISTS: Int32 = 0x100
comptime B_FANCY_BORDER = border_style(1)
comptime B_FIELD_NAME_LENGTH: Int32 = 0xff
comptime B_FILE_ERROR: Int32 = -2147459072
comptime B_FILE_EXISTS: Int32 = -2147459070
comptime B_FILE_NAME_LENGTH: Int32 = 0x100
comptime B_FILE_NODE = node_flavor(1)
comptime B_FILE_TOO_LARGE: Int32 = -2147454972
comptime B_FILTER_BITMAP_BILINEAR = bitmap_drawing_options(0x100)
comptime B_FIND_PATHS_SYSTEM_ONLY: UInt32 = 0x10
comptime B_FIND_PATHS_USER_ONLY: UInt32 = 0x20
comptime B_FIND_PATH_ADD_ONS_DIRECTORY = path_base_directory(1)
comptime B_FIND_PATH_APPS_DIRECTORY = path_base_directory(2)
comptime B_FIND_PATH_BIN_DIRECTORY = path_base_directory(3)
comptime B_FIND_PATH_BOOT_DIRECTORY = path_base_directory(4)
comptime B_FIND_PATH_CACHE_DIRECTORY = path_base_directory(5)
comptime B_FIND_PATH_CREATE_DIRECTORY: UInt32 = 1
comptime B_FIND_PATH_CREATE_PARENT_DIRECTORY: UInt32 = 2
comptime B_FIND_PATH_DATA_DIRECTORY = path_base_directory(6)
comptime B_FIND_PATH_DEVELOP_DIRECTORY = path_base_directory(7)
comptime B_FIND_PATH_DEVELOP_LIB_DIRECTORY = path_base_directory(8)
comptime B_FIND_PATH_DOCUMENTATION_DIRECTORY = path_base_directory(9)
comptime B_FIND_PATH_ETC_DIRECTORY = path_base_directory(0xa)
comptime B_FIND_PATH_EXISTING_ONLY: UInt32 = 4
comptime B_FIND_PATH_FONTS_DIRECTORY = path_base_directory(0xb)
comptime B_FIND_PATH_HEADERS_DIRECTORY = path_base_directory(0xc)
comptime B_FIND_PATH_IMAGE_PATH = path_base_directory(0x3e8)
comptime B_FIND_PATH_INSTALLATION_LOCATION_DIRECTORY = path_base_directory(0)
comptime B_FIND_PATH_LIB_DIRECTORY = path_base_directory(0xd)
comptime B_FIND_PATH_LOG_DIRECTORY = path_base_directory(0xe)
comptime B_FIND_PATH_MEDIA_NODES_DIRECTORY = path_base_directory(0xf)
comptime B_FIND_PATH_PACKAGES_DIRECTORY = path_base_directory(0x10)
comptime B_FIND_PATH_PACKAGE_PATH = path_base_directory(0x3e9)
comptime B_FIND_PATH_PREFERENCES_DIRECTORY = path_base_directory(0x11)
comptime B_FIND_PATH_SERVERS_DIRECTORY = path_base_directory(0x12)
comptime B_FIND_PATH_SETTINGS_DIRECTORY = path_base_directory(0x13)
comptime B_FIND_PATH_SOUNDS_DIRECTORY = path_base_directory(0x14)
comptime B_FIND_PATH_SPOOL_DIRECTORY = path_base_directory(0x15)
comptime B_FIND_PATH_TRANSLATORS_DIRECTORY = path_base_directory(0x16)
comptime B_FIND_PATH_VAR_DIRECTORY = path_base_directory(0x17)
comptime B_FIRST_REAL_TIME_PRIORITY: Int32 = 0x64
comptime B_FIXED_SPACING: UInt32 = 3
comptime B_FLOATING_ALL_WINDOW_FEEL = window_feel(6)
comptime B_FLOATING_APP_WINDOW_FEEL = window_feel(4)
comptime B_FLOATING_SUBSET_WINDOW_FEEL = window_feel(5)
comptime B_FLOATING_WINDOW = window_type(0x15)
comptime B_FLOATING_WINDOW_LOOK = window_look(7)
comptime B_FLOAT_TYPE: UInt32 = 0x464c4f54
comptime B_FLUSH_DCACHE: Int32 = 1
comptime B_FLUSH_ICACHE: Int32 = 4
comptime B_FOCUS_FOLLOWS_MOUSE = mode_mouse(1)
comptime B_FOLLOW_ALL: UInt32 = 0x1234
comptime B_FOLLOW_ALL_SIDES: UInt32 = 0x1234
comptime B_FOLLOW_BOTTOM: UInt32 = 0x3030
comptime B_FOLLOW_H_CENTER: UInt32 = 0x505
comptime B_FOLLOW_LEFT: UInt32 = 0x202
comptime B_FOLLOW_LEFT_RIGHT: UInt32 = 0x204
comptime B_FOLLOW_LEFT_TOP: UInt32 = 0x1212
comptime B_FOLLOW_NONE: UInt32 = 0
comptime B_FOLLOW_RIGHT: UInt32 = 0x404
comptime B_FOLLOW_TOP: UInt32 = 0x1010
comptime B_FOLLOW_TOP_BOTTOM: UInt32 = 0x1030
comptime B_FOLLOW_V_CENTER: UInt32 = 0x5050
comptime B_FONTS_UPDATED: UInt32 = 0x5f464e55
comptime B_FONT_ALL = set_font_mask(0x1ff)
comptime B_FONT_ENCODING = set_font_mask(0x20)
comptime B_FONT_FACE = set_font_mask(0x40)
comptime B_FONT_FALSE_BOLD_WIDTH = set_font_mask(0x100)
comptime B_FONT_FAMILY_AND_STYLE = set_font_mask(1)
comptime B_FONT_FAMILY_LENGTH: Int32 = 0x3f
comptime B_FONT_FLAGS = set_font_mask(0x80)
comptime B_FONT_LEFT_TO_RIGHT = font_direction(0)
comptime B_FONT_RIGHT_TO_LEFT = font_direction(1)
comptime B_FONT_ROTATION = set_font_mask(8)
comptime B_FONT_SHEAR = set_font_mask(4)
comptime B_FONT_SIZE = set_font_mask(2)
comptime B_FONT_SPACING = set_font_mask(0x10)
comptime B_FONT_STYLE_LENGTH: Int32 = 0x3f
comptime B_FORCE_ANTIALIASING: UInt32 = 2
comptime B_FRAME_EVENTS: UInt32 = 0x4000000
comptime B_FULL_LOCK: Int32 = 2
comptime B_FULL_POINTER_HISTORY: UInt32 = 8
comptime B_FULL_UPDATE_ON_RESIZE: UInt32 = 0x80000000
comptime B_FUNCTION_KEY: UInt32 = 0x10
comptime B_GAME_AND = game_blit_op(2)
comptime B_GAME_COPY = game_blit_op(0)
comptime B_GAME_COPY_KEYED = game_blit_op(1)
comptime B_GAME_FRONT = game_pane_plane(1)
comptime B_GAME_OR = game_blit_op(3)
comptime B_GAME_PANE_CRT = game_pane_effect(2)
comptime B_GAME_PANE_FRONT_PLANE: UInt32 = 4
comptime B_GAME_PANE_FULLSCREEN: UInt32 = 2
comptime B_GAME_PANE_PLAIN = game_pane_effect(0)
comptime B_GAME_PANE_SCANLINES = game_pane_effect(1)
comptime B_GAME_PANE_SCANLINE_PALETTE: UInt32 = 1
comptime B_GAME_SPRITE_FLIP_X: UInt32 = 2
comptime B_GAME_SPRITE_FLIP_Y: UInt32 = 4
comptime B_GAME_SPRITE_SCREEN: UInt32 = 1
comptime B_GAME_WORLD = game_pane_plane(0)
comptime B_GAME_XOR = game_blit_op(4)
comptime B_GENERAL_ERROR_BASE: Int32 = -2147483648
comptime B_GET_PROPERTY = command_code(0x50474554)
comptime B_GET_SUPPORTED_SUITES = command_code(0x53554954)
comptime B_GRAY1 = color_space(1)
comptime B_GRAY8 = color_space(2)
comptime B_GRAYSCALE_8_BIT = color_space(2)
comptime B_GRAYSCALE_8_BIT_TYPE: UInt32 = 0x47525942
comptime B_HAIKU_64_BIT: Int32 = 1
comptime B_HAIKU_ABI: Int32 = 0x40000
comptime B_HAIKU_ABI_GCC_2: Int32 = 0x20000
comptime B_HAIKU_ABI_GCC_2_ANCIENT: Int32 = 0x20000
comptime B_HAIKU_ABI_GCC_2_BEOS: Int32 = 0x20001
comptime B_HAIKU_ABI_GCC_2_HAIKU: Int32 = 0x20002
comptime B_HAIKU_ABI_GCC_4: Int32 = 0x40000
comptime B_HAIKU_ABI_MAJOR: UInt32 = 0xffff0000
comptime B_HAIKU_BITS: Int32 = 0x40
comptime B_HAIKU_PHYSICAL_64_BIT: Int32 = 1
comptime B_HAIKU_PHYSICAL_BITS: Int32 = 0x40
comptime B_HAIKU_VERSION: Int32 = 0xa01
comptime B_HAIKU_VERSION_1: Int32 = 0x10000
comptime B_HAIKU_VERSION_1_ALPHA_1: Int32 = 0x100
comptime B_HAIKU_VERSION_1_ALPHA_2: Int32 = 0x200
comptime B_HAIKU_VERSION_1_ALPHA_3: Int32 = 0x300
comptime B_HAIKU_VERSION_1_ALPHA_4: Int32 = 0x400
comptime B_HAIKU_VERSION_1_BETA_1: Int32 = 0x500
comptime B_HAIKU_VERSION_1_BETA_2: Int32 = 0x600
comptime B_HAIKU_VERSION_1_BETA_3: Int32 = 0x700
comptime B_HAIKU_VERSION_1_BETA_4: Int32 = 0x800
comptime B_HAIKU_VERSION_1_BETA_5: Int32 = 0x900
comptime B_HAIKU_VERSION_1_BETA_6: Int32 = 0xa00
comptime B_HAIKU_VERSION_1_PRE_ALPHA_2: Int32 = 0x101
comptime B_HAIKU_VERSION_1_PRE_ALPHA_3: Int32 = 0x201
comptime B_HAIKU_VERSION_1_PRE_ALPHA_4: Int32 = 0x301
comptime B_HAIKU_VERSION_1_PRE_BETA_1: Int32 = 0x401
comptime B_HAIKU_VERSION_1_PRE_BETA_2: Int32 = 0x501
comptime B_HAIKU_VERSION_1_PRE_BETA_3: Int32 = 0x601
comptime B_HAIKU_VERSION_1_PRE_BETA_4: Int32 = 0x701
comptime B_HAIKU_VERSION_1_PRE_BETA_5: Int32 = 0x801
comptime B_HAIKU_VERSION_1_PRE_BETA_6: Int32 = 0x901
comptime B_HAIKU_VERSION_1_PRE_BETA_7: Int32 = 0xa01
comptime B_HAIKU_VERSION_BEOS: Int32 = 1
comptime B_HAIKU_VERSION_BONE: Int32 = 2
comptime B_HAIKU_VERSION_DANO: Int32 = 3
comptime B_HANGUL_HANJA_KEY: UInt32 = 0xf1
comptime B_HANGUL_KEY: UInt32 = 0xf0
comptime B_HANKAKU_ZENKAKU: UInt32 = 0xf3
comptime B_HASH_MARKS_BOTH = hash_mark_location(3)
comptime B_HASH_MARKS_BOTTOM = hash_mark_location(2)
comptime B_HASH_MARKS_LEFT = hash_mark_location(1)
comptime B_HASH_MARKS_NONE = hash_mark_location(0)
comptime B_HASH_MARKS_RIGHT = hash_mark_location(2)
comptime B_HASH_MARKS_TOP = hash_mark_location(1)
comptime B_HAS_TUNED_FONT: UInt32 = 1
comptime B_HEAVY_FACE: UInt32 = 0x200
comptime B_HIGHLIGHT_BACKGROUND_TINT: Float32 = 1.2949999570846558
comptime B_HLS24 = color_space(0x4044)
comptime B_HLS32 = color_space(0x4045)
comptime B_HLSA32 = color_space(0x6045)
comptime B_HOME: UInt32 = 1
comptime B_HORIZONTAL = orientation(0)
comptime B_HOST_IS_BENDIAN: Int32 = 0
comptime B_HOST_IS_LENDIAN: Int32 = 1
comptime B_HSI24 = color_space(0x4040)
comptime B_HSI32 = color_space(0x4041)
comptime B_HSIA32 = color_space(0x6041)
comptime B_HSV24 = color_space(0x4042)
comptime B_HSV32 = color_space(0x4043)
comptime B_HSVA32 = color_space(0x6043)
comptime B_IDEA_ALERT = alert_type(2)
comptime B_IDLE_PRIORITY: Int32 = 0
comptime B_ID_SPECIFIER: UInt32 = 7
comptime B_ILLEGAL_DATA: Int32 = -2147465214
comptime B_INACTIVE_ICON_BITMAP: UInt32 = 0
comptime B_INDEX_SPECIFIER: UInt32 = 2
comptime B_INFINITE_TIMEOUT: Int64 = 0x7fffffffffffffff
comptime B_INFO_ALERT = alert_type(1)
comptime B_INPUT_DEVICES_CHANGED = command_code(0x49444348)
comptime B_INPUT_METHOD_AWARE: UInt32 = 0x400000
comptime B_INPUT_METHOD_EVENT = command_code(0x494d4556)
comptime B_INSERT: UInt32 = 5
comptime B_INSIDE_VIEW: UInt32 = 1
comptime B_INSTANT_WARP_FOCUS_FOLLOWS_MOUSE = mode_focus_follows_mouse(2)
comptime B_INT16_TYPE: UInt32 = 0x53485254
comptime B_INT32_TYPE: UInt32 = 0x4c4f4e47
comptime B_INT64_TYPE: UInt32 = 0x4c4c4e47
comptime B_INT8_TYPE: UInt32 = 0x42595445
comptime B_INTERFACE_ERROR_BASE: Int32 = -2147471360
comptime B_INTERRUPTED: Int32 = -2147483638
comptime B_INVALIDATE: UInt32 = 0x5f49564c
comptime B_INVALIDATE_AFTER_LAYOUT: UInt32 = 0x80000
comptime B_INVALIDATE_DCACHE: Int32 = 2
comptime B_INVALIDATE_ICACHE: Int32 = 8
comptime B_IO_ERROR: Int32 = -2147483647
comptime B_ISO_8859_1: UInt32 = 1
comptime B_ISO_8859_10: UInt32 = 0xa
comptime B_ISO_8859_2: UInt32 = 2
comptime B_ISO_8859_3: UInt32 = 3
comptime B_ISO_8859_4: UInt32 = 4
comptime B_ISO_8859_5: UInt32 = 5
comptime B_ISO_8859_6: UInt32 = 6
comptime B_ISO_8859_7: UInt32 = 7
comptime B_ISO_8859_8: UInt32 = 8
comptime B_ISO_8859_9: UInt32 = 9
comptime B_IS_A_DIRECTORY: Int32 = -2147459063
comptime B_IS_FIXED: UInt32 = 2
comptime B_ITALIC_FACE: UInt32 = 1
comptime B_ITEMS_IN_COLUMN = menu_layout(1)
comptime B_ITEMS_IN_MATRIX = menu_layout(2)
comptime B_ITEMS_IN_ROW = menu_layout(0)
comptime B_KATAKANA_HIRAGANA: UInt32 = 0xf2
comptime B_KEEP_ICON_BITMAP: UInt32 = 1
comptime B_KEYBOARD_EVENTS: UInt32 = 2
comptime B_KEYBOARD_NAVIGATION_COLOR = color_which(4)
comptime B_KEY_DOWN: UInt32 = 0x5f4b5944
comptime B_KEY_MAP_LOADED: UInt32 = 0x5f4b4d4c
comptime B_KEY_UP: UInt32 = 0x5f4b5955
comptime B_KILL_CAN_INTERRUPT: UInt32 = 0x20
comptime B_LAB24 = color_space(0x4032)
comptime B_LAB32 = color_space(0x4033)
comptime B_LABA32 = color_space(0x6033)
comptime B_LARGE_ICON_TYPE: UInt32 = 0x49434f4e
comptime B_LAST_BUFFER_ERROR: Int32 = -2147467257
comptime B_LAUNCH_FAILED: Int32 = -2147475451
comptime B_LAUNCH_FAILED_APP_IN_TRASH: Int32 = -2147475444
comptime B_LAUNCH_FAILED_APP_NOT_FOUND: Int32 = -2147475445
comptime B_LAUNCH_FAILED_EXECUTABLE: Int32 = -2147475446
comptime B_LAUNCH_FAILED_FILES_APP_NOT_FOUND: Int32 = -2147475442
comptime B_LAUNCH_FAILED_NO_PREFERRED_APP: Int32 = -2147475443
comptime B_LAUNCH_FAILED_NO_RESOLVE_LINK: Int32 = -2147475447
comptime B_LAYOUT_WINDOW: UInt32 = 0x5f4c4159
comptime B_LAZY_LOCK: Int32 = 1
comptime B_LEFT_ARROW: UInt32 = 0x1c
comptime B_LEFT_COMMAND_KEY: UInt32 = 0x400
comptime B_LEFT_CONTROL_KEY: UInt32 = 0x1000
comptime B_LEFT_OPTION_KEY: UInt32 = 0x4000
comptime B_LEFT_SHIFT_KEY: UInt32 = 0x100
comptime B_LEGACY_EXECUTABLE: Int32 = -2147478778
comptime B_LIBRARY_IMAGE = image_type(2)
comptime B_LIGHTEN_1_TINT: Float32 = 0.5899999737739563
comptime B_LIGHTEN_2_TINT: Float32 = 0.38499999046325684
comptime B_LIGHTEN_MAX_TINT: Float32 = 0.0
comptime B_LIGHT_FACE: UInt32 = 0x100
comptime B_LINK_ACTIVE_COLOR = color_which(0x24)
comptime B_LINK_HOVER_COLOR = color_which(0x22)
comptime B_LINK_LIMIT: Int32 = -2147459060
comptime B_LINK_TARGET = command_code(0x44444c4e)
comptime B_LINK_TEXT_COLOR = color_which(0x21)
comptime B_LINK_VISITED_COLOR = color_which(0x23)
comptime B_LIST_BACKGROUND_COLOR = color_which(0x1c)
comptime B_LIST_ITEM_TEXT_COLOR = color_which(0x1e)
comptime B_LIST_SELECTED_BACKGROUND_COLOR = color_which(0x1d)
comptime B_LIST_SELECTED_ITEM_TEXT_COLOR = color_which(0x1f)
comptime B_LOCK_WINDOW_FOCUS: UInt32 = 1
comptime B_LOMEM: Int32 = 4
comptime B_LOOPER_PORT_DEFAULT_CAPACITY: Int32 = 0xc8
comptime B_LOWEST_ACTIVE_PRIORITY: Int32 = 1
comptime B_LOW_PRIORITY: Int32 = 5
comptime B_MACINTOSH_ROMAN: UInt32 = 0xb
comptime B_MAIL_ACCESS_ERROR: Int32 = -2147450876
comptime B_MAIL_ERROR_BASE: Int32 = -2147450880
comptime B_MAIL_INVALID_MAIL: Int32 = -2147450873
comptime B_MAIL_NO_DAEMON: Int32 = -2147450880
comptime B_MAIL_NO_RECIPIENT: Int32 = -2147450874
comptime B_MAIL_UNKNOWN_FIELD: Int32 = -2147450875
comptime B_MAIL_UNKNOWN_HOST: Int32 = -2147450877
comptime B_MAIL_UNKNOWN_USER: Int32 = -2147450879
comptime B_MAIL_WRONG_PASSWORD: Int32 = -2147450878
comptime B_MAX_MOUSE_BUTTONS: Int32 = 0x10
comptime B_MAX_SYMLINKS: Int32 = 0x10
comptime B_MEDIA_ADDON_DISABLED: Int32 = -2147467141
comptime B_MEDIA_ADDON_FAILED: Int32 = -2147467142
comptime B_MEDIA_ADDON_RESTRICTED: Int32 = -2147467138
comptime B_MEDIA_ALREADY_CONNECTED: Int32 = -2147467145
comptime B_MEDIA_APP_ALREADY_REGISTERED: Int32 = -2147467153
comptime B_MEDIA_APP_NOT_REGISTERED: Int32 = -2147467152
comptime B_MEDIA_BAD_BUFFER: Int32 = -2147467160
comptime B_MEDIA_BAD_CLIP_FORMAT: Int32 = -2147467143
comptime B_MEDIA_BAD_DESTINATION: Int32 = -2147467146
comptime B_MEDIA_BAD_FORMAT: Int32 = -2147467161
comptime B_MEDIA_BAD_NODE: Int32 = -2147467163
comptime B_MEDIA_BAD_SOURCE: Int32 = -2147467147
comptime B_MEDIA_BUFFERS_NOT_RECLAIMED: Int32 = -2147467150
comptime B_MEDIA_BUFFER_ALREADY_EXISTS: Int32 = -2147467156
comptime B_MEDIA_CANNOT_CHANGE_RUN_MODE: Int32 = -2147467154
comptime B_MEDIA_CANNOT_RECLAIM_BUFFERS: Int32 = -2147467151
comptime B_MEDIA_CANNOT_SEEK: Int32 = -2147467155
comptime B_MEDIA_CHANGE_IN_PROGRESS: Int32 = -2147467140
comptime B_MEDIA_DUPLICATE_FORMAT: Int32 = -2147467136
comptime B_MEDIA_ERROR_BASE: Int32 = -2147467264
comptime B_MEDIA_NODE_ALREADY_EXISTS: Int32 = -2147467157
comptime B_MEDIA_NODE_BUSY: Int32 = -2147467162
comptime B_MEDIA_NOT_CONNECTED: Int32 = -2147467144
comptime B_MEDIA_NO_HANDLER: Int32 = -2147467137
comptime B_MEDIA_PARAMETER_GROUP_TYPE: UInt32 = 0x424d4347
comptime B_MEDIA_PARAMETER_TYPE: UInt32 = 0x424d4354
comptime B_MEDIA_PARAMETER_WEB_TYPE: UInt32 = 0x424d4357
comptime B_MEDIA_REALTIME_DISABLED: Int32 = -2147467135
comptime B_MEDIA_REALTIME_UNAVAILABLE: Int32 = -2147467134
comptime B_MEDIA_STALE_CHANGE_COUNT: Int32 = -2147467139
comptime B_MEDIA_SYSTEM_FAILURE: Int32 = -2147467164
comptime B_MEDIA_TIME_SOURCE_BUSY: Int32 = -2147467148
comptime B_MEDIA_TIME_SOURCE_STOPPED: Int32 = -2147467149
comptime B_MEDIA_TOO_MANY_BUFFERS: Int32 = -2147467158
comptime B_MEDIA_TOO_MANY_NODES: Int32 = -2147467159
comptime B_MENU_BACKGROUND_COLOR = color_which(2)
comptime B_MENU_ITEM_TEXT_COLOR = color_which(7)
comptime B_MENU_KEY: UInt32 = 0x80
comptime B_MENU_SELECTED_BACKGROUND_COLOR = color_which(6)
comptime B_MENU_SELECTED_BORDER_COLOR = color_which(9)
comptime B_MENU_SELECTED_ITEM_TEXT_COLOR = color_which(8)
comptime B_MENU_SELECTION_BACKGROUND_COLOR = color_which(6)
comptime B_MESSAGE_NOT_UNDERSTOOD = command_code(0x4d4e4f54)
comptime B_MESSAGE_TO_SELF: Int32 = -2147475454
comptime B_MESSAGE_TYPE: UInt32 = 0x4d534747
comptime B_MESSENGER_TYPE: UInt32 = 0x4d534e47
comptime B_MIDI_ERROR_BASE: Int32 = -2147463168
comptime B_MIME_DATA = command_code(0x4d494d45)
comptime B_MIME_STRING_TYPE: UInt32 = 0x4d494d53
comptime B_MIME_TYPE: UInt32 = 0x4d494d45
comptime B_MIME_TYPE_LENGTH: Int32 = 0xf0
comptime B_MINIMIZE: UInt32 = 0x5f574d4e
comptime B_MINI_ICON_TYPE: UInt32 = 0x4d49434e
comptime B_MISMATCHED_VALUES: Int32 = -2147483642
comptime B_MISSING_LIBRARY: Int32 = -2147478781
comptime B_MISSING_SYMBOL: Int32 = -2147478780
comptime B_MITER_JOIN = join_mode(1)
comptime B_MODAL_ALL_WINDOW_FEEL = window_feel(3)
comptime B_MODAL_APP_WINDOW_FEEL = window_feel(1)
comptime B_MODAL_SUBSET_WINDOW_FEEL = window_feel(2)
comptime B_MODAL_WINDOW = window_type(3)
comptime B_MODAL_WINDOW_LOOK = window_look(3)
comptime B_MODE_CHANGED = direct_driver_state(2)
comptime B_MODIFIERS_CHANGED: UInt32 = 0x5f4d4348
comptime B_MONOCHROME_1_BIT = color_space(1)
comptime B_MONOCHROME_1_BIT_TYPE: UInt32 = 0x4d4e4f42
comptime B_MOUSE_DOWN: UInt32 = 0x5f4d444e
comptime B_MOUSE_ENTER_EXIT: UInt32 = 0x5f4d4558
comptime B_MOUSE_IDLE: UInt32 = 0x5f4d5349
comptime B_MOUSE_MOVED: UInt32 = 0x5f4d4d56
comptime B_MOUSE_UP: UInt32 = 0x5f4d5550
comptime B_MOUSE_WHEEL_CHANGED: UInt32 = 0x5f4d5743
comptime B_MOVE_IF_PARTIALLY_OFFSCREEN: UInt32 = 2
comptime B_MOVE_TARGET = command_code(0x44444d56)
comptime B_NAME_IN_USE: Int32 = -2147483640
comptime B_NAME_NOT_FOUND: Int32 = -2147483641
comptime B_NAME_SPECIFIER: UInt32 = 6
comptime B_NAME_TOO_LONG: Int32 = -2147459068
comptime B_NAVIGABLE: UInt32 = 0x2000000
comptime B_NAVIGABLE_JUMP: UInt32 = 0x8000000
comptime B_NAVIGATION_BASE_COLOR = color_which(4)
comptime B_NAVIGATION_PULSE_COLOR = color_which(0x11)
comptime B_NEGATIVE_FACE: UInt32 = 4
comptime B_NETWORK_ADDRESS_TYPE: UInt32 = 0x4e574144
comptime B_NODE_MONITOR = command_code(0x4e444d4e)
comptime B_NODE_REF_TYPE: UInt32 = 0x4e524546
comptime B_NONZERO: UInt32 = 1
comptime B_NORMAL_FOCUS_FOLLOWS_MOUSE = mode_focus_follows_mouse(0)
comptime B_NORMAL_MOUSE = mode_mouse(0)
comptime B_NORMAL_PRIORITY: Int32 = 0xa
comptime B_NORMAL_TABLE: UInt32 = 0x100
comptime B_NORMAL_WINDOW_FEEL = window_feel(0)
comptime B_NOT_ALLOWED: Int32 = -2147483633
comptime B_NOT_ANCHORED_ON_ACTIVATE: UInt32 = 0x20000
comptime B_NOT_AN_EXECUTABLE: Int32 = -2147478782
comptime B_NOT_A_DIRECTORY: Int32 = -2147459067
comptime B_NOT_A_MESSAGE: Int32 = -2147475440
comptime B_NOT_CLOSABLE: UInt32 = 0x20
comptime B_NOT_H_RESIZABLE: UInt32 = 4
comptime B_NOT_INITIALIZED: Int32 = -2147483635
comptime B_NOT_MINIMIZABLE: UInt32 = 0x4000
comptime B_NOT_MOVABLE: UInt32 = 1
comptime B_NOT_RESIZABLE: UInt32 = 2
comptime B_NOT_SUPPORTED: Int32 = -2147454933
comptime B_NOT_V_RESIZABLE: UInt32 = 8
comptime B_NOT_ZOOMABLE: UInt32 = 0x40
comptime B_NO_BORDER = border_style(2)
comptime B_NO_BORDER_WINDOW_LOOK = window_look(0x13)
comptime B_NO_COLOR = color_which(0)
comptime B_NO_COLOR_SPACE = color_space(0)
comptime B_NO_COMMAND_KEY: UInt32 = 0x10000
comptime B_NO_ERROR: Int32 = 0
comptime B_NO_INIT: Int32 = -2147483635
comptime B_NO_LOCK: Int32 = 0
comptime B_NO_MEMORY: Int32 = -2147483648
comptime B_NO_MORE_FDS: Int32 = -2147459062
comptime B_NO_MORE_PORTS: Int32 = -2147479039
comptime B_NO_MORE_SEMS: Int32 = -2147479551
comptime B_NO_MORE_TEAMS: Int32 = -2147479292
comptime B_NO_MORE_THREADS: Int32 = -2147479295
comptime B_NO_POINTER_HISTORY: UInt32 = 4
comptime B_NO_PRINT_SERVER: Int32 = -2147446784
comptime B_NO_REPLY = command_code(0x4e4f4e45)
comptime B_NO_SERVER_SIDE_WINDOW_MODIFIERS: UInt32 = 0x200
comptime B_NO_SPECIFIER: UInt32 = 0
comptime B_NO_TINT: Float32 = 1.0
comptime B_NO_TRANSLATOR: Int32 = -2147465215
comptime B_NO_TRUNCATION: UInt32 = 0xffffffff
comptime B_NO_WORKSPACE_ACTIVATION: UInt32 = 0x100
comptime B_NUMPAD_EQUAL_KEY: UInt32 = 0x6a
comptime B_NUM_LOCK: UInt32 = 0x20
comptime B_NUM_LOCK_KEY: UInt32 = 0x22
comptime B_OBJECT_TYPE: UInt32 = 0x4f505452
comptime B_OBJECT_TYPE_FD: UInt32 = 0
comptime B_OBJECT_TYPE_PORT: UInt32 = 2
comptime B_OBJECT_TYPE_SEMAPHORE: UInt32 = 1
comptime B_OBJECT_TYPE_THREAD: UInt32 = 3
comptime B_OBSERVER_NOTICE_CHANGE = command_code(0x4e544348)
comptime B_OBSERVER_OBSERVE_ALL: UInt32 = 0xffffffff
comptime B_OFFSET_SPACING = button_spacing(1)
comptime B_OFF_T_TYPE: UInt32 = 0x4f464654
comptime B_OK: Int32 = 0
comptime B_ONE_SHOT_ABSOLUTE_ALARM: UInt32 = 1
comptime B_ONE_SHOT_RELATIVE_ALARM: UInt32 = 2
comptime B_OPEN_AT_END: Int32 = 0x800
comptime B_OPEN_IN_WORKSPACE: UInt32 = 0x5f4f5753
comptime B_OPEN_PANEL = file_panel_mode(0)
comptime B_OPTION_CAPS_SHIFT_TABLE: UInt32 = 2
comptime B_OPTION_CAPS_TABLE: UInt32 = 4
comptime B_OPTION_KEY: UInt32 = 0x40
comptime B_OPTION_SHIFT_TABLE: UInt32 = 8
comptime B_OPTION_TABLE: UInt32 = 0x10
comptime B_OP_ADD = drawing_mode(4)
comptime B_OP_ALPHA = drawing_mode(0xa)
comptime B_OP_BLEND = drawing_mode(6)
comptime B_OP_COPY = drawing_mode(0)
comptime B_OP_ERASE = drawing_mode(2)
comptime B_OP_INVERT = drawing_mode(3)
comptime B_OP_MAX = drawing_mode(8)
comptime B_OP_MIN = drawing_mode(7)
comptime B_OP_OVER = drawing_mode(1)
comptime B_OP_SELECT = drawing_mode(9)
comptime B_OP_SUBTRACT = drawing_mode(5)
comptime B_OS_ERROR_BASE: Int32 = -2147479552
comptime B_OS_NAME_LENGTH: Int32 = 0x20
comptime B_OUTLINED_FACE: UInt32 = 8
comptime B_OUTLINE_RESIZE: UInt32 = 0x1000
comptime B_OUTSIDE_VIEW: UInt32 = 3
comptime B_OVERLAY_FILTER_HORIZONTAL = overlay_options(0x10000)
comptime B_OVERLAY_FILTER_VERTICAL = overlay_options(0x20000)
comptime B_OVERLAY_MIRROR = overlay_options(0x40000)
comptime B_OVERLAY_TRANSFER_CHANNEL = overlay_options(0x80000)
comptime B_PACKAGE_LINKS_DIRECTORY = directory_which(0xfa3)
comptime B_PACKAGE_UPDATE: UInt32 = 0x5f504b55
comptime B_PAGE_DOWN: UInt32 = 0xc
comptime B_PAGE_SIZE: Int32 = 0x1000
comptime B_PAGE_UP: UInt32 = 0xb
comptime B_PANEL_BACKGROUND_COLOR = color_which(1)
comptime B_PANEL_TEXT_COLOR = color_which(0xa)
comptime B_PARENT_VIEW_COORDINATES = coordinate_space(4)
comptime B_PARENT_VIEW_DRAW_COORDINATES = coordinate_space(3)
comptime B_PARTIALLY_ACTIVATE_ICON_BITMAP: UInt32 = 2
comptime B_PARTIAL_READ: Int32 = -2147459056
comptime B_PARTIAL_WRITE: Int32 = -2147459055
comptime B_PARTITION_TOO_SMALL: Int32 = -2147459057
comptime B_PASTE = command_code(0x50535445)
comptime B_PATH_NAME_LENGTH: Int32 = 0x400
comptime B_PATTERN_TYPE: UInt32 = 0x5041544e
comptime B_PAUSE_KEY: UInt32 = 0x10
comptime B_PERIODIC_ALARM: UInt32 = 3
comptime B_PERMISSION_DENIED: Int32 = -2147483646
comptime B_PIXEL_ALIGNMENT = window_alignment(1)
comptime B_PIXEL_ALPHA = source_alpha(0)
comptime B_PLAIN_BORDER = border_style(0)
comptime B_POINTER_EVENTS: UInt32 = 1
comptime B_POINTER_TYPE: UInt32 = 0x504e5452
comptime B_POINT_TYPE: UInt32 = 0x42504e54
comptime B_POSIX_ENOMEM: Int32 = -2147454976
comptime B_POSIX_ERROR_BASE: Int32 = -2147454976
comptime B_POSTSCRIPT_TYPE1_WINDOWS = font_file_format(1)
comptime B_PREFERENCES_DIRECTORY = directory_which(0xfa1)
comptime B_PREVIOUS_STATE_COORDINATES = coordinate_space(1)
comptime B_PRIMARY_MOUSE_BUTTON: UInt32 = 1
comptime B_PRINTER_CHANGED: UInt32 = 0x5f504348
comptime B_PRINTF_POINTER_WIDTH: Int32 = 0x10
comptime B_PRINTING_METRIC = font_metric_mode(1)
comptime B_PRINT_ERROR_BASE: Int32 = -2147446784
comptime B_PRINT_KEY: UInt32 = 0xe
comptime B_PROPERTY_INFO_TYPE: UInt32 = 0x53435444
comptime B_PROPERTY_NAME_LENGTH: Int32 = 0xff
comptime B_PULSE: UInt32 = 0x5f50554c
comptime B_PULSE_NEEDED: UInt32 = 0x10000000
comptime B_QUERY_UPDATE = command_code(0x51555044)
comptime B_QUIT_ON_WINDOW_CLOSE: UInt32 = 0x100000
comptime B_QUIT_REQUESTED: UInt32 = 0x5f515251
comptime B_RANDOMIZED_ANY_ADDRESS: Int32 = 6
comptime B_RANDOMIZED_BASE_ADDRESS: Int32 = 7
comptime B_RANGE_SPECIFIER: UInt32 = 4
comptime B_RAW_TYPE: UInt32 = 0x52415754
comptime B_READY_TO_RUN: UInt32 = 0x5f525452
comptime B_READ_AREA: Int32 = 1
comptime B_READ_ONLY: Int32 = 0
comptime B_READ_ONLY_DEVICE: Int32 = -2147459064
comptime B_READ_WRITE: Int32 = 2
comptime B_REAL_TIME_DISPLAY_PRIORITY: Int32 = 0x64
comptime B_REAL_TIME_PRIORITY: Int32 = 0x78
comptime B_RECT_TYPE: UInt32 = 0x52454354
comptime B_REDO = command_code(0x5245444f)
comptime B_REFS_RECEIVED: UInt32 = 0x5f525243
comptime B_REF_TYPE: UInt32 = 0x52524546
comptime B_REGULAR_FACE: UInt32 = 0x40
comptime B_RELATIVE_TIMEOUT: UInt32 = 8
comptime B_RELEASE_ALL: UInt32 = 8
comptime B_RELEASE_IF_WAITING_ONLY: UInt32 = 0x10
comptime B_RELEASE_OVERLAY_LOCK: UInt32 = 0x5f524f56
comptime B_REPLY = command_code(0x52504c59)
comptime B_RESET_STATUS_BAR = command_code(0x53425253)
comptime B_RESOURCE_NOT_FOUND: Int32 = -2147467262
comptime B_RESOURCE_UNAVAILABLE: Int32 = -2147467261
comptime B_RESULT_NOT_REPRESENTABLE: Int32 = -2147454959
comptime B_RETURN: UInt32 = 0xa
comptime B_REVERSE_INDEX_SPECIFIER: UInt32 = 3
comptime B_REVERSE_RANGE_SPECIFIER: UInt32 = 5
comptime B_RGB15 = color_space(0x10)
comptime B_RGB15_BIG = color_space(0x1010)
comptime B_RGB15_LITTLE = color_space(0x10)
comptime B_RGB16 = color_space(5)
comptime B_RGB16_BIG = color_space(0x1005)
comptime B_RGB16_LITTLE = color_space(5)
comptime B_RGB24 = color_space(3)
comptime B_RGB24_BIG = color_space(0x1003)
comptime B_RGB24_LITTLE = color_space(3)
comptime B_RGB30 = color_space(9)
comptime B_RGB30_BIG = color_space(0x1009)
comptime B_RGB30_LITTLE = color_space(9)
comptime B_RGB32 = color_space(8)
comptime B_RGB32_BIG = color_space(0x1008)
comptime B_RGB32_LITTLE = color_space(8)
comptime B_RGB48 = color_space(0x11)
comptime B_RGB48_BIG = color_space(0x1011)
comptime B_RGB48_LITTLE = color_space(0x11)
comptime B_RGBA15 = color_space(0x2010)
comptime B_RGBA15_BIG = color_space(0x3010)
comptime B_RGBA15_LITTLE = color_space(0x2010)
comptime B_RGBA32 = color_space(0x2008)
comptime B_RGBA32_BIG = color_space(0x3008)
comptime B_RGBA32_LITTLE = color_space(0x2008)
comptime B_RGBA64 = color_space(0x2012)
comptime B_RGBA64_BIG = color_space(0x3012)
comptime B_RGBA64_LITTLE = color_space(0x2012)
comptime B_RGB_16_BIT = color_space(0x10)
comptime B_RGB_32_BIT = color_space(8)
comptime B_RGB_32_BIT_TYPE: UInt32 = 0x52474242
comptime B_RGB_COLOR_TYPE: UInt32 = 0x52474243
comptime B_RIGHT_ARROW: UInt32 = 0x1d
comptime B_RIGHT_COMMAND_KEY: UInt32 = 0x800
comptime B_RIGHT_CONTROL_KEY: UInt32 = 0x2000
comptime B_RIGHT_OPTION_KEY: UInt32 = 0x8000
comptime B_RIGHT_SHIFT_KEY: UInt32 = 0x200
comptime B_ROUND_CAP = cap_mode(0)
comptime B_ROUND_JOIN = join_mode(0)
comptime B_SAME_POSITION_IN_ALL_WORKSPACES: UInt32 = 0x200000
comptime B_SAVE_PANEL = file_panel_mode(1)
comptime B_SAVE_REQUESTED = command_code(0x53415645)
comptime B_SCREEN_CHANGED: UInt32 = 0x5f534348
comptime B_SCREEN_COORDINATES = coordinate_space(6)
comptime B_SCREEN_METRIC = font_metric_mode(0)
comptime B_SCROLL_BAR_THUMB_COLOR = color_which(0x20)
comptime B_SCROLL_KEY: UInt32 = 0xf
comptime B_SCROLL_LOCK: UInt32 = 0x10
comptime B_SCROLL_VIEW_AWARE: UInt32 = 0x200000
comptime B_SECONDARY_MOUSE_BUTTON: UInt32 = 2
comptime B_SELECT_ALL = command_code(0x53414c4c)
comptime B_SERVER_NOT_FOUND: Int32 = -2147467263
comptime B_SET_PROPERTY = command_code(0x50534554)
comptime B_SHADOW_COLOR = color_which(0x13)
comptime B_SHIFT_KEY: UInt32 = 1
comptime B_SHIFT_TABLE: UInt32 = 0x80
comptime B_SHINE_COLOR = color_which(0x12)
comptime B_SHUTDOWN_CANCELLED: Int32 = -2147475439
comptime B_SHUTTING_DOWN: Int32 = -2147475438
comptime B_SILENT_RELAUNCH = command_code(0x4152454c)
comptime B_SIMPLE_DATA = command_code(0x44415441)
comptime B_SIZE_TYPE: UInt32 = 0x53495a45
comptime B_SIZE_T_TYPE: UInt32 = 0x53495a54
comptime B_SIZE_UNLIMITED: Float32 = 1073741824.0
comptime B_SIZE_UNSET: Float32 = -2.0
comptime B_SPACE: UInt32 = 0x20
comptime B_SPACE_BAR_KEY: UInt32 = 0x5e
comptime B_SPECIFIERS_END: UInt32 = 0x80
comptime B_SQUARE_CAP = cap_mode(4)
comptime B_SQUARE_JOIN = join_mode(4)
comptime B_SSIZE_T_TYPE: UInt32 = 0x53535a54
comptime B_STACK_AREA: Int32 = 8
comptime B_STATUS_BAR_COLOR = color_which(0x25)
comptime B_STOP_ALERT = alert_type(4)
comptime B_STORAGE_ERROR_BASE: Int32 = -2147459072
comptime B_STREAM_NOT_FOUND: Int32 = -2147467264
comptime B_STRIKEOUT_FACE: UInt32 = 0x10
comptime B_STRING_LIST_TYPE: UInt32 = 0x5354524c
comptime B_STRING_SPACING: UInt32 = 1
comptime B_STRING_TYPE: UInt32 = 0x43535452
comptime B_SUBPIXEL_PRECISE: UInt32 = 0x1000000
comptime B_SUBSCRIBER_NOT_ENTERED: Int32 = -2147467259
comptime B_SUBSTITUTE: UInt32 = 0x1a
comptime B_SUCCESS_COLOR = color_which(0x64)
comptime B_SUPPORTS_LAYOUT: UInt32 = 0x100000
comptime B_SUSPEND_VIEW_FOCUS: UInt32 = 2
comptime B_SWAP_ALWAYS = swap_action(4)
comptime B_SWAP_BENDIAN_TO_HOST = swap_action(3)
comptime B_SWAP_HOST_TO_BENDIAN = swap_action(1)
comptime B_SWAP_HOST_TO_LENDIAN = swap_action(0)
comptime B_SWAP_LENDIAN_TO_HOST = swap_action(2)
comptime B_SYMBOL_TYPE_ANY: Int32 = 5
comptime B_SYMBOL_TYPE_DATA: Int32 = 1
comptime B_SYMBOL_TYPE_TEXT: Int32 = 2
comptime B_SYMLINK_NODE = node_flavor(2)
comptime B_SYSTEM_ADDONS_DIRECTORY = directory_which(0x3ea)
comptime B_SYSTEM_APPS_DIRECTORY = directory_which(0x3ef)
comptime B_SYSTEM_BIN_DIRECTORY = directory_which(0x3f0)
comptime B_SYSTEM_BOOT_DIRECTORY = directory_which(0x3eb)
comptime B_SYSTEM_CACHE_DIRECTORY = directory_which(0x7e4)
comptime B_SYSTEM_DATA_DIRECTORY = directory_which(0x3f7)
comptime B_SYSTEM_DESKBAR_DIRECTORY = directory_which(0x3fb)
comptime B_SYSTEM_DEVELOP_DIRECTORY = directory_which(0x3f8)
comptime B_SYSTEM_DIRECTORY = directory_which(0x3e8)
comptime B_SYSTEM_DOCUMENTATION_DIRECTORY = directory_which(0x3f2)
comptime B_SYSTEM_ETC_DIRECTORY = directory_which(0x7d8)
comptime B_SYSTEM_FONTS_DIRECTORY = directory_which(0x3ec)
comptime B_SYSTEM_HEADERS_DIRECTORY = directory_which(0x3fa)
comptime B_SYSTEM_IMAGE = image_type(4)
comptime B_SYSTEM_LIB_DIRECTORY = directory_which(0x3ed)
comptime B_SYSTEM_LOG_DIRECTORY = directory_which(0x7dc)
comptime B_SYSTEM_MEDIA_NODES_DIRECTORY = directory_which(0x3f5)
comptime B_SYSTEM_NONPACKAGED_ADDONS_DIRECTORY = directory_which(0x7e8)
comptime B_SYSTEM_NONPACKAGED_BIN_DIRECTORY = directory_which(0x7eb)
comptime B_SYSTEM_NONPACKAGED_DATA_DIRECTORY = directory_which(0x7ec)
comptime B_SYSTEM_NONPACKAGED_DEVELOP_DIRECTORY = directory_which(0x7f2)
comptime B_SYSTEM_NONPACKAGED_DIRECTORY = directory_which(0x7e7)
comptime B_SYSTEM_NONPACKAGED_DOCUMENTATION_DIRECTORY = directory_which(0x7ef)
comptime B_SYSTEM_NONPACKAGED_FONTS_DIRECTORY = directory_which(0x7ed)
comptime B_SYSTEM_NONPACKAGED_HEADERS_DIRECTORY = directory_which(0x7f1)
comptime B_SYSTEM_NONPACKAGED_LIB_DIRECTORY = directory_which(0x7f0)
comptime B_SYSTEM_NONPACKAGED_MEDIA_NODES_DIRECTORY = directory_which(0x7ea)
comptime B_SYSTEM_NONPACKAGED_SOUNDS_DIRECTORY = directory_which(0x7ee)
comptime B_SYSTEM_NONPACKAGED_TRANSLATORS_DIRECTORY = directory_which(0x7e9)
comptime B_SYSTEM_PACKAGES_DIRECTORY = directory_which(0x3f9)
comptime B_SYSTEM_PREFERENCES_DIRECTORY = directory_which(0x3f3)
comptime B_SYSTEM_SERVERS_DIRECTORY = directory_which(0x3ee)
comptime B_SYSTEM_SETTINGS_DIRECTORY = directory_which(0x7da)
comptime B_SYSTEM_SOUNDS_DIRECTORY = directory_which(0x3f6)
comptime B_SYSTEM_SPOOL_DIRECTORY = directory_which(0x7dd)
comptime B_SYSTEM_TEAM: Int32 = 1
comptime B_SYSTEM_TEMP_DIRECTORY = directory_which(0x7de)
comptime B_SYSTEM_TIMEBASE: Int32 = 0
comptime B_SYSTEM_TRANSLATORS_DIRECTORY = directory_which(0x3f4)
comptime B_SYSTEM_VAR_DIRECTORY = directory_which(0x7df)
comptime B_TAB: UInt32 = 9
comptime B_TEAM_USAGE_CHILDREN: Int32 = -1
comptime B_TEAM_USAGE_SELF: Int32 = 0
comptime B_TERTIARY_MOUSE_BUTTON: UInt32 = 4
comptime B_THREAD_ASLEEP = thread_state(4)
comptime B_THREAD_READY = thread_state(2)
comptime B_THREAD_RECEIVING = thread_state(3)
comptime B_THREAD_RUNNING = thread_state(1)
comptime B_THREAD_SUSPENDED = thread_state(5)
comptime B_THREAD_WAITING = thread_state(6)
comptime B_TILE_BITMAP = bitmap_tiling(3)
comptime B_TILE_BITMAP_X = bitmap_tiling(1)
comptime B_TILE_BITMAP_Y = bitmap_tiling(2)
comptime B_TIMED_OUT: Int32 = -2147483639
comptime B_TIMEOUT: UInt32 = 8
comptime B_TIMEOUT_REAL_TIME_BASE: UInt32 = 0x40
comptime B_TIME_TYPE: UInt32 = 0x54494d45
comptime B_TITLED_WINDOW = window_type(1)
comptime B_TITLED_WINDOW_LOOK = window_look(1)
comptime B_TOOL_TIP_BACKGROUND_COLOR = color_which(0x14)
comptime B_TOOL_TIP_TEXT_COLOR = color_which(0x15)
comptime B_TOO_MANY_ARGS: Int32 = -2147454975
comptime B_TOPOLOGY_CORE = topology_level_type(3)
comptime B_TOPOLOGY_PACKAGE = topology_level_type(4)
comptime B_TOPOLOGY_ROOT = topology_level_type(1)
comptime B_TOPOLOGY_SMT = topology_level_type(2)
comptime B_TOPOLOGY_UNKNOWN = topology_level_type(0)
comptime B_TRACKER_ADDON_MESSAGE: UInt32 = 0x5f54414d
comptime B_TRACK_RECT_CORNER = rect_tracking_style(1)
comptime B_TRACK_WHOLE_RECT = rect_tracking_style(0)
comptime B_TRANSLATION_BASE_ERROR: Int32 = -2147465216
comptime B_TRANSLATION_ERROR_BASE: Int32 = -2147465216
comptime B_TRANSLATOR_ADDED: UInt32 = 0x5f415254
comptime B_TRANSLATOR_REMOVED: UInt32 = 0x5f525254
comptime B_TRANSPARENT_BACKGROUND: UInt32 = 0x40000
comptime B_TRASH_DIRECTORY = directory_which(1)
comptime B_TRASH_TARGET = command_code(0x4444524d)
comptime B_TRIANGLE_THUMB = thumb_style(1)
comptime B_TRIM_ICON_BITMAP: UInt32 = 0x100
comptime B_TRIM_ICON_BITMAP_KEEP_ASPECT: UInt32 = 0x200
comptime B_TRUETYPE_WINDOWS = font_file_format(0)
comptime B_TRUNCATE_BEGINNING: UInt32 = 1
comptime B_TRUNCATE_END: UInt32 = 0
comptime B_TRUNCATE_MIDDLE: UInt32 = 2
comptime B_TRUNCATE_SMART: UInt32 = 3
comptime B_UINT16_TYPE: UInt32 = 0x55534854
comptime B_UINT32_TYPE: UInt32 = 0x554c4e47
comptime B_UINT64_TYPE: UInt32 = 0x554c4c47
comptime B_UINT8_TYPE: UInt32 = 0x55425954
comptime B_UNDERSCORE_FACE: UInt32 = 2
comptime B_UNDO = command_code(0x554e444f)
comptime B_UNDO_CLEAR = undo_state(4)
comptime B_UNDO_CUT = undo_state(2)
comptime B_UNDO_DROP = undo_state(5)
comptime B_UNDO_PASTE = undo_state(3)
comptime B_UNDO_TYPING = undo_state(1)
comptime B_UNDO_UNAVAILABLE = undo_state(0)
comptime B_UNICODE_UTF8: UInt32 = 0
comptime B_UNKNOWN_EXECUTABLE: Int32 = -2147478779
comptime B_UNKNOWN_MIME_TYPE: Int32 = -2147475449
comptime B_UNMAPPED_KEY_DOWN: UInt32 = 0x5f554b44
comptime B_UNMAPPED_KEY_UP: UInt32 = 0x5f554b55
comptime B_UNSUPPORTED: Int32 = -2147459058
comptime B_UNTYPED_WINDOW = window_type(0)
comptime B_UPDATE_STATUS_BAR = command_code(0x53425550)
comptime B_UP_ARROW: UInt32 = 0x1e
comptime B_URGENT_DISPLAY_PRIORITY: Int32 = 0x14
comptime B_URGENT_PRIORITY: Int32 = 0x6e
comptime B_USER_ADDONS_DIRECTORY = directory_which(0xbba)
comptime B_USER_APPS_DIRECTORY = directory_which(0xbd7)
comptime B_USER_BIN_DIRECTORY = directory_which(0xbd8)
comptime B_USER_BOOT_DIRECTORY = directory_which(0xbbb)
comptime B_USER_CACHE_DIRECTORY = directory_which(0xbc5)
comptime B_USER_CONFIG_DIRECTORY = directory_which(0xbb9)
comptime B_USER_DATA_DIRECTORY = directory_which(0xbc4)
comptime B_USER_DESKBAR_DIRECTORY = directory_which(0xbbf)
comptime B_USER_DEVELOP_DIRECTORY = directory_which(0xbd4)
comptime B_USER_DIRECTORY = directory_which(0xbb8)
comptime B_USER_DOCUMENTATION_DIRECTORY = directory_which(0xbd5)
comptime B_USER_ETC_DIRECTORY = directory_which(0xbda)
comptime B_USER_FONTS_DIRECTORY = directory_which(0xbbc)
comptime B_USER_HEADERS_DIRECTORY = directory_which(0xbc7)
comptime B_USER_LIB_DIRECTORY = directory_which(0xbbd)
comptime B_USER_LOG_DIRECTORY = directory_which(0xbdb)
comptime B_USER_MEDIA_NODES_DIRECTORY = directory_which(0xbc2)
comptime B_USER_NONPACKAGED_ADDONS_DIRECTORY = directory_which(0xbc9)
comptime B_USER_NONPACKAGED_BIN_DIRECTORY = directory_which(0xbcc)
comptime B_USER_NONPACKAGED_DATA_DIRECTORY = directory_which(0xbcd)
comptime B_USER_NONPACKAGED_DEVELOP_DIRECTORY = directory_which(0xbd3)
comptime B_USER_NONPACKAGED_DIRECTORY = directory_which(0xbc8)
comptime B_USER_NONPACKAGED_DOCUMENTATION_DIRECTORY = directory_which(0xbd0)
comptime B_USER_NONPACKAGED_FONTS_DIRECTORY = directory_which(0xbce)
comptime B_USER_NONPACKAGED_HEADERS_DIRECTORY = directory_which(0xbd2)
comptime B_USER_NONPACKAGED_LIB_DIRECTORY = directory_which(0xbd1)
comptime B_USER_NONPACKAGED_MEDIA_NODES_DIRECTORY = directory_which(0xbcb)
comptime B_USER_NONPACKAGED_SOUNDS_DIRECTORY = directory_which(0xbcf)
comptime B_USER_NONPACKAGED_TRANSLATORS_DIRECTORY = directory_which(0xbca)
comptime B_USER_PACKAGES_DIRECTORY = directory_which(0xbc6)
comptime B_USER_PREFERENCES_DIRECTORY = directory_which(0xbd9)
comptime B_USER_PRINTERS_DIRECTORY = directory_which(0xbc0)
comptime B_USER_SERVERS_DIRECTORY = directory_which(0xbd6)
comptime B_USER_SETTINGS_DIRECTORY = directory_which(0xbbe)
comptime B_USER_SOUNDS_DIRECTORY = directory_which(0xbc3)
comptime B_USER_SPOOL_DIRECTORY = directory_which(0xbdc)
comptime B_USER_TRANSLATORS_DIRECTORY = directory_which(0xbc1)
comptime B_USER_VAR_DIRECTORY = directory_which(0xbdd)
comptime B_USE_BIG_INSETS = BSpacing(-1008)
comptime B_USE_BIG_SPACING = BSpacing(-1008)
comptime B_USE_BORDER_INSETS = BSpacing(-1009)
comptime B_USE_BORDER_SPACING = BSpacing(-1009)
comptime B_USE_CORNER_INSETS = BSpacing(-1007)
comptime B_USE_CORNER_SPACING = BSpacing(-1007)
comptime B_USE_DEFAULT_SPACING = BSpacing(-1002)
comptime B_USE_HALF_ITEM_INSETS = BSpacing(-1004)
comptime B_USE_HALF_ITEM_SPACING = BSpacing(-1004)
comptime B_USE_ITEM_INSETS = BSpacing(-1003)
comptime B_USE_ITEM_SPACING = BSpacing(-1003)
comptime B_USE_SMALL_INSETS = BSpacing(-1006)
comptime B_USE_SMALL_SPACING = BSpacing(-1006)
comptime B_USE_WINDOW_INSETS = BSpacing(-1005)
comptime B_USE_WINDOW_SPACING = BSpacing(-1005)
comptime B_UTILITIES_DIRECTORY = directory_which(0xfa2)
comptime B_UVL24 = color_space(0x4030)
comptime B_UVL32 = color_space(0x4031)
comptime B_UVLA32 = color_space(0x6031)
comptime B_VALUE_CHANGED: UInt32 = 0x5f564348
comptime B_VECTOR_ICON_TYPE: UInt32 = 0x5649434e
comptime B_VERTICAL = orientation(1)
comptime B_VIEWS_SUPPORT_DRAW_BITMAP: UInt32 = 1
comptime B_VIEW_COORDINATES = coordinate_space(2)
comptime B_VIEW_MOVED: UInt32 = 0x5f564d56
comptime B_VIEW_RESIZED: UInt32 = 0x5f565253
comptime B_WAIT_FOR_RETRACE = bitmap_drawing_options(0x800)
comptime B_WARNING_ALERT = alert_type(3)
comptime B_WARP_FOCUS_FOLLOWS_MOUSE = mode_focus_follows_mouse(1)
comptime B_WIDTH_AS_USUAL = button_width(0)
comptime B_WIDTH_FROM_LABEL = button_width(2)
comptime B_WIDTH_FROM_WIDEST = button_width(1)
comptime B_WILL_ACCEPT_FIRST_CLICK: UInt32 = 0x10
comptime B_WILL_DRAW: UInt32 = 0x20000000
comptime B_WINDOW_ACTIVATED: UInt32 = 0x5f414354
comptime B_WINDOW_BORDER_COLOR = color_which(0x19)
comptime B_WINDOW_COORDINATES = coordinate_space(5)
comptime B_WINDOW_INACTIVE_BORDER_COLOR = color_which(0x1a)
comptime B_WINDOW_INACTIVE_TAB_COLOR = color_which(0x17)
comptime B_WINDOW_INACTIVE_TEXT_COLOR = color_which(0x18)
comptime B_WINDOW_MOVED: UInt32 = 0x5f574d56
comptime B_WINDOW_MOVE_BY = command_code(0x57444d42)
comptime B_WINDOW_MOVE_TO = command_code(0x57444d54)
comptime B_WINDOW_RESIZED: UInt32 = 0x5f575253
comptime B_WINDOW_TAB_COLOR = color_which(3)
comptime B_WINDOW_TEXT_COLOR = color_which(0x16)
comptime B_WORKSPACES_CHANGED: UInt32 = 0x5f574347
comptime B_WORKSPACE_ACTIVATED: UInt32 = 0x5f574143
comptime B_WOULD_BLOCK: Int32 = -2147483637
comptime B_WRITE_AREA: Int32 = 2
comptime B_WRITE_ONLY: Int32 = 1
comptime B_XATTR_TYPE: UInt32 = 0x58415452
comptime B_YCbCr411 = color_space(0x4001)
comptime B_YCbCr420 = color_space(0x4004)
comptime B_YCbCr422 = color_space(0x4000)
comptime B_YCbCr444 = color_space(0x4003)
comptime B_YUV12 = color_space(0x402d)
comptime B_YUV411 = color_space(0x4021)
comptime B_YUV420 = color_space(0x4024)
comptime B_YUV422 = color_space(0x4020)
comptime B_YUV444 = color_space(0x4023)
comptime B_YUV9 = color_space(0x402c)
comptime B_ZOOM: UInt32 = 0x5f575a4d


def _status_name(status: Int32) -> StaticString:
    """The name Errors.h gives a `status_t`; "" when it gives none."""
    if status == -2147483648:
        return "B_NO_MEMORY"
    if status == -2147483647:
        return "B_IO_ERROR"
    if status == -2147483646:
        return "B_PERMISSION_DENIED"
    if status == -2147483645:
        return "B_BAD_INDEX"
    if status == -2147483644:
        return "B_BAD_TYPE"
    if status == -2147483643:
        return "B_BAD_VALUE"
    if status == -2147483642:
        return "B_MISMATCHED_VALUES"
    if status == -2147483641:
        return "B_NAME_NOT_FOUND"
    if status == -2147483640:
        return "B_NAME_IN_USE"
    if status == -2147483639:
        return "B_TIMED_OUT"
    if status == -2147483638:
        return "B_INTERRUPTED"
    if status == -2147483637:
        return "B_WOULD_BLOCK"
    if status == -2147483636:
        return "B_CANCELED"
    if status == -2147483635:
        return "B_NO_INIT"
    if status == -2147483634:
        return "B_BUSY"
    if status == -2147483633:
        return "B_NOT_ALLOWED"
    if status == -2147483632:
        return "B_BAD_DATA"
    if status == -2147483631:
        return "B_DONT_DO_THAT"
    if status == -2147479552:
        return "B_BAD_SEM_ID"
    if status == -2147479551:
        return "B_NO_MORE_SEMS"
    if status == -2147479296:
        return "B_BAD_THREAD_ID"
    if status == -2147479295:
        return "B_NO_MORE_THREADS"
    if status == -2147479294:
        return "B_BAD_THREAD_STATE"
    if status == -2147479293:
        return "B_BAD_TEAM_ID"
    if status == -2147479292:
        return "B_NO_MORE_TEAMS"
    if status == -2147479040:
        return "B_BAD_PORT_ID"
    if status == -2147479039:
        return "B_NO_MORE_PORTS"
    if status == -2147478784:
        return "B_BAD_IMAGE_ID"
    if status == -2147478783:
        return "B_BAD_ADDRESS"
    if status == -2147478782:
        return "B_NOT_AN_EXECUTABLE"
    if status == -2147478781:
        return "B_MISSING_LIBRARY"
    if status == -2147478780:
        return "B_MISSING_SYMBOL"
    if status == -2147478779:
        return "B_UNKNOWN_EXECUTABLE"
    if status == -2147478778:
        return "B_LEGACY_EXECUTABLE"
    if status == -2147478528:
        return "B_DEBUGGER_ALREADY_INSTALLED"
    if status == -2147475456:
        return "B_BAD_REPLY"
    if status == -2147475455:
        return "B_DUPLICATE_REPLY"
    if status == -2147475454:
        return "B_MESSAGE_TO_SELF"
    if status == -2147475453:
        return "B_BAD_HANDLER"
    if status == -2147475452:
        return "B_ALREADY_RUNNING"
    if status == -2147475451:
        return "B_LAUNCH_FAILED"
    if status == -2147475450:
        return "B_AMBIGUOUS_APP_LAUNCH"
    if status == -2147475449:
        return "B_UNKNOWN_MIME_TYPE"
    if status == -2147475448:
        return "B_BAD_SCRIPT_SYNTAX"
    if status == -2147475447:
        return "B_LAUNCH_FAILED_NO_RESOLVE_LINK"
    if status == -2147475446:
        return "B_LAUNCH_FAILED_EXECUTABLE"
    if status == -2147475445:
        return "B_LAUNCH_FAILED_APP_NOT_FOUND"
    if status == -2147475444:
        return "B_LAUNCH_FAILED_APP_IN_TRASH"
    if status == -2147475443:
        return "B_LAUNCH_FAILED_NO_PREFERRED_APP"
    if status == -2147475442:
        return "B_LAUNCH_FAILED_FILES_APP_NOT_FOUND"
    if status == -2147475441:
        return "B_BAD_MIME_SNIFFER_RULE"
    if status == -2147475440:
        return "B_NOT_A_MESSAGE"
    if status == -2147475439:
        return "B_SHUTDOWN_CANCELLED"
    if status == -2147475438:
        return "B_SHUTTING_DOWN"
    if status == -2147471360:
        return "B_INTERFACE_ERROR_BASE"
    if status == -2147467264:
        return "B_MEDIA_ERROR_BASE"
    if status == -2147467263:
        return "B_SERVER_NOT_FOUND"
    if status == -2147467262:
        return "B_RESOURCE_NOT_FOUND"
    if status == -2147467261:
        return "B_RESOURCE_UNAVAILABLE"
    if status == -2147467260:
        return "B_BAD_SUBSCRIBER"
    if status == -2147467259:
        return "B_SUBSCRIBER_NOT_ENTERED"
    if status == -2147467258:
        return "B_BUFFER_NOT_AVAILABLE"
    if status == -2147467257:
        return "B_LAST_BUFFER_ERROR"
    if status == -2147467164:
        return "B_MEDIA_SYSTEM_FAILURE"
    if status == -2147467163:
        return "B_MEDIA_BAD_NODE"
    if status == -2147467162:
        return "B_MEDIA_NODE_BUSY"
    if status == -2147467161:
        return "B_MEDIA_BAD_FORMAT"
    if status == -2147467160:
        return "B_MEDIA_BAD_BUFFER"
    if status == -2147467159:
        return "B_MEDIA_TOO_MANY_NODES"
    if status == -2147467158:
        return "B_MEDIA_TOO_MANY_BUFFERS"
    if status == -2147467157:
        return "B_MEDIA_NODE_ALREADY_EXISTS"
    if status == -2147467156:
        return "B_MEDIA_BUFFER_ALREADY_EXISTS"
    if status == -2147467155:
        return "B_MEDIA_CANNOT_SEEK"
    if status == -2147467154:
        return "B_MEDIA_CANNOT_CHANGE_RUN_MODE"
    if status == -2147467153:
        return "B_MEDIA_APP_ALREADY_REGISTERED"
    if status == -2147467152:
        return "B_MEDIA_APP_NOT_REGISTERED"
    if status == -2147467151:
        return "B_MEDIA_CANNOT_RECLAIM_BUFFERS"
    if status == -2147467150:
        return "B_MEDIA_BUFFERS_NOT_RECLAIMED"
    if status == -2147467149:
        return "B_MEDIA_TIME_SOURCE_STOPPED"
    if status == -2147467148:
        return "B_MEDIA_TIME_SOURCE_BUSY"
    if status == -2147467147:
        return "B_MEDIA_BAD_SOURCE"
    if status == -2147467146:
        return "B_MEDIA_BAD_DESTINATION"
    if status == -2147467145:
        return "B_MEDIA_ALREADY_CONNECTED"
    if status == -2147467144:
        return "B_MEDIA_NOT_CONNECTED"
    if status == -2147467143:
        return "B_MEDIA_BAD_CLIP_FORMAT"
    if status == -2147467142:
        return "B_MEDIA_ADDON_FAILED"
    if status == -2147467141:
        return "B_MEDIA_ADDON_DISABLED"
    if status == -2147467140:
        return "B_MEDIA_CHANGE_IN_PROGRESS"
    if status == -2147467139:
        return "B_MEDIA_STALE_CHANGE_COUNT"
    if status == -2147467138:
        return "B_MEDIA_ADDON_RESTRICTED"
    if status == -2147467137:
        return "B_MEDIA_NO_HANDLER"
    if status == -2147467136:
        return "B_MEDIA_DUPLICATE_FORMAT"
    if status == -2147467135:
        return "B_MEDIA_REALTIME_DISABLED"
    if status == -2147467134:
        return "B_MEDIA_REALTIME_UNAVAILABLE"
    if status == -2147465216:
        return "B_TRANSLATION_BASE_ERROR"
    if status == -2147465215:
        return "B_NO_TRANSLATOR"
    if status == -2147465214:
        return "B_ILLEGAL_DATA"
    if status == -2147463168:
        return "B_MIDI_ERROR_BASE"
    if status == -2147459072:
        return "B_FILE_ERROR"
    if status == -2147459070:
        return "B_FILE_EXISTS"
    if status == -2147459069:
        return "B_ENTRY_NOT_FOUND"
    if status == -2147459068:
        return "B_NAME_TOO_LONG"
    if status == -2147459067:
        return "B_NOT_A_DIRECTORY"
    if status == -2147459066:
        return "B_DIRECTORY_NOT_EMPTY"
    if status == -2147459065:
        return "B_DEVICE_FULL"
    if status == -2147459064:
        return "B_READ_ONLY_DEVICE"
    if status == -2147459063:
        return "B_IS_A_DIRECTORY"
    if status == -2147459062:
        return "B_NO_MORE_FDS"
    if status == -2147459061:
        return "B_CROSS_DEVICE_LINK"
    if status == -2147459060:
        return "B_LINK_LIMIT"
    if status == -2147459059:
        return "B_BUSTED_PIPE"
    if status == -2147459058:
        return "B_UNSUPPORTED"
    if status == -2147459057:
        return "B_PARTITION_TOO_SMALL"
    if status == -2147459056:
        return "B_PARTIAL_READ"
    if status == -2147459055:
        return "B_PARTIAL_WRITE"
    if status == -2147454976:
        return "B_POSIX_ENOMEM"
    if status == -2147454975:
        return "B_TOO_MANY_ARGS"
    if status == -2147454972:
        return "B_FILE_TOO_LARGE"
    if status == -2147454969:
        return "B_DEVICE_NOT_FOUND"
    if status == -2147454959:
        return "B_RESULT_NOT_REPRESENTABLE"
    if status == -2147454935:
        return "B_BUFFER_OVERFLOW"
    if status == -2147454933:
        return "B_NOT_SUPPORTED"
    if status == -2147450880:
        return "B_MAIL_NO_DAEMON"
    if status == -2147450879:
        return "B_MAIL_UNKNOWN_USER"
    if status == -2147450878:
        return "B_MAIL_WRONG_PASSWORD"
    if status == -2147450877:
        return "B_MAIL_UNKNOWN_HOST"
    if status == -2147450876:
        return "B_MAIL_ACCESS_ERROR"
    if status == -2147450875:
        return "B_MAIL_UNKNOWN_FIELD"
    if status == -2147450874:
        return "B_MAIL_NO_RECIPIENT"
    if status == -2147450873:
        return "B_MAIL_INVALID_MAIL"
    if status == -2147446784:
        return "B_NO_PRINT_SERVER"
    if status == -2147442688:
        return "B_DEVICE_ERROR_BASE"
    if status == -2147442687:
        return "B_DEV_NO_MEMORY"
    if status == -2147442686:
        return "B_DEV_BAD_DRIVE_NUM"
    if status == -2147442685:
        return "B_DEV_NO_MEDIA"
    if status == -2147442684:
        return "B_DEV_UNREADABLE"
    if status == -2147442683:
        return "B_DEV_FORMAT_ERROR"
    if status == -2147442682:
        return "B_DEV_TIMEOUT"
    if status == -2147442681:
        return "B_DEV_RECALIBRATE_ERROR"
    if status == -2147442680:
        return "B_DEV_SEEK_ERROR"
    if status == -2147442679:
        return "B_DEV_ID_ERROR"
    if status == -2147442678:
        return "B_DEV_READ_ERROR"
    if status == -2147442677:
        return "B_DEV_WRITE_ERROR"
    if status == -2147442676:
        return "B_DEV_NOT_READY"
    if status == -2147442675:
        return "B_DEV_MEDIA_CHANGED"
    if status == -2147442674:
        return "B_DEV_MEDIA_CHANGE_REQUESTED"
    if status == -2147442673:
        return "B_DEV_RESOURCE_CONFLICT"
    if status == -2147442672:
        return "B_DEV_CONFIGURATION_ERROR"
    if status == -2147442671:
        return "B_DEV_DISABLED_BY_USER"
    if status == -2147442670:
        return "B_DEV_DOOR_OPEN"
    if status == -2147442669:
        return "B_DEV_INVALID_PIPE"
    if status == -2147442668:
        return "B_DEV_CRC_ERROR"
    if status == -2147442667:
        return "B_DEV_STALLED"
    if status == -2147442666:
        return "B_DEV_BAD_PID"
    if status == -2147442665:
        return "B_DEV_UNEXPECTED_PID"
    if status == -2147442664:
        return "B_DEV_DATA_OVERRUN"
    if status == -2147442663:
        return "B_DEV_DATA_UNDERRUN"
    if status == -2147442662:
        return "B_DEV_FIFO_OVERRUN"
    if status == -2147442661:
        return "B_DEV_FIFO_UNDERRUN"
    if status == -2147442660:
        return "B_DEV_PENDING"
    if status == -2147442659:
        return "B_DEV_MULTIPLE_ERRORS"
    if status == -2147442658:
        return "B_DEV_TOO_LATE"
    if status == -2147418113:
        return "B_ERRORS_END"
    if status == -1:
        return "B_ERROR"
    if status == 0:
        return "B_OK"
    return ""


def status_of(error: Error) -> Int32:
    """The `status_t` an error the bridge raised stands for, as its
    message ends by naming it: `BMessage::FindInt32: Name not found
    (B_NAME_NOT_FOUND)`. B_ERROR for an error that names none.

    The bridge raises plain `Error`s rather than a typed error, so that
    one `try` block can call it and anything else (design section
    18.4)."""
    var text = String(error)
    var start = text.rfind(" (")
    if start < 0 or not text.endswith(")"):
        return B_ERROR
    var name = String(text[byte = start + 2 : text.byte_length() - 1])
    if name.startswith("status "):
        try:
            return Int32(atol(name[byte=7:]))
        except:
            return B_ERROR
    if name == "B_ALREADY_RUNNING":
        return -2147475452
    if name == "B_AMBIGUOUS_APP_LAUNCH":
        return -2147475450
    if name == "B_APP_ERROR_BASE":
        return -2147475456
    if name == "B_BAD_ADDRESS":
        return -2147478783
    if name == "B_BAD_DATA":
        return -2147483632
    if name == "B_BAD_HANDLER":
        return -2147475453
    if name == "B_BAD_IMAGE_ID":
        return -2147478784
    if name == "B_BAD_INDEX":
        return -2147483645
    if name == "B_BAD_MIME_SNIFFER_RULE":
        return -2147475441
    if name == "B_BAD_PORT_ID":
        return -2147479040
    if name == "B_BAD_REPLY":
        return -2147475456
    if name == "B_BAD_SCRIPT_SYNTAX":
        return -2147475448
    if name == "B_BAD_SEM_ID":
        return -2147479552
    if name == "B_BAD_SUBSCRIBER":
        return -2147467260
    if name == "B_BAD_TEAM_ID":
        return -2147479293
    if name == "B_BAD_THREAD_ID":
        return -2147479296
    if name == "B_BAD_THREAD_STATE":
        return -2147479294
    if name == "B_BAD_TYPE":
        return -2147483644
    if name == "B_BAD_VALUE":
        return -2147483643
    if name == "B_BUFFER_NOT_AVAILABLE":
        return -2147467258
    if name == "B_BUFFER_OVERFLOW":
        return -2147454935
    if name == "B_BUSTED_PIPE":
        return -2147459059
    if name == "B_BUSY":
        return -2147483634
    if name == "B_CANCELED":
        return -2147483636
    if name == "B_CROSS_DEVICE_LINK":
        return -2147459061
    if name == "B_DEBUGGER_ALREADY_INSTALLED":
        return -2147478528
    if name == "B_DEVICE_ERROR_BASE":
        return -2147442688
    if name == "B_DEVICE_FULL":
        return -2147459065
    if name == "B_DEVICE_NOT_FOUND":
        return -2147454969
    if name == "B_DEV_BAD_DRIVE_NUM":
        return -2147442686
    if name == "B_DEV_BAD_PID":
        return -2147442666
    if name == "B_DEV_CONFIGURATION_ERROR":
        return -2147442672
    if name == "B_DEV_CRC_ERROR":
        return -2147442668
    if name == "B_DEV_DATA_OVERRUN":
        return -2147442664
    if name == "B_DEV_DATA_UNDERRUN":
        return -2147442663
    if name == "B_DEV_DISABLED_BY_USER":
        return -2147442671
    if name == "B_DEV_DOOR_OPEN":
        return -2147442670
    if name == "B_DEV_FIFO_OVERRUN":
        return -2147442662
    if name == "B_DEV_FIFO_UNDERRUN":
        return -2147442661
    if name == "B_DEV_FORMAT_ERROR":
        return -2147442683
    if name == "B_DEV_ID_ERROR":
        return -2147442679
    if name == "B_DEV_INVALID_IOCTL":
        return -2147442688
    if name == "B_DEV_INVALID_PIPE":
        return -2147442669
    if name == "B_DEV_MEDIA_CHANGED":
        return -2147442675
    if name == "B_DEV_MEDIA_CHANGE_REQUESTED":
        return -2147442674
    if name == "B_DEV_MULTIPLE_ERRORS":
        return -2147442659
    if name == "B_DEV_NOT_READY":
        return -2147442676
    if name == "B_DEV_NO_MEDIA":
        return -2147442685
    if name == "B_DEV_NO_MEMORY":
        return -2147442687
    if name == "B_DEV_PENDING":
        return -2147442660
    if name == "B_DEV_READ_ERROR":
        return -2147442678
    if name == "B_DEV_RECALIBRATE_ERROR":
        return -2147442681
    if name == "B_DEV_RESOURCE_CONFLICT":
        return -2147442673
    if name == "B_DEV_SEEK_ERROR":
        return -2147442680
    if name == "B_DEV_STALLED":
        return -2147442667
    if name == "B_DEV_TIMEOUT":
        return -2147442682
    if name == "B_DEV_TOO_LATE":
        return -2147442658
    if name == "B_DEV_UNEXPECTED_PID":
        return -2147442665
    if name == "B_DEV_UNREADABLE":
        return -2147442684
    if name == "B_DEV_WRITE_ERROR":
        return -2147442677
    if name == "B_DIRECTORY_NOT_EMPTY":
        return -2147459066
    if name == "B_DONT_DO_THAT":
        return -2147483631
    if name == "B_DUPLICATE_REPLY":
        return -2147475455
    if name == "B_ENTRY_NOT_FOUND":
        return -2147459069
    if name == "B_ERROR":
        return -1
    if name == "B_ERRORS_END":
        return -2147418113
    if name == "B_FILE_ERROR":
        return -2147459072
    if name == "B_FILE_EXISTS":
        return -2147459070
    if name == "B_FILE_TOO_LARGE":
        return -2147454972
    if name == "B_GENERAL_ERROR_BASE":
        return -2147483648
    if name == "B_ILLEGAL_DATA":
        return -2147465214
    if name == "B_INTERFACE_ERROR_BASE":
        return -2147471360
    if name == "B_INTERRUPTED":
        return -2147483638
    if name == "B_IO_ERROR":
        return -2147483647
    if name == "B_IS_A_DIRECTORY":
        return -2147459063
    if name == "B_LAST_BUFFER_ERROR":
        return -2147467257
    if name == "B_LAUNCH_FAILED":
        return -2147475451
    if name == "B_LAUNCH_FAILED_APP_IN_TRASH":
        return -2147475444
    if name == "B_LAUNCH_FAILED_APP_NOT_FOUND":
        return -2147475445
    if name == "B_LAUNCH_FAILED_EXECUTABLE":
        return -2147475446
    if name == "B_LAUNCH_FAILED_FILES_APP_NOT_FOUND":
        return -2147475442
    if name == "B_LAUNCH_FAILED_NO_PREFERRED_APP":
        return -2147475443
    if name == "B_LAUNCH_FAILED_NO_RESOLVE_LINK":
        return -2147475447
    if name == "B_LEGACY_EXECUTABLE":
        return -2147478778
    if name == "B_LINK_LIMIT":
        return -2147459060
    if name == "B_MAIL_ACCESS_ERROR":
        return -2147450876
    if name == "B_MAIL_ERROR_BASE":
        return -2147450880
    if name == "B_MAIL_INVALID_MAIL":
        return -2147450873
    if name == "B_MAIL_NO_DAEMON":
        return -2147450880
    if name == "B_MAIL_NO_RECIPIENT":
        return -2147450874
    if name == "B_MAIL_UNKNOWN_FIELD":
        return -2147450875
    if name == "B_MAIL_UNKNOWN_HOST":
        return -2147450877
    if name == "B_MAIL_UNKNOWN_USER":
        return -2147450879
    if name == "B_MAIL_WRONG_PASSWORD":
        return -2147450878
    if name == "B_MEDIA_ADDON_DISABLED":
        return -2147467141
    if name == "B_MEDIA_ADDON_FAILED":
        return -2147467142
    if name == "B_MEDIA_ADDON_RESTRICTED":
        return -2147467138
    if name == "B_MEDIA_ALREADY_CONNECTED":
        return -2147467145
    if name == "B_MEDIA_APP_ALREADY_REGISTERED":
        return -2147467153
    if name == "B_MEDIA_APP_NOT_REGISTERED":
        return -2147467152
    if name == "B_MEDIA_BAD_BUFFER":
        return -2147467160
    if name == "B_MEDIA_BAD_CLIP_FORMAT":
        return -2147467143
    if name == "B_MEDIA_BAD_DESTINATION":
        return -2147467146
    if name == "B_MEDIA_BAD_FORMAT":
        return -2147467161
    if name == "B_MEDIA_BAD_NODE":
        return -2147467163
    if name == "B_MEDIA_BAD_SOURCE":
        return -2147467147
    if name == "B_MEDIA_BUFFERS_NOT_RECLAIMED":
        return -2147467150
    if name == "B_MEDIA_BUFFER_ALREADY_EXISTS":
        return -2147467156
    if name == "B_MEDIA_CANNOT_CHANGE_RUN_MODE":
        return -2147467154
    if name == "B_MEDIA_CANNOT_RECLAIM_BUFFERS":
        return -2147467151
    if name == "B_MEDIA_CANNOT_SEEK":
        return -2147467155
    if name == "B_MEDIA_CHANGE_IN_PROGRESS":
        return -2147467140
    if name == "B_MEDIA_DUPLICATE_FORMAT":
        return -2147467136
    if name == "B_MEDIA_ERROR_BASE":
        return -2147467264
    if name == "B_MEDIA_NODE_ALREADY_EXISTS":
        return -2147467157
    if name == "B_MEDIA_NODE_BUSY":
        return -2147467162
    if name == "B_MEDIA_NOT_CONNECTED":
        return -2147467144
    if name == "B_MEDIA_NO_HANDLER":
        return -2147467137
    if name == "B_MEDIA_REALTIME_DISABLED":
        return -2147467135
    if name == "B_MEDIA_REALTIME_UNAVAILABLE":
        return -2147467134
    if name == "B_MEDIA_STALE_CHANGE_COUNT":
        return -2147467139
    if name == "B_MEDIA_SYSTEM_FAILURE":
        return -2147467164
    if name == "B_MEDIA_TIME_SOURCE_BUSY":
        return -2147467148
    if name == "B_MEDIA_TIME_SOURCE_STOPPED":
        return -2147467149
    if name == "B_MEDIA_TOO_MANY_BUFFERS":
        return -2147467158
    if name == "B_MEDIA_TOO_MANY_NODES":
        return -2147467159
    if name == "B_MESSAGE_TO_SELF":
        return -2147475454
    if name == "B_MIDI_ERROR_BASE":
        return -2147463168
    if name == "B_MISMATCHED_VALUES":
        return -2147483642
    if name == "B_MISSING_LIBRARY":
        return -2147478781
    if name == "B_MISSING_SYMBOL":
        return -2147478780
    if name == "B_NAME_IN_USE":
        return -2147483640
    if name == "B_NAME_NOT_FOUND":
        return -2147483641
    if name == "B_NAME_TOO_LONG":
        return -2147459068
    if name == "B_NOT_ALLOWED":
        return -2147483633
    if name == "B_NOT_AN_EXECUTABLE":
        return -2147478782
    if name == "B_NOT_A_DIRECTORY":
        return -2147459067
    if name == "B_NOT_A_MESSAGE":
        return -2147475440
    if name == "B_NOT_INITIALIZED":
        return -2147483635
    if name == "B_NOT_SUPPORTED":
        return -2147454933
    if name == "B_NO_ERROR":
        return 0
    if name == "B_NO_INIT":
        return -2147483635
    if name == "B_NO_MEMORY":
        return -2147483648
    if name == "B_NO_MORE_FDS":
        return -2147459062
    if name == "B_NO_MORE_PORTS":
        return -2147479039
    if name == "B_NO_MORE_SEMS":
        return -2147479551
    if name == "B_NO_MORE_TEAMS":
        return -2147479292
    if name == "B_NO_MORE_THREADS":
        return -2147479295
    if name == "B_NO_PRINT_SERVER":
        return -2147446784
    if name == "B_NO_TRANSLATOR":
        return -2147465215
    if name == "B_OK":
        return 0
    if name == "B_OS_ERROR_BASE":
        return -2147479552
    if name == "B_PARTIAL_READ":
        return -2147459056
    if name == "B_PARTIAL_WRITE":
        return -2147459055
    if name == "B_PARTITION_TOO_SMALL":
        return -2147459057
    if name == "B_PERMISSION_DENIED":
        return -2147483646
    if name == "B_POSIX_ENOMEM":
        return -2147454976
    if name == "B_POSIX_ERROR_BASE":
        return -2147454976
    if name == "B_PRINT_ERROR_BASE":
        return -2147446784
    if name == "B_READ_ONLY_DEVICE":
        return -2147459064
    if name == "B_RESOURCE_NOT_FOUND":
        return -2147467262
    if name == "B_RESOURCE_UNAVAILABLE":
        return -2147467261
    if name == "B_RESULT_NOT_REPRESENTABLE":
        return -2147454959
    if name == "B_SERVER_NOT_FOUND":
        return -2147467263
    if name == "B_SHUTDOWN_CANCELLED":
        return -2147475439
    if name == "B_SHUTTING_DOWN":
        return -2147475438
    if name == "B_STORAGE_ERROR_BASE":
        return -2147459072
    if name == "B_STREAM_NOT_FOUND":
        return -2147467264
    if name == "B_SUBSCRIBER_NOT_ENTERED":
        return -2147467259
    if name == "B_TIMED_OUT":
        return -2147483639
    if name == "B_TOO_MANY_ARGS":
        return -2147454975
    if name == "B_TRANSLATION_BASE_ERROR":
        return -2147465216
    if name == "B_TRANSLATION_ERROR_BASE":
        return -2147465216
    if name == "B_UNKNOWN_EXECUTABLE":
        return -2147478779
    if name == "B_UNKNOWN_MIME_TYPE":
        return -2147475449
    if name == "B_UNSUPPORTED":
        return -2147459058
    if name == "B_WOULD_BLOCK":
        return -2147483637
    return B_ERROR
