# ===----------------------------------------------------------------------=== #
# Copyright (c) 2026, MojoProse. All rights reserved.
#
# Licensed under the Apache License v2.0 with LLVM Exceptions:
# https://llvm.org/LICENSE.txt
#
# Generated by Haiku/generator/mojobe_gen.py from the Haiku headers and
# bridge.toml. Do not edit: change the generator or its annotations.
# ===----------------------------------------------------------------------=== #
"""The Be API's value types, laid out as the Haiku headers lay them out
(checked at compile time against clang's layout for the Haiku target),
and the constant values of those types."""

from std.sys import size_of, align_of


@fieldwise_init
struct BRect(Equatable, TrivialRegisterPassable, Writable):
    """`BRect`, 16 bytes."""

    var left: Float32
    var top: Float32
    var right: Float32
    var bottom: Float32

    def Width(self) -> Float32:
        """The width, as `BRect::Width()` has it (right - left)."""
        return self.right - self.left

    def Height(self) -> Float32:
        """The height, as `BRect::Height()` has it (bottom - top)."""
        return self.bottom - self.top

    def write_to(self, mut writer: Some[Writer]):
        writer.write(
            "BRect(",
            self.left,
            ", ",
            self.top,
            ", ",
            self.right,
            ", ",
            self.bottom,
            ")",
        )


@fieldwise_init
struct BPoint(Equatable, TrivialRegisterPassable, Writable):
    """`BPoint`, 8 bytes."""

    var x: Float32
    var y: Float32

    def write_to(self, mut writer: Some[Writer]):
        writer.write("BPoint(", self.x, ", ", self.y, ")")


@fieldwise_init
struct rgb_color(Equatable, TrivialRegisterPassable):
    """`rgb_color`, 4 bytes."""

    var red: UInt8
    var green: UInt8
    var blue: UInt8
    var alpha: UInt8


@fieldwise_init
struct font_height(Equatable, TrivialRegisterPassable):
    """`font_height`, 12 bytes."""

    var ascent: Float32
    var descent: Float32
    var leading: Float32


@fieldwise_init
struct clipping_rect(Equatable, TrivialRegisterPassable):
    """`clipping_rect`, 16 bytes."""

    var left: Int32
    var top: Int32
    var right: Int32
    var bottom: Int32


@fieldwise_init
struct screen_id(Equatable, TrivialRegisterPassable):
    """`screen_id`, 4 bytes."""

    var id: Int32


@fieldwise_init
struct pattern(Equatable, TrivialRegisterPassable):
    """`pattern`, 8 bytes."""

    var data: UInt64


def _check_layouts():
    """Fails the compile when a value type is not laid out as clang lays it out for Haiku."""
    comptime assert size_of[BRect]() == 16
    comptime assert align_of[BRect]() == 4
    comptime assert size_of[BPoint]() == 8
    comptime assert align_of[BPoint]() == 4
    comptime assert size_of[rgb_color]() == 4
    comptime assert align_of[rgb_color]() == 1
    comptime assert size_of[font_height]() == 12
    comptime assert align_of[font_height]() == 4
    comptime assert size_of[clipping_rect]() == 16
    comptime assert align_of[clipping_rect]() == 4
    comptime assert size_of[screen_id]() == 4
    comptime assert align_of[screen_id]() == 4
    comptime assert size_of[pattern]() == 8


# ===----------------------------------------------------------------------=== #
# Hand-written (Haiku/generator/snippets/_values.mojo): helpers, and the
# constants of value types, which are `extern const` objects in the headers
# and so have no value clang can give the generator.
# ===----------------------------------------------------------------------=== #


def rgb(red: UInt8, green: UInt8, blue: UInt8, alpha: UInt8 = 255) -> rgb_color:
    """An `rgb_color`, opaque unless told otherwise."""
    return rgb_color(red, green, blue, alpha)


comptime B_ORIGIN = BPoint(0, 0)
"""`B_ORIGIN`: the point (0, 0)."""

comptime B_SOLID_HIGH = pattern(0xFFFFFFFFFFFFFFFF)
"""`B_SOLID_HIGH`: every pixel in the high colour."""

comptime B_SOLID_LOW = pattern(0)
"""`B_SOLID_LOW`: every pixel in the low colour."""

comptime B_MIXED_COLORS = pattern(0x55AA55AA55AA55AA)
"""`B_MIXED_COLORS`: a checkerboard of the high and low colours."""

comptime B_MAIN_SCREEN_ID = screen_id(0)
"""`B_MAIN_SCREEN_ID`: the main screen."""
