# ===----------------------------------------------------------------------=== #
# Copyright (c) 2026, MojoProse. All rights reserved.
#
# Licensed under the Apache License v2.0 with LLVM Exceptions:
# https://llvm.org/LICENSE.txt
#
# Generated by Haiku/generator/mojobe_gen.py from the Haiku headers and
# bridge.toml. Do not edit: change the generator or its annotations.
# ===----------------------------------------------------------------------=== #
"""The Be API's hook functions, one trait each (design section 8.3). A
type implements the hooks it wants; making a `BView` or a `BWindow` from
it builds that type's hook table at compile time, and a hook it does not
implement never enters Mojo."""

from ._api import (
    HandlerMessageReceived,
    HandlerHooks,
    LooperMessageReceived,
    LooperQuitRequested,
    LooperHooks,
    ApplicationReadyToRun,
    ApplicationMessageReceived,
    ApplicationQuitRequested,
    ApplicationAboutRequested,
    ApplicationPulse,
    ApplicationRefsReceived,
    ApplicationHooks,
    WindowMessageReceived,
    WindowQuitRequested,
    WindowFrameMoved,
    WindowFrameResized,
    WindowWindowActivated,
    WindowWorkspaceActivated,
    WindowMenusBeginning,
    WindowMenusEnded,
    WindowZoom,
    WindowMinimize,
    WindowHooks,
    ViewDraw,
    ViewDrawAfterChildren,
    ViewMouseDown,
    ViewMouseUp,
    ViewMouseMoved,
    ViewKeyDown,
    ViewKeyUp,
    ViewMessageReceived,
    ViewAttachedToWindow,
    ViewAllAttached,
    ViewDetachedFromWindow,
    ViewAllDetached,
    ViewFrameMoved,
    ViewFrameResized,
    ViewWindowActivated,
    ViewPulse,
    ViewHooks,
    ListViewSelectionChanged,
    ListViewHooks,
    GamePaneMessageReceived,
    GamePaneQuitRequested,
    GamePaneWindowActivated,
    GamePaneHooks,
)
